Repository knative/func, pull requests merged in 2020-12, with the labels that each got.

#243 fix: fix the help text for the describe function
  cmd/describe.go
Labels: source/commands

#242 feat: add --all-namespaces flag to `func list`
  client.go
  cmd/list.go
  knative/lister.go
Labels: source/commands, type/enhancement

#239 chore: ensure that pkger is run when templates change
  .github/workflows/ci.yaml
  .github/workflows/pull_requests.yaml
  Makefile
Labels: project/chore, templates/go, templates/node, templates/quarkus

#247 chore: pull and run pkger on main branch CI
  .github/workflows/ci.yaml
Labels: project/chore

#248 fix: change --format flag to --output for list and describe commands
  cmd/describe.go
  cmd/list.go
  docs/commands.md
Labels: source/commands

#240 fix: print "No functions found in [ns] namespace" for kn func list
  cmd/list.go
Labels: source/commands, type/enhancement

#252 fix: correcting broken merge
  cmd/list.go
  go.sum
  pkged.go
Labels: source/commands, type/bug
