Repository knative/func, pull requests merged in 2020-09, with the labels that each got.

#88 fix: image override
  client.go
  cmd/create.go
  function.go
Labels: source/lib, type/bug

#104 chore(actions): add binary uploads to develop branch CI
  .github/workflows/develop.yaml
Labels: project/chore

#99 templates(node): make node templates use npx @redhat/faas-js-runtime
  pkged.go
  templates/node/events/local.js
  templates/node/events/package-lock.json
  templates/node/events/package.json
  templates/node/http/local.js
  templates/node/http/package-lock.json
  templates/node/http/package.json
Labels: templates/node

#118 feat: default to no confirmation prompts for CLI commands
  client.go
  cmd/build.go
  cmd/create.go
  cmd/delete.go
  cmd/deploy.go
  cmd/init.go
  cmd/root.go
  cmd/update.go
Labels: source/commands, type/enhancement

#124 chore: remove dead appsody code
  appsody/builder.go
  appsody/initializer.go
  appsody/initializer_test.go
  appsody/runner_test.go
  appsody/testdata/example.com/runnable/handle.go
Labels: project/chore, source/lib

#129 chore: remove [options] from usage string
  cmd/build.go
  cmd/create.go
  cmd/describe.go
  cmd/init.go
  cmd/list.go
  cmd/update.go
Labels: project/chore, source/commands

#128 docs: add documentation for CLI commands
  docs/commands.md
Labels: info/discussion, project/documentation

#130 fix: correct value for config path and robustify
  cmd/create.go
  cmd/init.go
  cmd/root.go
Labels: project/chore, source/configuration

#132 feat: add local debugging to node.js templates
  pkged.go
  templates/node/events/package.json
  templates/node/http/package.json
Labels: templates/node, type/enhancement

#133 src: add Long command descriptions for each of the CLI commands
  cmd/build.go
  cmd/create.go
  cmd/delete.go
  cmd/deploy.go
  cmd/describe.go
  cmd/init.go
  cmd/list.go
  cmd/run.go
  cmd/update.go
  go.mod
  pkged.go
Labels: project/documentation, source/commands

#136 feat: set builder images in templates and .faas.yaml
  buildpacks/builder.go
  client.go
  cmd/completion_util.go
  cmd/init.go
  config.go
  function.go
  pkged.go
  templates/go/events/.builders.yaml
  templates/go/http/.builders.yaml
  templates/node/events/.builders.yaml
  templates/node/http/.builders.yaml
  templates/quarkus/events/.builders.yaml
  templates/quarkus/http/.builders.yaml
Labels: source/configuration, templates/go, templates/node, templates/quarkus, type/enhancement

#139 chore(ci): fix release binary uploads
  .github/workflows/ci.yaml
Labels: project/chore, type/bug

#143 chore: rename .faas.yaml to faas.yaml
  cmd/build.go
  cmd/create.go
  cmd/delete.go
  cmd/deploy.go
  cmd/describe.go
  cmd/list.go
  cmd/update.go
  config.go
  docs/commands.md
Labels: project/chore, source/configuration
