Repository knative/func, pull requests merged in 2020-10, with the labels that each got.

#146 chore(actions): update release-please-action to latest 2.4.1
  .github/workflows/ci.yaml
Labels: project/chore

#153 chore: ignore vscode files
  .gitignore
Labels: project/chore

#152 feat!: combine deploy and update commands
  client.go
  client_test.go
  cmd/create.go
  cmd/deploy.go
  cmd/root.go
  cmd/update.go
  docs/commands.md
  function.go
  knative/client.go
  knative/deployer.go
  knative/updater.go
  mock/updater.go
Labels: source/commands

#150 chore(templates): bump faas-js-runtime to 0.3.0 and update the name
  go.mod
  go.sum
  pkged.go
  templates/node/events/package-lock.json
  templates/node/events/package.json
  templates/node/events/test/integration.js
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/node/http/test/integration.js
Labels: templates/node, type/enhancement

#156 src!: change all references of "repository" to "registry" for images
  client.go
  client_test.go
  cmd/build.go
  cmd/create.go
  cmd/deploy.go
  cmd/root.go
  docs/commands.md
  docs/integrators_guide.md
  function.go
  templates.go
Labels: source/configuration, type/enhancement

#155 feat(kn): Enable faas to be integrated as plugin to kn
  cmd/root.go
  plugin/plugin.go
Labels: source/commands, type/enhancement

#163 fix: Fix root cmd init
  cmd/root.go
  plugin/plugin.go
Labels: source/commands

#170 chore(ci): tweak release-please-action to bump minor pre major.
  .github/workflows/ci.yaml
Labels: project/releases

#172 feat: pass CloudEvent data as first parameter for Node.js event fns
  go.sum
  pkged.go
  templates/node/events/README.md
  templates/node/events/index.js
  templates/node/events/package-lock.json
  templates/node/events/package.json
  templates/node/events/test/unit.js
  templates/node/http/package-lock.json
  templates/node/http/package.json
Labels: templates/node

#174 feat: add health probes to node & go service
  knative/deployer.go
Labels: source/lib

#175 src: use image digest
  client.go
  client_test.go
  config.go
  docker/pusher.go
  docker/runner.go
  function.go
  knative/deployer.go
  mock/pusher.go
Labels: source/lib
