Repository knative/func, pull requests merged in 2021-11, with the labels that each got.

#615 test: setup CodeCov report (codecov.io) upload and bot
  .codecov.yaml
Labels: lgtm, approved, cla: yes, size/XS

#618 chore: bump go to 1.16 in ci workflow
  .github/workflows/ci.yaml
Labels: lgtm, approved, cla: yes, size/XS, kind/chore

#594 Support ssh docker daemon connection
  buildpacks/builder.go
  docker/docker_client.go
  docker/pusher.go
  docker/runner.go
  go.mod
  ssh/ssh_dialer.go
  ssh/terminal.go
  third_party/VENDOR-LICENSE/github.com/docker/cli/cli/LICENSE
  third_party/VENDOR-LICENSE/github.com/docker/cli/cli/NOTICE
  vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/pdeathsig_linux.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/pdeathsig_nolinux.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/session_unix.go
  vendor/github.com/docker/cli/cli/connhelper/commandconn/session_windows.go
  vendor/github.com/docker/cli/cli/connhelper/connhelper.go
  vendor/github.com/docker/cli/cli/connhelper/ssh/ssh.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, cla: yes

#612 test: add e2e test for config volumes
  test/_e2e/cmd_config_volumes_test.go
Labels: lgtm, approved, size/L, cla: yes

#621 Revert "chore: use release-please fork for release branches (#609)"
  .github/workflows/ci.yaml
Labels: lgtm, approved, cla: yes, size/XS, kind/chore

#622 fix: Environment values -> Environment variables
  cmd/config.go
Labels: size/S, size/S, lgtm, approved, cla: yes

#623 fix: ConfigMap/Secret key validation
  cmd/config_envs.go
  config.go
  config_test.go
  utils/names.go
  utils/names_test.go
Labels: lgtm, approved, size/L, cla: yes

#625 chore: bump go version to 1.16 in ci build
  .github/workflows/ci.yaml
Labels: lgtm, approved, cla: yes, size/XS, kind/chore

#629 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, size/S, lgtm, approved, cla: yes

#632 Do not print header when `func list` does not find any functions
  cmd/list.go
Labels: lgtm, approved, cla: yes, size/XS

#628 fix: remove stray manifest.yaml files
  pkged.go
  templates/go/cloudevents/manifest.yaml
  templates/node/cloudevents/manifest.yaml
Labels: kind/bug, size/S, size/S, lgtm, approved, cla: yes

#639 MethodNotAllowed added for rust cloudevents template
  pkged.go
  templates/rust/cloudevents/src/main.rs
Labels: kind/enhancement, lgtm, approved, cla: yes, size/XS

#651 feat: function creation timestamp
  client.go
  client_test.go
  cmd/delete_test.go
  config.go
  function.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/M, cla: yes

#654 chore: build tag consistency
  cloudevents/emitter_test.go
  docker/credentials_helper_test.go
  docker/pusher_test.go
  knative/deployer_test.go
  repository_test.go
Labels: size/S, size/S, lgtm, approved, cla: yes

#648 feat: automatically start podman service
  .codecov.yaml
  buildpacks/builder.go
  docker/docker_client.go
  docker/docker_client_generated.go
  docker/docker_client_linux_test.go
  docker/docker_client_test.go
  docker/pusher.go
  docker/runner.go
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, cla: yes, size/XL

#652 chore: makefile-initiated golangci-lint to v1.43.0
  Makefile
Labels: lgtm, approved, cla: yes, size/XS

#656 chore: extract config validate
  config.go
Labels: lgtm, approved, size/L, cla: yes

#650 chore: remove redundant combined workflow
  .github/workflows/pull_requests.yaml
Labels: lgtm, approved, size/M, cla: yes, kind/chore

#655 chore: prefer slices over plural types
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_labels_test.go
  cmd/config_volumes.go
  cmd/root.go
  cmd/root_test.go
  config.go
  config_test.go
  function.go
  knative/deployer.go
  pkged.go
Labels: lgtm, approved, size/L, cla: yes

#653 chore: test helpers relocation
  client_int_test.go
  client_test.go
  function_test.go
  repositories_test.go
  templates_test.go
  testing/testing.go
Labels: lgtm, approved, size/L, cla: yes, kind/chore

#658 Refactor tests
  docker/docker_client_linux_test.go
  docker/docker_client_test.go
  docker/pusher_test.go
  testing/testing.go
Labels: lgtm, approved, size/L, cla: yes

#646 Initial support for buildEnvs in manifest.yaml
  repository.go
  repository_test.go
  template.go
  templates.go
  templates_test.go
  testdata/repositories/customLanguagePackRepo/manifest.yaml
  testdata/repositories/customLanguagePackRepo/templates/manifestedRuntime/manifest.yaml
  testdata/repositories/customLanguagePackRepo/templates/manifestedRuntime/manifestedTemplate/manifest.yaml
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#660 feat: add POD_NAME as an environment variable
  knative/deployer.go
  knative/deployer_test.go
Labels: kind/enhancement, lgtm, approved, size/M, cla: yes

#661 Revert "feat: add POD_NAME as an environment variable (#660)"
  knative/deployer.go
  knative/deployer_test.go
Labels: lgtm, approved, size/M, cla: yes

#649 feat: make SpringBoot template SpringNative by default
  templates/springboot/cloudevents/README.md
  templates/springboot/cloudevents/manifest.yaml
  templates/springboot/cloudevents/pom.xml
  templates/springboot/cloudevents/src/main/resources/application.properties
  templates/springboot/http/README.md
  templates/springboot/http/pom.xml
  templates/springboot/manifest.yaml
Labels: lgtm, approved, size/L, cla: yes

#663 chore: use buildEnvs instead of custom buildpack
  pkged.go
  templates/typescript/manifest.yaml
Labels: kind/techdebt, lgtm, approved, cla: yes, size/XS

#641 src: direct serialization of Function metadata as func.yaml
  client.go
  client_test.go
  cmd/build.go
  cmd/config.go
  cmd/config_envs.go
  cmd/config_volumes.go
  cmd/deploy.go
  cmd/run.go
  config.go
  config_test.go
  docs/guides/templates.md
  function.go
  function_envs.go
  function_envs_unit_test.go
  function_labels.go
  function_labels_unit_test.go
  function_options.go
  function_options_unit_test.go
  function_test.go
  function_unit_test.go
  function_volumes.go
  function_volumes_unit_test.go
  schema/func_yaml-schema.json
  schema/generator/main.go
Labels: lgtm, approved, size/XXL, cla: yes

#665 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#670 fix: use specific version of paketo builder
  pkged.go
  templates/node/manifest.yaml
Labels: lgtm, approved, cla: yes, size/XS

#669 fix: use default socket path for TCP connections
  docker/docker_client.go
  docker/docker_client_test.go
Labels: lgtm, approved, size/M, cla: yes

#672 Update getting_started_localhost.md
  docs/getting_started_localhost.md
Labels: lgtm, approved, cla: yes, size/XS

#561 chore: remove dead code
  buildpacks/builder.go
  buildpacks/utils.go
  pkged.go
  test/_e2e/cmd_config_envs_test.go
  test/_e2e/cmd_config_volumes_test.go
Labels: lgtm, approved, size/M, cla: yes, kind/chore

#647 making language runtime a required flag
  cmd/create.go
  cmd/create_test.go
  function_test.go
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#588 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/M, cla: yes

#666 [main] Format Go code
  pkged.go
Labels: lgtm, approved, cla: yes, size/XS

#664 feat: function version migrations
  client.go
  client_test.go
  function.go
  function_migrations.go
  function_migrations_unit_test.go
  function_test.go
  function_unit_test.go
  go.mod
  go.sum
  repository.go
  schema/func_yaml-schema.json
  templates.go
  testdata/migrations/README.md
  testdata/migrations/v0.19.0/func.yaml
  testing/testing.go
  third_party/VENDOR-LICENSE/github.com/coreos/go-semver/semver/LICENSE
  third_party/VENDOR-LICENSE/github.com/coreos/go-semver/semver/NOTICE
  vendor/github.com/coreos/go-semver/LICENSE
  vendor/github.com/coreos/go-semver/NOTICE
  vendor/github.com/coreos/go-semver/semver/semver.go
  vendor/github.com/coreos/go-semver/semver/sort.go
  vendor/modules.txt
Labels: kind/enhancement, lgtm, approved, size/XXL, cla: yes

#680 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, cla: yes, size/XS

#679 Clean up tests
  function_migrations_unit_test.go
  function_test.go
  function_volumes_unit_test.go
  repositories_test.go
  repository_test.go
  templates_test.go
Labels: lgtm, approved, size/L, cla: yes

#677 fix: schema-generate should point to `function.go`
  Makefile
Labels: lgtm, approved, cla: yes, size/XS

#683 feat: ensure config fs structure
  client.go
  client_test.go
  cmd/create.go
  cmd/repository.go
  cmd/root.go
  docker/pusher.go
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#687 chore: revert using a fork of boson-project/test-templates
  test/_e2e/cmd_config_envs_test.go
  test/_e2e/cmd_config_volumes_test.go
Labels: lgtm, approved, cla: yes, size/XS, kind/chore
