Repository knative/func, pull requests merged in 2021-06, with the labels that each got.

#365 chore(builders): add explicit version numbers for builder images
  pkged.go
  templates/go/events/.builders.yaml
  templates/go/http/.builders.yaml
  templates/node/events/.builders.yaml
  templates/node/http/.builders.yaml
  templates/python/events/.builders.yaml
  templates/python/http/.builders.yaml
  templates/quarkus/events/.builders.yaml
  templates/quarkus/http/.builders.yaml
  templates/springboot/events/.builders.yaml
  templates/springboot/http/.builders.yaml
  templates/typescript/events/.builders.yaml
  templates/typescript/http/.builders.yaml
Labels: source/configuration

#369 feat: reference Secrets in `envs` and `volumes` sections in config
  cmd/delete_test.go
  cmd/deploy.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  config.go
  config_test.go
  docker/runner.go
  docs/guides/func_yaml.md
  function.go
  knative/client.go
  knative/deployer.go
  knative/deployer_test.go
Labels: source/configuration, type/enhancement

#371 feat: reference ConfigMaps in `envs` and `volumes` sections in config
  config.go
  config_test.go
  docs/guides/func_yaml.md
  knative/deployer.go
Labels: source/configuration, type/enhancement

#407 chore(CI): use container-tools/kind for integration tests
  .github/workflows/pull_requests.yaml
Labels: project/chore
