Repository knative/func, pull requests merged in 2021-12, with the labels that each got.

#689 chore: remove release-please from ci
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/M, cla: yes, kind/chore

#690 fix: make registry validation work again
  cmd/build.go
  cmd/build_test.go
Labels: kind/bug, lgtm, approved, size/M, cla: yes

#697 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#698 docs: `podman`: known issue + macOS doc
  docs/guides/podman.md
Labels: lgtm, approved, size/M, cla: yes

#681 feat: add flag to push image at the end of a successful build
  client.go
  cmd/build.go
  cmd/build_test.go
  cmd/root.go
Labels: lgtm, approved, size/L, cla: yes

#686 refactor: config path accessors with instantiation cleanup
  client.go
  client_int_test.go
  cmd/create.go
  docker/pusher.go
  repositories.go
Labels: kind/techdebt, lgtm, approved, size/L, cla: yes

#699 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#702 chore: refactor CLI flags for consistency across commands
  cmd/build.go
  cmd/config.go
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_volumes.go
  cmd/delete.go
  cmd/deploy.go
  cmd/emit.go
  cmd/info.go
  cmd/list.go
  cmd/root.go
  cmd/run.go
Labels: lgtm, approved, size/M, cla: yes, kind/chore

#688 feat: In cluster dialer to proxy TCP connections to unexposed services
  go.sum
  k8s/dialer.go
  k8s/dialer_test.go
  third_party/VENDOR-LICENSE/github.com/moby/spdystream/LICENSE
  third_party/VENDOR-LICENSE/github.com/moby/spdystream/NOTICE
  vendor/github.com/moby/spdystream/CONTRIBUTING.md
  vendor/github.com/moby/spdystream/LICENSE
  vendor/github.com/moby/spdystream/MAINTAINERS
  vendor/github.com/moby/spdystream/NOTICE
  vendor/github.com/moby/spdystream/README.md
  vendor/github.com/moby/spdystream/connection.go
  vendor/github.com/moby/spdystream/go.mod
  vendor/github.com/moby/spdystream/go.sum
  vendor/github.com/moby/spdystream/handlers.go
  vendor/github.com/moby/spdystream/priority.go
  vendor/github.com/moby/spdystream/spdy/dictionary.go
  vendor/github.com/moby/spdystream/spdy/read.go
  vendor/github.com/moby/spdystream/spdy/types.go
  vendor/github.com/moby/spdystream/spdy/write.go
  vendor/github.com/moby/spdystream/stream.go
  vendor/github.com/moby/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, cla: yes

#701 fix: move integration port to unregistered range
  client_int_test.go
  docs/DEVELOPMENT.md
  function_unit_test.go
  hack/allocate.sh
  hack/registry.sh
  hack/test-integration-podman.sh
  test/_e2e/config.go
  test/_e2e/main_test.go
  testdata/cluster.yaml
  testdata/repositories/customTemplateRepo/README.md
Labels: kind/bug, lgtm, approved, size/M, cla: yes

#712 fix: revert hostname alias
  client_int_test.go
  hack/allocate.sh
  hack/test-integration-podman.sh
  test/_e2e/config.go
  test/_e2e/main_test.go
Labels: size/S, size/S, lgtm, approved

#707 Refactor credential provider
  cmd/build.go
  cmd/deploy.go
  docker/credentials_helper.go
  docker/pusher.go
  docker/pusher_test.go
Labels: lgtm, approved, size/L

#713 Fix dialer test
  k8s/dialer_test.go
Labels: size/S, size/S, lgtm, approved

#711 feat: custom default HTTP transport
  cmd/func/main.go
  http/transport.go
  k8s/dialer.go
Labels: lgtm, approved, size/L, do-not-merge/hold

#716 src: revert global dialer
  cloudevents/emitter.go
  cmd/emit.go
  cmd/func/main.go
Labels: lgtm, approved, size/M

#644 feat: allow build to be triggered from run when fn.Image is missing
  cmd/run.go
  cmd/run_test.go
  docker/runner.go
  docker/runner_test.go
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#719 feat: add telemetry to Node.js and TypeScript function templates
  Makefile
  pkged.go
  templates/go/cloudevents/go.sum
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/cloudevents/src/index.ts
  templates/typescript/cloudevents/test/unit.ts
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
Labels: kind/enhancement, lgtm, approved, size/XXL

#724 [main] Format Go code
  pkged.go
Labels: lgtm, approved, size/XS

#723 mitigate log4j dependency vulnerability
  pkged.go
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
Labels: lgtm, approved, size/XS

#726 fix: ensure pkged.go is migrated
  hack/update-pkger.sh
Labels: lgtm, approved, size/XS

#727 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, size/S, lgtm, approved

#717 feat!: use `function.knative.dev` for Functions related labels
  knative/deployer.go
  knative/lister.go
Labels: lgtm, approved, size/M

#718 feat: allow push to cluster internal registries
  cmd/build.go
  cmd/deploy.go
  docker/credentials_helper.go
  docker/credentials_helper_test.go
  docker/creds/credentials.go
  docker/creds/credentials_test.go
  docker/pusher.go
  docker/pusher_test.go
  docker/testData/image.tar
  http/transport.go
  vendor/github.com/google/go-containerregistry/internal/httptest/httptest.go
  vendor/github.com/google/go-containerregistry/pkg/registry/blobs.go
  vendor/github.com/google/go-containerregistry/pkg/registry/error.go
  vendor/github.com/google/go-containerregistry/pkg/registry/manifest.go
  vendor/github.com/google/go-containerregistry/pkg/registry/registry.go
  vendor/github.com/google/go-containerregistry/pkg/registry/tls.go
  vendor/github.com/google/go-containerregistry/pkg/v1/daemon/README.md
  vendor/github.com/google/go-containerregistry/pkg/v1/daemon/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/daemon/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/daemon/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/daemon/write.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#667 chore: release 0.20.0
  CHANGELOG.md
  version.txt
Labels: lgtm, approved, size/M, cla: yes

#731 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS
