Repository knative/func, pull requests merged in 2021-09, with the labels that each got.

#502 chore: update buildpack image URI for Go and typescript
  pkged.go
  templates/go/events/manifest.yaml
  templates/go/http/manifest.yaml
  templates/typescript/events/manifest.yaml
  templates/typescript/http/manifest.yaml
Labels: size/S, size/S, lgtm, approved, cla: yes

#503 chore: fix typo in `build` help message
  cmd/build.go
Labels: lgtm, approved, cla: yes, size/XS

#505 test: adding e2e test for remote repository
  test/_e2e/cmd_build_test.go
  test/_e2e/cmd_deploy_test.go
  test/_e2e/config.go
  test/_e2e/e2e_remote_repository_test.go
  test/_e2e/func_test_proj.go
Labels: lgtm, approved, size/M, cla: yes

#508 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/L, cla: yes

#515 remove superfluous headers from go template
  pkged.go
  templates/go/http/handle.go
Labels: templates/go, lgtm, approved, cla: yes, size/XS

#507 chore: example message changes between standalone and plugin
  cmd/root.go
  cmd/root_test.go
  plugin/plugin.go
Labels: kind/enhancement, lgtm, approved, size/M, cla: yes

#509 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, cla: yes, size/XL

#510 fix: `build` should honor registry specified in `-r`
  function.go
Labels: lgtm, approved, cla: yes, size/XS

#516 ci: avert tar error in lint action
  .github/workflows/knative-style.yaml
Labels: kind/bug, lgtm, approved, cla: yes, size/XS

#514 feat: repository management cli
  client.go
  cmd/config_envs.go
  cmd/create.go
  cmd/delete_test.go
  cmd/repository.go
  cmd/repository_test.go
  cmd/root.go
  cmd/testdata/repository.git/HEAD
  cmd/testdata/repository.git/config
  cmd/testdata/repository.git/description
  cmd/testdata/repository.git/hooks/.gitinclude
  cmd/testdata/repository.git/info/exclude
  cmd/testdata/repository.git/info/refs
  cmd/testdata/repository.git/objects/00/9641334a89d30963a68442a132e5f8ef389ba8
  cmd/testdata/repository.git/objects/25/128199189ce87956e5e41fa8113bbf5cb6c39a
  cmd/testdata/repository.git/objects/27/d75d0e58009a59e1ff8a52a3297e1e0574138b
  cmd/testdata/repository.git/objects/43/0739f6d9930f74a6aef1a410f0f0727d171cef
  cmd/testdata/repository.git/objects/67/00ea8078422674e91189c1b513d1ab0696b150
  cmd/testdata/repository.git/objects/6f/6a77b977041c978dbdd431f9e7b2952c6908a3
  cmd/testdata/repository.git/objects/8b/57110b1cc8f2019ca4b2ed51a450ee0873eaaf
  cmd/testdata/repository.git/objects/98/68959b2b456ac7767bf351a84b369f9fbadb3a
  cmd/testdata/repository.git/objects/9a/c29c7ad8c06fa6613b794521568fbd7ea007dd
  cmd/testdata/repository.git/objects/b2/7e306a552e80fcae0bfa959bd6e8652de70c69
  cmd/testdata/repository.git/objects/b7/5832d0a4a4bb0409cca573b2c97b017d088f90
  cmd/testdata/repository.git/objects/c7/e84596af04680b8e7a39b9a527f19ccd75f287
  cmd/testdata/repository.git/objects/ca/1a6296f97eced6c9497d05598ef508852cac5d
  cmd/testdata/repository.git/objects/ca/5019f945b1d769d042c5f87d39f5d7a15f290c
  cmd/testdata/repository.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
  cmd/testdata/repository.git/objects/f3/a9c97a29b561e7d72668581ea82284de2f1ca0
  cmd/testdata/repository.git/objects/info/packs
  cmd/testdata/repository.git/packed-refs
  cmd/testdata/repository.git/refs/heads/main
  cmd/testdata/repository.git/refs/tags/.gitinclude
  docker/runner_test.go
  docs/guides/commands.md
  docs/guides/templates.md
  mock/client.go
  pkged.go
  repositories.go
  repositories_test.go
  repository.go
  repository_test.go
  templates/go/events/README.md
  templates_test.go
  utils/names.go
Labels: kind/enhancement, lgtm, approved, size/XXL, cla: yes

#490 feat: client effective runtimes list
  client.go
  client_test.go
  repositories.go
  repositories_test.go
Labels: kind/enhancement, lgtm, approved, size/M, cla: yes

#519 chore: properly access repositories
  client.go
Labels: lgtm, approved, cla: yes, size/XS

#518 test: add test for DerivedImage
  function_test.go
Labels: lgtm, approved, size/L, cla: yes

#521 Update Knative dependencies to v0.24
  go.mod
  go.sum
Labels: lgtm, approved, cla: yes, size/XL

#525 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, cla: yes, size/XS

#524 fix: prompt default options
  cmd/repository.go
  repositories.go
Labels: kind/bug, size/S, size/S, lgtm, approved, cla: yes

#533 Revert linting action to the canonical version
  .github/workflows/knative-style.yaml
  .golangci.yaml
Labels: lgtm, approved, cla: yes, size/XS

#526 Better credentials handling
  cmd/deploy.go
  docker/credentials_helper.go
  docker/pusher.go
  docker/pusher_test.go
Labels: lgtm, approved, size/L, cla: yes

#530 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, size/S, lgtm, approved, cla: yes

#535 fix: use full image names
  pkged.go
  templates/go/events/manifest.yaml
  templates/go/http/manifest.yaml
  templates/node/events/manifest.yaml
  templates/node/http/manifest.yaml
  templates/typescript/events/manifest.yaml
  templates/typescript/http/manifest.yaml
Labels: lgtm, approved, size/M, cla: yes

#517 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, size/S, lgtm, approved, cla: yes

#539 Update installing_cli.md
  docs/installing_cli.md
Labels: lgtm, approved, cla: yes, size/XS

#538 fix: hide a fmt.Println behind verbose flag
  knative/deployer.go
Labels: lgtm, approved, cla: yes, size/XS

#537 feat: periodically update progress during build
  client.go
Labels: kind/enhancement, size/S, size/S, lgtm, approved, cla: yes

#541 fix: update-pkger.sh sed error on osX
  hack/update-pkger.sh
Labels: kind/bug, size/S, size/S, lgtm, approved, cla: yes

#543 Add serveraddress to auth header of docker API
  docker/pusher.go
Labels: lgtm, approved, cla: yes, size/XS

#544 fix: stop the progress ticker after build completes
  client.go
Labels: size/S, size/S, lgtm, approved, cla: yes

#548 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/S, size/S, lgtm, approved, cla: yes

#547 feat: create cli
  buildpacks/utils.go
  client.go
  client_test.go
  cmd/completion_util.go
  cmd/create.go
  cmd/create_test.go
  cmd/repository.go
  cmd/repository_test.go
  cmd/root.go
  pkged.go
  repositories.go
  repositories_test.go
  templates.go
  templates/test/http/rtAtplDefault.txt
  templates/test/tpla/rtAtplA.txt
  templates/test/tplb/executable.sh
  templates/test/tplb/rtAtplB.txt
  templates_test.go
  test/_e2e/cmd_create_test.go
  test/_e2e/e2e_remote_repository_test.go
Labels: kind/enhancement, lgtm, approved, cla: yes, size/XL

#554 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, size/S, lgtm, approved, cla: yes

#549 fix: registry URL comparison
  docker/credentials_helper.go
  docker/credentials_helper_test.go
Labels: lgtm, approved, size/M, cla: yes

#551 avoid unintentional image/registry overwrite
  cmd/build.go
Labels: lgtm, approved, cla: yes, size/XS

#557 Update Quarkus version in templates
  .github/workflows/ci.yaml
  .github/workflows/pull_requests.yaml
  pkged.go
  templates/quarkus/events/pom.xml
  templates/quarkus/http/pom.xml
Labels: size/S, size/S, lgtm, approved, cla: yes
