Repository knative/func, pull requests merged in 2021-08, with the labels that each got.

#436 feat: Add proper example of configuring Rust functions.
  go.sum
  pkged.go
  templates/rust/events/src/config.rs
  templates/rust/events/src/handler.rs
  templates/rust/http/src/config.rs
  templates/rust/http/src/handler.rs
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#455 doc: status badges
  README.md
Labels: approved, cla: yes, lgtm, size/S, size/S

#456 build: remove pkged.go from make clean
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#447 chore: add some collaborators to the OWNERS file
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#373 feat: add support for labels in func.yaml
  cmd/config.go
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/delete_test.go
  cmd/root.go
  cmd/root_test.go
  config.go
  config_test.go
  docs/guides/func_yaml.md
  function.go
  knative/deployer.go
  pkged.go
  utils/names.go
  utils/names_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XXL, source/lib

#437 feat: remote template repositories
  client.go
  cmd/create.go
  docs/guides/commands.md
  docs/guides/language-packs.md
  docs/guides/templates.md
  go.mod
  go.sum
  templates.go
  templates_test.go
  testdata/README.md
  testdata/repository.git/HEAD
  testdata/repository.git/config
  testdata/repository.git/description
  testdata/repository.git/hooks/post-update
  testdata/repository.git/info/exclude
  testdata/repository.git/info/refs
  testdata/repository.git/objects/25/128199189ce87956e5e41fa8113bbf5cb6c39a
  testdata/repository.git/objects/43/0739f6d9930f74a6aef1a410f0f0727d171cef
  testdata/repository.git/objects/67/00ea8078422674e91189c1b513d1ab0696b150
  testdata/repository.git/objects/8b/57110b1cc8f2019ca4b2ed51a450ee0873eaaf
  testdata/repository.git/objects/98/68959b2b456ac7767bf351a84b369f9fbadb3a
  testdata/repository.git/objects/9a/c29c7ad8c06fa6613b794521568fbd7ea007dd
  testdata/repository.git/objects/b7/5832d0a4a4bb0409cca573b2c97b017d088f90
  testdata/repository.git/objects/c7/e84596af04680b8e7a39b9a527f19ccd75f287
  testdata/repository.git/objects/ca/1a6296f97eced6c9497d05598ef508852cac5d
  testdata/repository.git/objects/ca/5019f945b1d769d042c5f87d39f5d7a15f290c
  testdata/repository.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
  testdata/repository.git/objects/info/packs
  testdata/repository.git/packed-refs
  testdata/repository.git/refs/heads/.gitinclude
  testdata/repository.git/refs/heads/main
  testdata/repository.git/refs/tags/.gitinclude
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XL

#459 fix: use ascii chars in progress indicator on win
  progress/progress.go
Labels: lgtm, approved, cla: yes, size/XS

#458 fix: hide progress indicator if asking for creds
  client.go
  cmd/deploy.go
  docker/pusher.go
Labels: lgtm, approved, size/M, cla: yes

#460 feat: generate json schema for func.yaml
  .github/workflows/ci.yaml
  .github/workflows/pull_requests.yaml
  Makefile
  config.go
  go.mod
  go.sum
  schema/func_yaml-schema.json
  schema/generator/main.go
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#470 chore: use mirror for lifecycle image
  buildpacks/builder.go
Labels: size/S, size/S, lgtm, approved, cla: yes

#468 feat: make func schema if config updated
  Makefile
Labels: kind/enhancement, size/S, size/S, lgtm, approved, cla: yes

#467 feat: repository management client api
  client.go
  repositories.go
  repositories_test.go
  testdata/README.md
  testdata/repository-a.git/HEAD
  testdata/repository-a.git/config
  testdata/repository-a.git/description
  testdata/repository-a.git/hooks/.gitinclude
  testdata/repository-a.git/info/exclude
  testdata/repository-a.git/objects/32/bad9e3775e80ae9b7483acf6d7630bf8b945e9
  testdata/repository-a.git/objects/91/f1295d025a69a8ae87296ea5fda680672275d9
  testdata/repository-a.git/objects/ef/1e6c8ed28e25dec915e8cd7479dacf671665ed
  testdata/repository-a.git/objects/info/.gitinclude
  testdata/repository-a.git/objects/pack/.gitinclude
  testdata/repository-a.git/packed-refs
  testdata/repository-a.git/refs/heads/.gitinclude
  testdata/repository-a.git/refs/tags/.gitinclude
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#462 docs: add section about Node.js log levels
  docs/guides/nodejs.md
Labels: project/documentation, size/S, size/S, lgtm, approved, cla: yes

#472 feat!: use key&value for Labels
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/root.go
  cmd/root_test.go
  config.go
  config_test.go
  docs/guides/func_yaml.md
  function.go
  knative/deployer.go
  schema/func_yaml-schema.json
  utils/names.go
  utils/names_test.go
Labels: lgtm, approved, cla: yes, size/XL

#464 Support nested image paths
  docker/pusher.go
  docker/pusher_test.go
Labels: kind/bug, lgtm, approved, size/M, cla: yes

#477 fix: enable healt checks for Quarkus
  knative/deployer.go
  pkged.go
  templates/quarkus/events/pom.xml
  templates/quarkus/events/src/main/resources/application.properties
  templates/quarkus/http/pom.xml
  templates/quarkus/http/src/main/resources/application.properties
Labels: size/S, size/S, lgtm, approved, cla: yes

#457 Tests config labels
  Makefile
  cmd/config.go
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_labels_test.go
  cmd/config_volumes.go
  go.mod
  go.sum
Labels: lgtm, approved, size/L, cla: yes

#478 fix: regenerate pkged.go
  pkged.go
Labels: lgtm, approved, cla: yes, size/XS

#479 fix: better cleanup before pkger run
  Makefile
Labels: lgtm, approved, cla: yes, size/XS

#476 chore: ignore IDE files
  .gitignore
Labels: lgtm, approved, cla: yes, size/XS

#474 feat!: change `describe` command to `info`
  client.go
  cmd/emit.go
  cmd/info.go
  docs/guides/commands.md
  knative/describer.go
  test/_e2e/cmd_describe_test.go
  test/_e2e/e2e_functions_test.go
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#473 src: template tests use public api
  client_test.go
  function.go
  repositories.go
  templates_test.go
Labels: kind/techdebt, lgtm, approved, size/L, cla: yes

#480 docs: change `describe` command to `info`
  docs/guides/developers_tutorial.md
  docs/guides/golang.md
  docs/guides/nodejs.md
  docs/guides/python.md
  docs/guides/quarkus.md
  docs/guides/typescript.md
  pkged.go
  templates/quarkus/events/README.md
  templates/quarkus/http/README.md
  templates/rust/events/README.md
  templates/rust/http/README.md
  templates/springboot/events/README.md
  templates/springboot/http/README.md
Labels: lgtm, approved, size/M, cla: yes

#482 fix: support nested subdirs in remote templates
  templates.go
Labels: kind/bug, size/S, size/S, lgtm, approved, cla: yes

#481 Using systemctl to manage podman user owned service
  docs/guides/podman.md
Labels: lgtm, approved, cla: yes, size/XS

#483 Remote file modes unit test
  templates_test.go
  testdata/repository.git/info/refs
  testdata/repository.git/objects/00/9641334a89d30963a68442a132e5f8ef389ba8
  testdata/repository.git/objects/27/d75d0e58009a59e1ff8a52a3297e1e0574138b
  testdata/repository.git/objects/6f/6a77b977041c978dbdd431f9e7b2952c6908a3
  testdata/repository.git/objects/b2/7e306a552e80fcae0bfa959bd6e8652de70c69
  testdata/repository.git/objects/f3/a9c97a29b561e7d72668581ea82284de2f1ca0
  testdata/repository.git/refs/heads/main
Labels: lgtm, approved, size/M, cla: yes

#484 Remote file modes integration test
  client_int_test.go
  templates.go
Labels: kind/enhancement, lgtm, approved, size/M, cla: yes

#487 style: create command output formatting for repository option
  cmd/create.go
Labels: lgtm, approved, cla: yes, size/XS

#486 doc: fix create command help message description
  cmd/create.go
Labels: lgtm, approved, cla: yes, size/XS

#465 feat: introduce manifest.yaml for language pack providers
  buildpacks/builder.go
  client.go
  config.go
  function.go
  knative/deployer.go
  knative/deployer_test.go
  pkged.go
  schema/func_yaml-schema.json
  templates/go/events/.builders.yaml
  templates/go/events/manifest.yaml
  templates/go/http/.builders.yaml
  templates/go/http/manifest.yaml
  templates/node/events/.builders.yaml
  templates/node/events/manifest.yaml
  templates/node/http/.builders.yaml
  templates/node/http/manifest.yaml
  templates/python/events/.builders.yaml
  templates/python/events/manifest.yaml
  templates/python/http/.builders.yaml
  templates/python/http/manifest.yaml
  templates/quarkus/events/.builders.yaml
  templates/quarkus/events/manifest.yaml
  templates/quarkus/http/.builders.yaml
  templates/quarkus/http/manifest.yaml
  templates/rust/events/.builders.yaml
  templates/rust/events/manifest.yaml
  templates/rust/http/.builders.yaml
  templates/rust/http/manifest.yaml
  templates/springboot/events/.builders.yaml
  templates/springboot/events/manifest.yaml
  templates/springboot/http/.builders.yaml
  templates/springboot/http/manifest.yaml
  templates/typescript/events/.builders.yaml
  templates/typescript/events/manifest.yaml
  templates/typescript/http/.builders.yaml
  templates/typescript/http/manifest.yaml
Labels: lgtm, approved, size/L, cla: yes

#491 add meeting time to README
  README.md
Labels: lgtm, approved, cla: yes, size/XS

#489 Add Omer to OWNERS
  OWNERS
Labels: lgtm, approved, cla: yes, size/XS

#485 feat!: move built in templates for Go, Node.js and TypeScript to Paketo builders
  buildpacks/builder.go
  client.go
  cmd/completion_util.go
  cmd/delete_test.go
  config.go
  docs/guides/func_yaml.md
  function.go
  knative/deployer.go
  knative/deployer_test.go
  pkged.go
  schema/func_yaml-schema.json
  templates/go/events/manifest.yaml
  templates/go/http/manifest.yaml
  templates/node/events/manifest.yaml
  templates/node/events/package-lock.json
  templates/node/events/package.json
  templates/node/http/manifest.yaml
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/python/events/manifest.yaml
  templates/python/http/manifest.yaml
  templates/rust/events/manifest.yaml
  templates/rust/http/manifest.yaml
  templates/springboot/events/manifest.yaml
  templates/springboot/http/manifest.yaml
  templates/typescript/events/manifest.yaml
  templates/typescript/events/package-lock.json
  templates/typescript/events/package.json
  templates/typescript/http/manifest.yaml
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
  test/_e2e/update_templates/node/events/package-lock.json
  test/_e2e/update_templates/node/events/package.json
  test/_e2e/update_templates/node/http/package-lock.json
  test/_e2e/update_templates/node/http/package.json
  test/_e2e/update_templates/typescript/http/package-lock.json
  test/_e2e/update_templates/typescript/http/package.json
Labels: kind/enhancement, lgtm, approved, size/XXL, cla: yes

#475 feat: repository and templates client api
  Makefile
  client.go
  client_test.go
  repositories.go
  repositories_test.go
  repository.go
  repository_test.go
  templates.go
  templates_test.go
  testdata/repositories/customProvider/customRuntime/.gitinclude
  testdata/repositories/customProvider/customRuntime/customTemplate/custom.impl
  testdata/repositories/customProvider/go/customTemplate/custom.go
  testdata/repositories/repositoryTests/go/custom/custom.go
  testdata/repositories/repositoryTests/node/custom/custom.js
Labels: kind/enhancement, lgtm, approved, cla: yes, size/XL

#493 fix: `config labels` panic
  cmd/config_labels.go
Labels: lgtm, approved, cla: yes, size/XS

#495 feat: builders/buildpacks configured in client
  client.go
  client_test.go
Labels: kind/enhancement, lgtm, approved, size/L, cla: yes

#500 chore: minor fix in the help doc
  cmd/deploy.go
Labels: lgtm, approved, cla: yes, size/XS

#498 fix: control chars on progress listener for Windows OS
  client.go
  progress/progress.go
Labels: size/S, size/S, lgtm, approved, cla: yes, kind/chore
