Repository knative/func, pull requests merged in 2021-07, with the labels that each got.

#413 chore: add AUTHORS and OWNERS files
  AUTHORS
  OWNERS
Labels: project/chore

#419 ci: move to inbuilt provider scripts for local and ci clusters
  .github/workflows/pull_requests.yaml
  go.mod
  go.sum
  hack/allocate.sh
  hack/binaries.sh
  hack/ci.sh
  hack/configure.sh
  hack/delete.sh
  hack/test.sh
  knative/client.go
  knative/describer.go
Labels: approved, cla: yes, lgtm, size/XXL

#421 Update builders version
  buildpacks/builder.go
  pkged.go
  templates/go/events/.builders.yaml
  templates/go/http/.builders.yaml
  templates/node/events/.builders.yaml
  templates/node/http/.builders.yaml
  templates/python/events/.builders.yaml
  templates/python/http/.builders.yaml
  templates/quarkus/events/.builders.yaml
  templates/quarkus/http/.builders.yaml
  templates/rust/events/.builders.yaml
  templates/rust/http/.builders.yaml
  templates/springboot/events/.builders.yaml
  templates/springboot/http/.builders.yaml
  templates/typescript/events/.builders.yaml
  templates/typescript/http/.builders.yaml
Labels: approved, cla: yes, lgtm, size/M

#423 Rename module to knative.dev/kn-plugin-func
  buildpacks/builder.go
  client_int_test.go
  client_test.go
  cmd/build.go
  cmd/completion_util.go
  cmd/config.go
  cmd/config_envs.go
  cmd/config_volumes.go
  cmd/create.go
  cmd/create_test.go
  cmd/delete.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/describe.go
  cmd/emit.go
  cmd/func/main.go
  cmd/list.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  config.go
  docker/pusher.go
  docker/runner.go
  docker/runner_test.go
  go.mod
  knative/client.go
  knative/deployer.go
  knative/describer.go
  knative/lister.go
  knative/remover.go
  mock/builder.go
  mock/deployer.go
  mock/lister.go
  mock/pusher.go
  mock/runner.go
  plugin/plugin.go
Labels: approved, cla: yes, lgtm, size/L

#422 CI run integration test against podman
  .github/workflows/pull_requests.yaml
  hack/test-integration-podman.sh
Labels: approved, cla: yes, lgtm, size/M

#428 src: Makefile developer accessibility
  .github/workflows/ci.yaml
  .github/workflows/pull_requests.yaml
  Makefile
  hack/allocate.sh
  hack/registry.sh
Labels: approved, cla: yes, lgtm, size/L

#429 ci: Added minimal e2e test support for typescript runtime
  test/_e2e/trigger_http_test.go
  test/_e2e/update_templates/typescript/http/package-lock.json
  test/_e2e/update_templates/typescript/http/package.json
  test/_e2e/update_templates/typescript/http/src/index.ts
  test/_e2e/update_templates/typescript/http/tsconfig.json
Labels: cla: yes, size/XXL

#431 test: confirm config search path
  cmd/create_test.go
  cmd/root.go
Labels: approved, cla: yes, lgtm, size/M

#432 doc: DEVELOPMENT.md
  README.md
  docs/DEVELOPMENT.md
  docs/README.md
Labels: approved, cla: yes, lgtm, size/M

#430 feat: Configure Rust functions
  docs/guides/rust.md
  pkged.go
  templates/rust/events/README.md
  templates/rust/events/src/config.rs
  templates/rust/events/src/main.rs
  templates/rust/http/README.md
  templates/rust/http/src/config.rs
  templates/rust/http/src/main.rs
Labels: approved, cla: yes, lgtm, size/M

#433 Bump node dependencies
  pkged.go
  templates/node/events/package-lock.json
  templates/node/http/package-lock.json
  templates/typescript/events/package-lock.json
  templates/typescript/http/package-lock.json
  test/_e2e/update_templates/node/events/package-lock.json
  test/_e2e/update_templates/node/http/package-lock.json
Labels: approved, cla: yes, lgtm, size/XXL

#434 Bump cloudevents dep to 4.0.3
  pkged.go
  templates/node/events/package-lock.json
  templates/node/events/package.json
  test/_e2e/update_templates/node/events/package-lock.json
  test/_e2e/update_templates/node/events/package.json
  test/_e2e/update_templates/typescript/http/package-lock.json
Labels: approved, cla: yes, lgtm, size/XXL

#424 Change github.com links to the new home
  .chglog/config.yml
  CHANGELOG.md
  README.md
  docs/getting_started_kubernetes.md
  docs/guides/developers_tutorial.md
  docs/installing_cli.md
  templates/go/events/README.md
  templates/go/http/README.md
Labels: approved, cla: yes, lgtm, size/L

#438 fix: fix unit tests for Node.js event templates
  pkged.go
  templates/node/events/package-lock.json
  templates/node/events/test/unit.js
  templates/node/http/package-lock.json
Labels: approved, cla: yes, kind/bug, lgtm, size/XXL

#439 chore(ci): fix main CI reference to downloaded pkger
  .github/workflows/ci.yaml
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#443 src: match client v0.23.2 deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XL

#444 feat: print emit response output if it's a cloudevent
  cloudevents/emitter.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#450 chore: removes deprecated CODEOWNERS file
  CODEOWNERS
Labels: approved, cla: yes, kind/chore, lgtm, size/XS

#449 fix: pkger runs only when necessary
  Makefile
  client.go
  pkged.go
Labels: approved, cla: yes, kind/bug, lgtm, size/M
