Repository knative/func, pull requests merged in 2022-10, with the labels that each got.

#1286 feat: ksvc log on deploy
  go.mod
  knative/deployer.go
  knative/logs.go
Labels: kind/enhancement, lgtm, approved, size/L

#1289 chore: cmd test cleanup
  cmd/build_test.go
  cmd/config_test.go
  cmd/create_test.go
  cmd/delete_test.go
  cmd/deploy_test.go
  cmd/invoke_test.go
  cmd/languages_test.go
  cmd/repository_test.go
  cmd/root_test.go
  cmd/run_test.go
  cmd/templates_test.go
  repositories_test.go
  templates_test.go
  testing/testing.go
Labels: lgtm, approved, size/L, kind/cleanup

#1299 fix: missing close of manifests
  repository.go
Labels: lgtm, approved, size/XS

#1296 Fix a typo in Quarkus template README.md
  templates/quarkus/http/README.md
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1301 chore: update docs README.md
  docs/README.md
Labels: lgtm, approved, size/XS, kind/chore

#1307 chore: add coverage for integration tests
  .github/workflows/test-integration.yaml
  .github/workflows/test-unit.yaml
  .gitignore
  Makefile
Labels: size/S, lgtm, approved, kind/chore

#1306 chore: update release script to use knative org
  hack/release.sh
Labels: lgtm, approved, size/XS, kind/chore

#1315 chore: use t.Cleanup() more
  docker/creds/credentials_test.go
  docker/docker_client_pm_test.go
  docker/docker_client_ssh_test.go
  docker/docker_client_test.go
  docker/docker_client_windows_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#1312 Func unit testing first approach
  buildpacks/builder_test.go
  test/README.md
Labels: lgtm, approved, size/M, kind/chore

#1252 chore: change Makefile for multiple tags at HEAD
  Makefile
  docs/RELEASING.md
  version.txt
Labels: lgtm, approved, size/M, kind/chore

#1314 chore: add unit test cases for instances
  instances.go
  instances_test.go
Labels: lgtm, approved, size/L, kind/chore

#1319 chore: update CI to run unit+integration on main
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/M, kind/chore

#1324 chore: fix ci.yaml
  .github/workflows/ci.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1327 chore: more changes to CI workflow
  .github/workflows/ci.yaml
Labels: size/S, lgtm, approved

#1331 test: test for docker runner
  cmd/client.go
  docker/runner.go
  docker/runner_int_test.go
  docker/runner_test.go
Labels: lgtm, approved, size/L

#1332 chore: update codecov config
  .codecov.yaml
Labels: lgtm, approved, size/XS

#1335 chore: fix codecov.yaml
  .codecov.yaml
Labels: lgtm, approved, size/XS

#1334 test: appease coverage gods
  docker/appease_coverage_gods_test.go
Labels: lgtm, approved, size/M

#1330 test: added test for get pod's logs
  k8s/logs_test.go
Labels: lgtm, approved, size/M

#1328 chore: bump node and golang actions to latest
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/update-quarkus-platform.yaml
Labels: lgtm, approved, size/M, kind/chore

#1336 cleanup: removed unused functions
  k8s/role_bidings.go
  k8s/service_accounts.go
Labels: lgtm, approved, size/M

#1329 feat: cancel pipeline run on SIGINT/SIGTERM
  pipelines/tekton/pipeplines_provider.go
Labels: kind/enhancement, lgtm, approved, size/M

#1337 chore: add link to the roadmap in the Readme
  README.md
Labels: lgtm, approved, size/XS

#1338 test: initial integration test for knative related functionality
  knative/integration_test.go
Labels: lgtm, approved, size/L, kind/chore

#1340 chore: update image tag in tekton pipeline
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: lgtm, approved, size/XS, kind/chore

#1343 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1345 fix: use proper temp dir for funs in e2e tests
  test/_e2e/e2e_functions_test.go
  test/_e2e/func_test_proj.go
  test/_e2e/update_test.go
Labels: size/S, lgtm, approved, kind/cleanup

#1346 fix: use proper tmp dir for oncluster e2e tests
  test/_oncluster/scenario_basic_test.go
  test/_oncluster/scenario_context-dir_test.go
  test/_oncluster/scenario_from-cli-local_test.go
  test/_oncluster/scenario_from-cli_test.go
  test/_oncluster/scenario_revision_test.go
  test/_oncluster/scenario_runtime_test.go
Labels: size/S, lgtm, approved, kind/cleanup

#1347 fix: Quarkus version update action
  .github/workflows/update-quarkus-platform.yaml
Labels: lgtm, approved, size/XS

#1298 On cluster build without VCS
  cmd/deploy.go
  cmd/deploy_test.go
  go.mod
  k8s/dialer.go
  k8s/persistent_volumes.go
  k8s/persistent_volumes_test.go
  k8s/security_context.go
  k8s/testData/content.tar
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/pipeplines_provider_test.go
  pipelines/tekton/resources.go
  pipelines/tekton/tasks.go
  pipelines/tekton/testData/fn-src/.gitignore
  pipelines/tekton/testData/fn-src/bin/release/a.out
  pipelines/tekton/testData/fn-src/hello.txt
  test/_oncluster/scenario_basic_test.go
Labels: lgtm, approved, size/XL

#1351 chore: update deploy help text
  cmd/deploy.go
  docs/reference/func_deploy.md
Labels: lgtm, approved, size/M

#1357 test: extended integration test for deployment
  knative/deployer.go
  knative/integration_test.go
  knative/logs.go
Labels: lgtm, approved, size/L

#1355 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1359 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#1354 fix: remove ldflags from docs generation make target
  Makefile
Labels: lgtm, approved, size/XS

#1361 test: fix condition and error message
  knative/integration_test.go
Labels: lgtm, approved, size/XS

#1235 test: adding oncluster builds e2e tests for s2i supported runtimes
  pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  test/_oncluster/scenario_runtime_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#1365 chore: add nodejs as a builder key
  buildpacks/builder.go
  s2i/builder.go
Labels: lgtm, approved, size/XS, kind/chore

#1344 chore: global config file paths
  client.go
  client_test.go
  cmd/build.go
  cmd/client.go
  cmd/create.go
  cmd/create_test.go
  cmd/delete.go
  cmd/deploy.go
  cmd/invoke.go
  cmd/languages.go
  cmd/repository.go
  cmd/templates.go
  config/config.go
  config/config_test.go
  docker/creds/credentials.go
  docker/creds/credentials_test.go
  go.mod
  job.go
  repositories.go
Labels: kind/enhancement, lgtm, approved, size/XL

#1373 fix: function constructor errors on valid path
  function.go
  function_test.go
  instances_test.go
Labels: lgtm, approved, size/M

#1364 feat: improve output of s2i build and push
  docker/pusher.go
  s2i/builder.go
Labels: lgtm, approved, size/L

#1374 Fix Tekton tasks install failures on CI
  hack/tekton.sh
Labels: lgtm, approved, size/XS, kind/cleanup

#1376 fix: config dir default empty
  config/config.go
  docker/creds/credentials_test.go
Labels: size/S, lgtm, approved

#1377 upgrade ci resources version
  hack/allocate.sh
  hack/binaries.sh
Labels: size/S, lgtm, approved, kind/cleanup

#1378 test: improve knative tests
  knative/integration_test.go
Labels: lgtm, approved, size/M

#1380 chore: update README.md with proper links
  README.md
Labels: lgtm, approved, size/XS, kind/chore

#1375 feat: defer OpenShift detection
  cmd/build.go
  cmd/client.go
  cmd/deploy.go
  cmd/run.go
  openshift/openshift.go
Labels: kind/enhancement, lgtm, approved, size/M

#1384 fix: make socat image public and remove socat image env
  k8s/dialer.go
Labels: size/S, lgtm, approved, kind/cleanup

#1388 chore: ensure all tests clear cmd args
  cmd/build_test.go
  cmd/config_labels_test.go
  cmd/delete_test.go
  cmd/deploy_test.go
  cmd/invoke_test.go
  cmd/languages_test.go
  cmd/templates_test.go
Labels: lgtm, approved, size/M

#1387 fix: KUBECONFIG unit test interference
  cmd/deploy_test.go
  cmd/root_test.go
  cmd/testdata/TestDeploy_NamespaceDefaults/TestDeploy_NamespaceRedeployWarning/kubeconfig
  cmd/testdata/TestDeploy_NamespaceDefaults/kubeconfig
  cmd/testdata/TestDeploy_NamespaceRedeployWarning/kubeconfig
  cmd/testdata/Test_namespace/kubeconfig
  cmd/testdata/default_kubeconfig
  cmd/testdata/kubeconfig_deploy_namespace
  openshift/openshift.go
Labels: lgtm, approved, size/L

#1389 chore: mock deployer method signature
  client_test.go
  cmd/deploy_test.go
  mock/deployer.go
Labels: kind/techdebt, lgtm, approved, size/M

#1386 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1391 feat: builder globally configurable
  cmd/build.go
  cmd/deploy.go
  config/config.go
Labels: kind/enhancement, size/S, lgtm, approved

#1352 feat: namespace globally configurable
  cmd/delete.go
  cmd/deploy.go
  cmd/info.go
  cmd/list.go
  cmd/repository.go
  cmd/root.go
  cmd/root_test.go
  config/config.go
  config/config_test.go
  config/testdata/TestDefaultNamespace/kubeconfig
  config/testdata/TestLoad/func/config.yaml
  docs/reference/func.md
  docs/reference/func_build.md
  docs/reference/func_completion.md
  docs/reference/func_config.md
  docs/reference/func_config_envs.md
  docs/reference/func_config_envs_add.md
  docs/reference/func_config_envs_remove.md
  docs/reference/func_config_labels.md
  docs/reference/func_config_labels_add.md
  docs/reference/func_config_labels_remove.md
  docs/reference/func_config_volumes.md
  docs/reference/func_config_volumes_add.md
  docs/reference/func_config_volumes_remove.md
  docs/reference/func_create.md
  docs/reference/func_delete.md
  docs/reference/func_info.md
  docs/reference/func_invoke.md
  docs/reference/func_languages.md
  docs/reference/func_list.md
  docs/reference/func_repository.md
  docs/reference/func_repository_add.md
  docs/reference/func_repository_list.md
  docs/reference/func_repository_remove.md
  docs/reference/func_repository_rename.md
  docs/reference/func_run.md
  docs/reference/func_templates.md
  docs/reference/func_version.md
Labels: kind/enhancement, lgtm, approved, size/L

#1392 feat: registry globally configurable
  cmd/build.go
  cmd/deploy.go
  cmd/root.go
  config/config.go
Labels: kind/enhancement, lgtm, approved, size/M

#1381 feat: describe command namespace
  client.go
  cmd/delete_test.go
  cmd/describe.go
  cmd/describe_test.go
  cmd/root.go
  docs/reference/func.md
  docs/reference/func_describe.md
Labels: kind/techdebt, lgtm, approved, size/L

#1372 chore: delete command namespace
  cmd/delete.go
  cmd/delete_test.go
  docs/reference/func_delete.md
Labels: kind/techdebt, lgtm, approved, size/M

#1390 chore: deploy cmd namespace
  cmd/deploy.go
  cmd/deploy_test.go
Labels: lgtm, approved, size/L

#1393 chore: update lifecycle
  buildpacks/builder.go
Labels: lgtm, approved, size/XS

#1370 chore: list command namespace
  cmd/list.go
  cmd/list_test.go
  docs/reference/func_list.md
Labels: kind/techdebt, lgtm, approved, size/L

#1394 chore(deps): update node and typescript deps
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/.prettierrc
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/cloudevents/src/index.ts
  templates/typescript/cloudevents/test/integration.ts
  templates/typescript/cloudevents/test/unit.ts
  templates/typescript/http/.prettierrc
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
  zz_filesystem_generated.go
Labels: lgtm, approved, size/L, kind/chore
