Repository knative/func, pull requests merged in 2022-09, with the labels that each got.

#1211 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1185 fix: image name derivation and flag precidence
  client.go
  client_test.go
  cmd/build.go
  cmd/build_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/root.go
  cmd/run.go
  function.go
  function_unit_test.go
Labels: lgtm, approved, size/XXL, kind/cleanup

#1193 Oncluster build initial e2e set of tests
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  Makefile
  hack/tekton.sh
  hack/test-integration-podman.sh
  test/README.md
  test/_common/cmd.go
  test/_common/gitserver.go
  test/_common/knfunc.go
  test/_common/shell.go
  test/_e2e/cleaner.go
  test/_e2e/cmd_deploy_test.go
  test/_e2e/knative.go
  test/_e2e/ready_check.go
  test/_e2e/update_test.go
  test/_oncluster/asserts.go
  test/_oncluster/git_helper.go
  test/_oncluster/nodejs_helper.go
  test/_oncluster/scenario_basic_test.go
  test/_oncluster/scenario_context-dir_test.go
  test/_oncluster/scenario_from-cli-local_test.go
  test/_oncluster/scenario_from-cli_test.go
  test/_oncluster/scenario_revision_test.go
  test/_oncluster/scenario_runtime_test.go
  test/_oncluster/tekton.go
  test/e2e_oncluster_tests.sh
  test/gitserver.sh
Labels: kind/enhancement, lgtm, approved, size/XXL

#1213 fix: on cluster build - populate image name if not set
  client.go
  client_test.go
  pipelines/tekton/pipeplines_provider.go
Labels: kind/bug, lgtm, approved, size/L

#1181 fix: in cluster dialer security context is non-privileged
  k8s/dialer.go
Labels: size/S, lgtm, approved

#1219 fix: downstream e2e fails with unknown default builder image
  test/_e2e/cmd_invoke_test.go
Labels: kind/bug, lgtm, approved, size/XS

#1215 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1217 fixed a variable name error in docs
  docs/function-developers/python.md
Labels: lgtm, approved, size/XS

#1214 fix: on cluster build - workaround for Tekton issue with empty array
  pipelines/tekton/resources.go
Labels: kind/bug, lgtm, approved, size/XS

#1223 fix: use flag value as default or when changed only
  cmd/build.go
  cmd/deploy.go
Labels: kind/bug, size/S, lgtm, approved

#1226 fix: correct error handling in filesystem tests
  filesystem_test.go
Labels: lgtm, approved, size/XS

#1227 fix: s2i build on Windows
  s2i/builder.go
Labels: lgtm, approved, size/XS

#1228 docs: update podman docs
  docs/reference/podman.md
Labels: lgtm, approved, size/XS

#1205 Adds labels and annotations from func.yaml to pipeline resources
  function.go
  function_unit_test.go
  k8s/persistent_volumes.go
  k8s/secrets.go
  knative/deployer.go
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/resources.go
Labels: kind/enhancement, lgtm, approved, size/L

#1224 feat: UX improvements for docker/podman usage
  cmd/func/main.go
  docker/docker_client.go
  docker/docker_client_ssh_test.go
Labels: lgtm, approved, size/L

#1231 fix: pack build outpout on Windows
  buildpacks/builder.go
  go.mod
Labels: lgtm, approved, size/M

#1230 Improvements for podman on Windows and macOS
  docker/docker_client.go
  docker/docker_client_linux_test.go
  docker/docker_client_pm_test.go
  docker/docker_client_ssh_test.go
  docker/docker_client_test.go
  docker/docker_client_windows_test.go
  go.mod
  go.sum
  ssh/ssh_agent_conf_windows.go
  vendor/gopkg.in/natefinch/npipe.v2/.gitignore
  vendor/gopkg.in/natefinch/npipe.v2/LICENSE.txt
  vendor/gopkg.in/natefinch/npipe.v2/README.md
  vendor/gopkg.in/natefinch/npipe.v2/doc.go
  vendor/gopkg.in/natefinch/npipe.v2/npipe_windows.go
  vendor/gopkg.in/natefinch/npipe.v2/znpipe_windows_386.go
  vendor/gopkg.in/natefinch/npipe.v2/znpipe_windows_amd64.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1232 chore: dialer improvements
  k8s/dialer.go
  k8s/dialer_test.go
Labels: size/S, lgtm, approved

#1233 fix: s2i on cluster build of Quarkus functions
  pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pipelines/tekton/resources.go
  pipelines/tekton/tasks.go
Labels: kind/bug, size/S, lgtm, approved

#1237 fixup: fix base for another PR
  docs/reference/func.md
Labels: lgtm, approved, size/XS

#1239 fix: cleanup of auto-podman-service when receiving SIGINT/SIGTERM
  docker/docker_client.go
  docker/docker_client_linux.go
  docker/docker_client_nonlinux.go
Labels: lgtm, approved, size/L

#1246 fix: updated func-deploy tekton task to aling with the new deploy command build flag options
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1244 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/M, skip-review

#1247 Update Go in actions to 1.18
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  Makefile
Labels: size/S, lgtm, approved

#1249 fix: wrong-error-message-reported-in-command-func-templates-repository
  cmd/client.go
  cmd/templates.go
  cmd/templates_test.go
Labels: lgtm, approved, size/M

#1257 fix: incorrect deploy namespace warnings
  cmd/deploy.go
Labels: kind/bug, lgtm, approved, size/XS

#1261 chore: sync docs with the source code
  docs/reference/func.md
  docs/reference/func_build.md
  docs/reference/func_deploy.md
Labels: lgtm, approved, size/XS

#1255 feat: `invoke` - Adding option allowing insecure connections over SSL
  cmd/client.go
  cmd/invoke.go
  docs/reference/func_invoke.md
  http/transport.go
Labels: kind/enhancement, lgtm, approved, size/M

#1263 fix: validation of function name
  utils/names.go
  utils/names_test.go
Labels: kind/bug, size/S, lgtm, approved

#1268 fix: registry prompt result being ignored
  cmd/build.go
Labels: kind/bug, lgtm, approved, size/XS

#1266 chore: linkage assignable socatImage
  k8s/dialer.go
Labels: lgtm, approved, size/XS

#1264 [chore] Adding Codecov badge to readme
  README.md
Labels: kind/enhancement, lgtm, approved, size/XS

#1270 [chore] updating codecov configs
  .codecov.yaml
Labels: size/S, lgtm, approved, kind/cleanup

#1262 Update Go version to 1.18
  go.mod
  go.sum
Labels: lgtm, approved, size/L, kind/cleanup

#1273 fix: nil deref when custom builder image
  function.go
Labels: kind/bug, approved, size/XS

#1271 fix: stdin interactivity check
  cmd/root.go
Labels: kind/bug, lgtm, approved, size/XS

#1254 [feat] refactoring func.yaml struct to match cmd lifecycle
  builders/builders.go
  builders/builders_test.go
  buildpacks/builder.go
  buildpacks/builder_test.go
  client_test.go
  cmd/build.go
  cmd/client.go
  cmd/completion_util.go
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_labels_test.go
  cmd/config_test.go
  cmd/config_volumes.go
  cmd/create.go
  cmd/delete.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/repository_test.go
  cmd/run.go
  docker/runner.go
  function.go
  function_migrations.go
  function_migrations_unit_test.go
  function_test.go
  function_unit_test.go
  knative/deployer.go
  knative/deployer_test.go
  openshift/metadata.go
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/resources.go
  pipelines/tekton/resources_test.go
  pipelines/tekton/validate.go
  pipelines/tekton/validate_test.go
  repository_test.go
  s2i/builder.go
  s2i/builder_test.go
  schema/func_yaml-schema.json
  template.go
  templates_test.go
  test/_oncluster/git_helper.go
  testdata/migrations/v0.34.0/func.yaml
  testdata/testFunctionMarshallingError/func.yaml
  testdata/testFunctionMigrationError/func.yaml
Labels: lgtm, approved, size/XXL, kind/api-change

#1258 fix: always use function's namespace when invoking remote
  cmd/invoke.go
  cmd/invoke_test.go
Labels: kind/bug, lgtm, approved, size/L

#1260 feat: readonly global config
  client.go
  cmd/build.go
  cmd/create.go
  cmd/create_test.go
  cmd/delete.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/invoke.go
  cmd/repository.go
  config.go
  config/config.go
  config/config_test.go
  config/testdata/func/config.yaml
  docker/creds/credentials.go
  docker/creds/credentials_test.go
  testing/testing.go
Labels: kind/enhancement, lgtm, approved, size/L

#1282 fix: default readiness endpoint
  repository.go
Labels: lgtm, approved, size/XS

#1276 [chore] increase labels, envs and volumes test coverage
  function_envs_unit_test.go
  function_labels_unit_test.go
  function_volumes_unit_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1285 chore: Refactor use of deprecated `io/ioutil` package
  client_test.go
  cmd/delete_test.go
  cmd/invoke.go
  config/config.go
  docker/creds/credentials.go
  docker/creds/credentials_test.go
  docker/docker_client_ssh_test.go
  docs/generator/main.go
  filesystem_test.go
  function.go
  function_volumes.go
  invoke.go
  repository.go
  s2i/builder_test.go
  schema/generator/main.go
  ssh/ssh_dialer.go
  test/_e2e/trigger_events_test.go
  test/_e2e/trigger_http_test.go
  test/_e2e/update_test.go
  testing/testing.go
Labels: lgtm, approved, size/L

#1288 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1291 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1292 feat: always pull base image for s2i builds
  s2i/builder.go
Labels: kind/enhancement, lgtm, approved, size/XS
