Repository knative/func, pull requests merged in 2022-03, with the labels that each got.

#840 Adding sample function in go template
  .gitignore
  templates/go/cloudevents/README.md
  templates/go/cloudevents/handle.go
  templates/go/cloudevents/handle_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#816 printing helpful shorthand command
  cmd/create.go
Labels: kind/enhancement, lgtm, approved, size/M

#876 Fix OpenShift credential loader
  openshift/openshift.go
Labels: lgtm, approved, size/XS

#873 fix: use full root name for cmd help prefixes
  cmd/create.go
  cmd/invoke.go
  cmd/root.go
Labels: kind/bug, lgtm, approved, size/XS

#875 feat: command help text template preprocessing
  cmd/build.go
  cmd/config.go
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_volumes.go
  cmd/delete.go
  cmd/deploy.go
  cmd/info.go
  cmd/invoke.go
  cmd/list.go
  cmd/repository.go
  cmd/root.go
  cmd/run.go
  cmd/version.go
Labels: kind/enhancement, lgtm, approved, size/L

#865 src: update root and version structure and help text
  cmd/root.go
  cmd/root_test.go
  cmd/version.go
Labels: lgtm, approved, size/L

#877 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#878 Relax permission check only to owner exec perm
  filesystem_test.go
Labels: lgtm, approved, size/XS

#869 src: promote verbosity to constructor arg
  buildpacks/builder.go
  client_int_test.go
  cmd/client.go
  cmd/completion_util.go
  cmd/root.go
  cmd/run.go
  cmd/version.go
  docker/pusher.go
  docker/pusher_test.go
  docker/runner.go
  docker/runner_test.go
  knative/deployer.go
  knative/describer.go
  knative/lister.go
  knative/remover.go
  pipelines/tekton/pipeplines_provider.go
  progress/progress.go
Labels: lgtm, approved, size/L

#881 Make `func invoke` print any response it receives.
  client.go
  client_test.go
  cmd/invoke.go
  invoke.go
Labels: kind/enhancement, lgtm, approved, size/M

#879 Generate templates zip unconditionally
  .github/workflows/ci.yaml
  Makefile
  generate/templates/main.go
Labels: lgtm, approved, size/L

#882 Fix return value of goByteArrayWriter.Write()
  generate/templates/main.go
Labels: size/S, lgtm, approved

#885 Hint to user when ssh server key is not known
  ssh/terminal.go
Labels: lgtm, approved, size/XS

#884 fix: bind verbose flag to root
  cmd/root.go
Labels: kind/bug, lgtm, approved, size/XS

#887 Improve cleanup recipes in Makefile
  Makefile
Labels: size/S, lgtm, approved

#888 Update developer documentation.
  docs/DEVELOPMENT.md
Labels: lgtm, approved, size/M

#889 Update wrt switch from pkger to custom ZIP pkging
  docs/DEVELOPMENT.md
  hack/verify-codegen.sh
  templates/README.md
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XXL

#890 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#838 Updating to latest spring cloud release and refactoring code
  .gitignore
  templates/springboot/cloudevents/README.md
  templates/springboot/cloudevents/manifest.yaml
  templates/springboot/cloudevents/pom.xml
  templates/springboot/cloudevents/src/main/java/echo/EchoFunction.java
  templates/springboot/cloudevents/src/main/java/echo/SpringCloudEventsApplication.java
  templates/springboot/cloudevents/src/main/java/functions/Input.java
  templates/springboot/cloudevents/src/main/java/functions/Output.java
  templates/springboot/cloudevents/src/main/java/functions/SpringCloudEventsApplication.java
  templates/springboot/cloudevents/src/test/java/echo/SpringCloudEventsApplicationTests.java
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XXL

#892 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#895 docs: parameter `-P` is not needed in grep in pre-commit hook
  docs/DEVELOPMENT.md
Labels: lgtm, approved, size/XS

#902 improve template comments for Node.js and TypeScript
  templates/node/cloudevents/index.js
  templates/node/http/index.js
  templates/typescript/cloudevents/src/index.ts
  templates/typescript/http/src/index.ts
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XXL, kind/chore

#904 fix: full clone of template repos on add
  repositories_test.go
  repository.go
Labels: kind/bug, lgtm, approved, size/M

#900 src: differentiate repository from repositories
  client.go
  client_test.go
  cmd/client.go
  cmd/create.go
  cmd/create_test.go
  cmd/repository.go
  cmd/repository_test.go
  docs/guides/commands.md
  repositories_test.go
  repository_test.go
  templates_test.go
Labels: lgtm, approved, size/L, kind/cleanup

#907 doc: add documentation for using podman remotely
  docs/guides/podman.md
Labels: lgtm, approved, size/M, kind/documentation

#910 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#916 Improve error handling
  buildpacks/builder.go
  client.go
  client_test.go
  cmd/build.go
  cmd/config.go
  cmd/config_envs.go
  cmd/create.go
  docker/pusher.go
  docker/pusher_test.go
  k8s/client.go
  pipelines/tekton/client.go
  ssh/terminal.go
Labels: lgtm, approved, size/M

#919 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#917 Improve template ZIP generation
  generate/templates/main.go
  zz_filesystem_generated.go
Labels: lgtm, approved, size/L

#920 Support using 'func invoke' for springboot templates
  templates/springboot/cloudevents/README.md
  templates/springboot/cloudevents/src/main/java/echo/EchoFunction.java
  templates/springboot/cloudevents/src/test/java/echo/SpringCloudEventsApplicationTests.java
  templates/springboot/http/README.md
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XXL, kind/documentation

#883 src: exported client constructor with options
  client_int_test.go
  client_test.go
  cmd/build.go
  cmd/build_test.go
  cmd/client.go
  cmd/config_labels_test.go
  cmd/create.go
  cmd/create_test.go
  cmd/delete.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/func/main.go
  cmd/info.go
  cmd/invoke.go
  cmd/list.go
  cmd/repository.go
  cmd/repository_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/run_test.go
  docker/pusher.go
  docker/pusher_test.go
  function_labels_unit_test.go
  pipelines/tekton/pipeplines_provider.go
  plugin/plugin.go
  testing/testing.go
Labels: lgtm, approved, size/XXL, kind/cleanup

#921 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#927 fix: revert cross-org workflow update
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: kind/bug, lgtm, approved, size/XL
