Repository knative/func, pull requests merged in 2022-05, with the labels that each got.

#1006 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1004 Allow empty credentials registry
  docker/creds/credentials.go
  docker/creds/credentials_test.go
Labels: lgtm, approved, size/L

#1001 chore: use paketo builders for all runtimes
  buildpacks/builder.go
  templates/rust/manifest.yaml
  templates/springboot/manifest.yaml
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XS

#1008 Remove unnecesary files from Java template
  templates/quarkus/cloudevents/.mvn/wrapper/maven-wrapper.jar
  templates/quarkus/http/.mvn/wrapper/maven-wrapper.jar
  templates/springboot/cloudevents/.mvn/wrapper/maven-wrapper.jar
  templates/springboot/http/.mvn/wrapper/maven-wrapper.jar
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XS

#1009 User fast-jar packaging for Quarkus
  templates/quarkus/cloudevents/src/main/resources/application.properties
  templates/quarkus/http/src/main/resources/application.properties
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XS

#1012 Update S2I envvars to work with fast-jar
  templates/quarkus/manifest.yaml
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XS

#1013 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1007 feat: improved invoke verbosity
  client.go
  cmd/invoke.go
  invoke.go
  templates/go/cloudevents/handle.go
  templates/go/cloudevents/handle_test.go
  templates/go/http/handle.go
  templates/go/http/handle_test.go
  test/_e2e/trigger_http_test.go
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/L

#1014 Fix S2I build with podman
  s2i/builder.go
  s2i/docker_client_wrapper.go
Labels: lgtm, approved, size/M

#1016 Use struct embedding instead of generated code
  .codecov.yaml
  docker/docker_client.go
  docker/docker_client_generated.go
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1019 fix: ignore node_modules for s2i builds
  s2i/builder.go
Labels: kind/bug, lgtm, approved, size/XS

#1023 Improve help for the `build` sub-command
  cmd/build.go
  cmd/completion_util.go
Labels: lgtm, approved, size/M

#1020 Make JS/TS Function templates async by default
  templates/node/cloudevents/index.js
  templates/node/cloudevents/test/unit.js
  templates/node/http/index.js
  templates/node/http/test/unit.js
  templates/typescript/cloudevents/src/index.ts
  templates/typescript/cloudevents/test/unit.ts
  templates/typescript/http/src/index.ts
  templates/typescript/http/test/unit.ts
  zz_filesystem_generated.go
Labels: lgtm, approved, size/M

#1024 feat: configurable s2i builder images
  cmd/build.go
  function.go
  s2i/builder.go
  s2i/builder_test.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/L
