Repository knative/func, pull requests merged in 2022-04, with the labels that each got.

#933 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#932 chore: add Apple M1 build in cross-platform target
  .github/workflows/ci.yaml
  Makefile
Labels: size/S, lgtm, approved, kind/chore

#939 Cherry pick SpringBoot updates for Release 0.22
  pkged.go
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
Labels: kind/bug, size/S, lgtm, approved

#938 Use "openshift" uname for OpenShift image registry
  openshift/openshift.go
Labels: lgtm, approved, size/XS

#924 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#940 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/L

#934 feat: on cluster build doesn't require privileged cluster permissions
  docs/guides/on-cluster-build.md
  k8s/secrets.go
  pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
  pipelines/tekton/client.go
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/resources.go
  pipelines/tekton/tasks.go
Labels: lgtm, approved, size/L

#943 Print logs if Pipeline Run fails
  k8s/logs.go
  pipelines/tekton/pipeplines_provider.go
Labels: lgtm, approved, size/M

#944 feat: invoke verbose metadata
  client.go
  client_test.go
  cmd/invoke.go
  invoke.go
Labels: kind/enhancement, lgtm, approved, size/M

#947 chore: update spring-boot in templates
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
  zz_filesystem_generated.go
Labels: lgtm, approved, size/M

#949 Template generation improvements
  filesystem_test.go
  generate/templates/main.go
Labels: size/S, lgtm, approved

#946 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#950 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#945 chore: add release process and func_darwin_arm64 to the release artifacts
  .versionrc
  CHANGELOG.md
  docs/RELEASING.md
  hack/release.sh
  version.txt
Labels: lgtm, approved, size/L, kind/chore

#953 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#948 feat: make templates consistent across runtimes
  templates/python/cloudevents/func.py
  templates/python/cloudevents/test_func.py
  templates/python/http/func.py
  templates/quarkus/cloudevents/src/main/java/functions/Function.java
  templates/quarkus/http/src/main/java/functions/Function.java
  templates/typescript/http/src/index.ts
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#956 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#918 docs: add a language pack "contract" document
  docs/CONTRIBUTING.md
  docs/function-developers/developers_guide.md
  docs/function-developers/getting_started.md
  docs/function-developers/golang.md
  docs/function-developers/nodejs.md
  docs/function-developers/python.md
  docs/function-developers/quarkus.md
  docs/function-developers/rust.md
  docs/function-developers/typescript.md
  docs/guides/developers_guide.md
  docs/guides/language-packs.md
  docs/installing_cli.md
  docs/language-pack-providers/language-pack-contract.md
  docs/reference/commands.md
  docs/reference/func_yaml.md
  docs/reference/integrators_guide.md
  docs/reference/on_cluster_build.md
  docs/reference/podman.md
  docs/reference/templates.md
Labels: lgtm, approved, size/L

#962 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#963 chore(release): 0.23.1
  CHANGELOG.md
  version.txt
Labels: lgtm, approved, size/XS

#966 chore: add version.txt to .gitattributes for style
  .gitattributes
Labels: lgtm, approved, size/XS, kind/chore

#959 Update Springboot e2e tests
  test/_e2e/trigger_events_test.go
  test/_e2e/trigger_http_test.go
  test/_e2e/update_templates/quarkus/http/pom.xml
  test/_e2e/update_templates/springboot/http/src/main/java/functions/CloudFunctionApplication.java
  test/_e2e/update_test.go
  test/e2e_lifecycle_tests.sh
Labels: lgtm, approved, size/L, kind/cleanup

#957 feat: s2i builder typescript support
  buildpacks/builder.go
  s2i/builder.go
  templates/typescript/manifest.yaml
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/XL

#972 Add unicode control chars exclude
  .unicode-control-characters.config.py
Labels: lgtm, approved, size/XS

#965 chore: update allocate script with latest knative
  hack/allocate.sh
Labels: size/S, lgtm, approved, kind/chore

#961 Refactor: templates
  client.go
  filesystem.go
  repository.go
  repository_test.go
  template.go
  templates.go
  templates_test.go
Labels: lgtm, approved, size/L

#973 Refactor: clean Repository and Runtimes structs
  function.go
  repository.go
  template.go
Labels: lgtm, approved, size/L

#967 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
Labels: size/S, lgtm, approved

#979 feat: enable Paketo builders for Python functions
  buildpacks/builder.go
  templates/python/cloudevents/Procfile
  templates/python/cloudevents/README.md
  templates/python/http/Procfile
  templates/python/http/README.md
  templates/python/manifest.yaml
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/M, do-not-merge/hold

#981 [fix] Docs typo: "Knaive" -> "Knative"
  docs/function-developers/developers_guide.md
Labels: lgtm, approved, size/XS, kind/documentation

#983 test: update python e2e tests (new revision test)
  test/_e2e/update_templates/python/http/Procfile
Labels: lgtm, approved, size/XS, kind/cleanup

#980 fix: update various doc links
  README.md
  docs/README.md
Labels: size/S, lgtm, approved

#985 feat: use Paketo buildpack for Quarkus
  templates/quarkus/cloudevents/README.md
  templates/quarkus/cloudevents/manifest.yaml
  templates/quarkus/http/README.md
  templates/quarkus/manifest.yaml
  zz_filesystem_generated.go
Labels: lgtm, approved, size/M

#987 Use socat image from quay.io
  k8s/dialer.go
Labels: lgtm, approved, size/XS

#988 fix: ignore `is forbidden` errors when deleting function and resources
  pipelines/tekton/pipeplines_provider.go
Labels: lgtm, approved, size/XS

#991 feat: s2i builder env var interpolation
  buildpacks/builder.go
  function.go
  function_test.go
  s2i/builder.go
Labels: kind/enhancement, lgtm, approved, size/L

#992 src: update runner with shared env var interpolation
  docker/runner.go
  function_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#993 feat: s2i builder quarkus support
  buildpacks/builder.go
  s2i/builder.go
  templates/quarkus/manifest.yaml
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/XS

#994 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#996 Fix read pwd from non-tty input
  cmd/client.go
  cmd/deploy.go
  cmd/prompt_test.go
Labels: kind/bug, lgtm, approved, size/L

#1000 chore(deps): bump faas-js-runtime version
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XXL, kind/chore

#999 Update spring boot cloud and native versions
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/M
