Repository knative/func, pull requests merged in 2022-12, with the labels that each got.

#1426 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1455 docs: update on cluster build guide to explicitly mention `--remote` flag
  docs/building-functions/on_cluster_build.md
Labels: lgtm, approved, size/XS, kind/documentation

#1461 fix: podman installation in GH action
  .github/workflows/test-podman.yaml
Labels: size/S, lgtm, approved

#1462 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1349 Set seccomp of auxiliary pods on k8s 1.24+
  k8s/dialer.go
  k8s/persistent_volumes.go
  k8s/security_context.go
Labels: kind/bug, size/S, lgtm, approved

#1433 fix: add default PodSecurityContext to the uploader (#1432)
  go.mod
  k8s/dialer.go
  k8s/persistent_volumes.go
  k8s/security_context.go
Labels: size/S, lgtm, approved

#1474 Cleanup e2e on cluster tests
  test/_common/gitserver.go
  test/_e2e/config.go
  test/_oncluster/git_helper.go
  test/_oncluster/scenario_basic_test.go
  test/_oncluster/scenario_context-dir_test.go
  test/_oncluster/scenario_from-cli-local_test.go
  test/_oncluster/scenario_from-cli_test.go
  test/_oncluster/scenario_revision_test.go
  test/_oncluster/scenario_runtime_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#1475 feat: change default pvc size to 256Mi (#851)
  pipelines/tekton/defaults.go
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/pipeplines_provider_test.go
Labels: lgtm, approved, size/M
