Repository knative/func, pull requests merged in 2022-07, with the labels that each got.

#1093 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1091 Improve usability of `func` CLI for IDE plugins
  cmd/deploy.go
  docker/creds/credentials.go
Labels: lgtm, approved, size/M

#1090 feat: deploy success message also displays the namespace
  client.go
  client_test.go
  knative/deployer.go
  mock/deployer.go
  pipelines/tekton/pipeplines_provider.go
  test/_e2e/cmd_deploy_test.go
Labels: lgtm, approved, size/M

#1100 Fix: try empty credentials as last option
  docker/creds/credentials.go
Labels: kind/bug, lgtm, approved, size/XS

#1102 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1101 Update to the latest knative version
  docs/getting_started_kubernetes.md
Labels: size/S, lgtm, approved, kind/documentation

#1107 Update Knative dependencies to v1.3 (0.30)
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/serving_client.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1109 fix: image push authorization check
  docker/creds/credentials.go
  docker/creds/credentials_test.go
  docker/pusher.go
  pipelines/tekton/pipeplines_provider.go
Labels: kind/bug, lgtm, approved, size/M

#1098 feat: func deploy accepts image digest in --image
  cmd/deploy.go
  cmd/deploy_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1105 fix: use 0 group id for func-buildpacks Task
  pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
Labels: size/S, lgtm, approved

#1106 feat: add OpenShift related Annotations & Labels
  client_int_test.go
  cmd/client.go
  knative/deployer.go
  openshift/metadata.go
  pipelines/tekton/pipeplines_provider.go
Labels: kind/enhancement, lgtm, approved, size/L

#1110 chore(deps): update node and typescript dependencies
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/package-lock.json
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XXL

#1119 chore(deps): update node/typescript deps in e2e tests
  test/_e2e/update_templates/node/cloudevents/package-lock.json
  test/_e2e/update_templates/node/http/package-lock.json
  test/_e2e/update_templates/typescript/http/package-lock.json
Labels: lgtm, approved, size/XXL, kind/chore

#1123 feat: build for Linux ARM64
  .github/workflows/ci.yaml
  Makefile
  hack/release.sh
Labels: kind/enhancement, size/S, lgtm, approved

#1127 fix: add languages command to cmd root
  cmd/languages.go
  cmd/root.go
Labels: lgtm, approved, size/XS

#1118 feat: always store namespace in func.yaml and warn if current ns & func.yaml ns is different
  cmd/build_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/testdata/kubeconfig_deploy_namespace
Labels: lgtm, approved, size/L

#1132 chore: update Quarkus templates to 2.10.3.Final
  templates/quarkus/cloudevents/pom.xml
  templates/quarkus/http/pom.xml
  zz_filesystem_generated.go
Labels: lgtm, approved, size/L, kind/cleanup

#1137 test: remove verbose from test invoke create/deploy commands
  test/_e2e/cmd_invoke_test.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1133 fix: stop build progress loop when build completes
  client.go
Labels: lgtm, approved, size/XS

#1136 chore: add validation for `builder`
  buildpacks/builder.go
  cmd/build.go
  cmd/completion_util.go
  cmd/deploy.go
  function.go
  function_builder.go
  function_builder_unit_test.go
  s2i/builder.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/L

#1089 docs: replace commands.md with generated text file
  Makefile
  cmd/invoke.go
  docs/reference/commands.md
  docs/reference/commands.txt
  hack/build-docs.sh
Labels: lgtm, approved, size/XXL, kind/documentation

#1135 chore: use lower case *functions* in all CLI outputs
  client.go
  client_int_test.go
  client_test.go
  cmd/build.go
  cmd/build_test.go
  cmd/config.go
  cmd/create.go
  cmd/create_test.go
  cmd/delete.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/info.go
  cmd/invoke.go
  cmd/repository.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/run_test.go
  cmd/version.go
  config.go
  docker/creds/credentials_test.go
  docker/pusher.go
  docker/runner.go
  function.go
  function_buildtype.go
  function_git.go
  function_migrations.go
  function_migrations_unit_test.go
  function_test.go
  instances.go
  invoke.go
  job.go
  mock/runner.go
  repository.go
  repository_test.go
  s2i/builder.go
  s2i/builder_test.go
  schema/generator/main.go
  templates.go
  templates_test.go
  test/_e2e/cmd_config_envs_test.go
  test/_e2e/cmd_invoke_test.go
  test/_e2e/trigger_http_test.go
  testing/testing.go
Labels: lgtm, approved, size/XL, kind/cleanup

#1140 feat: deploy Tekton task supports optional `image` parameter
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: size/S, lgtm, approved

#1142 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1147 Quarkus platform auto-updater
  .github/workflows/update-quarkus-platform.yaml
  hack/update-quarkus-platform.sh
Labels: lgtm, approved, size/M

#1148 fixup: master->main
  hack/update-quarkus-platform.sh
Labels: lgtm, approved, size/XS
