Repository knative/func, pull requests merged in 2022-11, with the labels that each got.

#1395 test: clear cmd args
  cmd/delete_test.go
Labels: lgtm, approved, size/XS

#1397 chore(OWNERS): update to new org
  OWNERS
Labels: lgtm, approved, size/XS, kind/chore

#1396 test: fix tests when running in cluster
  cmd/delete_test.go
  cmd/describe_test.go
  config/config_test.go
Labels: lgtm, approved, size/XS

#1399 fix: allow symlinks in templates
  filesystem.go
  filesystem_test.go
  generate/templates/main.go
Labels: kind/bug, lgtm, approved, size/L

#1401 fix: uploading of project containing symlink for on-cluster-build
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/pipeplines_provider_test.go
  pipelines/tekton/testData/fn-src/hello.txt.lnk
Labels: kind/bug, lgtm, approved, size/M

#1400 refactor: clean up
  filesystem.go
  filesystem_test.go
  generate/templates/main.go
Labels: lgtm, approved, size/L, kind/cleanup

#1403 chore: update buildpack lifecycle image to v0.15.0
  buildpacks/builder.go
Labels: lgtm, approved, size/XS

#1404 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1407 [main] Format Go code
  cmd/deploy.go
  config/config.go
  k8s/dialer.go
  progress/progress.go
  repository.go
  ssh/ssh_dialer.go
  test/_e2e/main_test.go
  test/_oncluster/scenario_context-dir_test.go
  testing/testing.go
Labels: lgtm, approved, size/M

#1410 fix: error instantiating empty function
  client.go
  function.go
  function_unit_test.go
  instances.go
  repository.go
  templates.go
Labels: kind/bug, lgtm, approved, size/L

#1411 fix: path default is current working directory
  buildpacks/builder.go
  cmd/build.go
  cmd/config.go
  cmd/delete.go
  cmd/describe.go
  cmd/invoke.go
  cmd/root.go
  cmd/run.go
  docs/reference/func_build.md
  docs/reference/func_config.md
  docs/reference/func_config_envs.md
  docs/reference/func_config_envs_add.md
  docs/reference/func_config_envs_remove.md
  docs/reference/func_config_labels.md
  docs/reference/func_config_labels_add.md
  docs/reference/func_config_labels_remove.md
  docs/reference/func_config_volumes.md
  docs/reference/func_config_volumes_add.md
  docs/reference/func_config_volumes_remove.md
  docs/reference/func_delete.md
  docs/reference/func_deploy.md
  docs/reference/func_describe.md
  docs/reference/func_invoke.md
  docs/reference/func_run.md
  function.go
  function_test.go
Labels: lgtm, approved, size/L, kind/cleanup

#1406 feat: caching for on cluster s2i build
  pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pipelines/tekton/resources.go
  pipelines/tekton/tasks.go
Labels: kind/enhancement, lgtm, approved, size/M, kind/performance

#1409 fix: mock and noop inconsistency
  client.go
  cmd/build_test.go
  cmd/client.go
  cmd/client_test.go
  cmd/delete_test.go
  cmd/deploy_test.go
  cmd/describe_test.go
  cmd/languages_test.go
  cmd/run_test.go
  cmd/templates_test.go
  docs/generator/main.go
  mock/remover.go
Labels: kind/bug, lgtm, approved, size/L

#1412 src: rename config local variable cfg
  cmd/build.go
  cmd/deploy.go
  cmd/root.go
  cmd/run.go
Labels: lgtm, approved, size/L, kind/cleanup

#1422 enhancement(templates): use latest faas-js-runtime + cloudevents
  Makefile
  templates/node/cloudevents/index.js
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/cloudevents/test/integration.js
  templates/node/cloudevents/test/unit.js
  templates/node/http/index.js
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/node/http/test/unit.js
  templates/typescript/cloudevents/.prettierrc
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/cloudevents/src/index.ts
  templates/typescript/cloudevents/test/unit.ts
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
  templates/typescript/http/src/index.ts
  templates/typescript/http/test/unit.ts
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#1413 fix: build prompts
  cmd/build.go
  cmd/build_test.go
  cmd/deploy.go
  cmd/deploy_test.go
Labels: lgtm, approved, size/L

#1415 feat: Change Invocation.format to Invoke
  client.go
  function.go
  function_migrations.go
  function_migrations_unit_test.go
  invoke.go
  repository.go
  schema/func_yaml-schema.json
  template.go
  templates/go/cloudevents/manifest.yaml
  templates/go/http/manifest.yaml
  templates/node/cloudevents/manifest.yaml
  templates/python/cloudevents/manifest.yaml
  templates/quarkus/cloudevents/manifest.yaml
  templates/rust/cloudevents/manifest.yaml
  templates/springboot/cloudevents/manifest.yaml
  templates/typescript/cloudevents/manifest.yaml
  templates_test.go
  testdata/migrations/v0.35.0-nondefault/func.yaml
  testdata/migrations/v0.35.0/func.yaml
  testdata/repositories/customLanguagePackRepo/templates/manifestedRuntime/manifestedTemplate/manifest.yaml
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/L

#1402 feat: Persist remote value in func.yaml
  cmd/deploy.go
  cmd/deploy_test.go
  function.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/M

#1405 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/trigger.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1424 fix: ignore global config on docs gen
  docs/generator/main.go
Labels: size/S, lgtm, approved

#1429 Add VMware builder as trusted
  buildpacks/builder.go
Labels: lgtm, approved, size/XS

#1430 documentation: remove old docs and restructure
  docs/README.md
  docs/building-functions/on_cluster_build.md
  docs/building-functions/podman.md
  docs/function-developers/developers_guide.md
  docs/function-developers/getting_started.md
  docs/function-templates/golang.md
  docs/function-templates/nodejs.md
  docs/function-templates/python.md
  docs/function-templates/quarkus.md
  docs/function-templates/rust.md
  docs/function-templates/typescript.md
  docs/getting_started_kubernetes.md
  docs/getting_started_localhost.md
  docs/installing_cli.md
  docs/integrators_guide.md
  docs/knative/config-domain.yaml
  docs/knative/config-kourier-nodeport.yaml
  docs/knative/config-network.yaml
  docs/language-packs/language-pack-contract.md
  docs/language-packs/templates.md
  docs/provisioning/eks/config-cluster.yaml
  docs/provisioning/eks/users.yaml
  docs/provisioning/kind/config-local.yaml
  docs/provisioning/kind/config-remote.yaml
  docs/provisioning/provision_eks.md
  docs/provisioning/provision_kind.md
  docs/reference/templates.md
  docs/tls/cloudflare-secret.yaml
  docs/tls/letsencrypt-issuer.yaml
Labels: lgtm, approved, size/XL, kind/documentation

#1431 chore: improve func version verbose mode to display image referenced …
  cmd/root.go
  cmd/root_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#1425 src: update build command help text
  cmd/build.go
  docs/reference/func.md
  docs/reference/func_build.md
Labels: lgtm, approved, size/L

#1442 fix(GHSA-5336-2g3f-9g3m): Fixes GSA GHSA-5336-2g3f-9g3m
  buildpacks/builder.go
  buildpacks/builder_test.go
Labels: lgtm, approved, size/M

#1443 [release-1.8]: Fixes GHSA-5336-2g3f-9g3m
  buildpacks/builder.go
  buildpacks/builder_test.go
Labels: kind/bug, lgtm, approved, size/M

#1444 cleanup(buildpacks): tweak TrustedBuilder()
  buildpacks/builder.go
  buildpacks/builder_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#1416 feat: command function context
  cmd/build.go
  cmd/build_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/testdata/TestBuild_ConfigApplied/func/config.yaml
  cmd/testdata/TestBuild_ConfigPrecidence/func/config.yaml
  config/config.go
  config/config_test.go
  docs/reference/func_build.md
Labels: kind/enhancement, lgtm, approved, size/XL

#1438 Add Google Cloud Function Buildpacks to trusted builder prefixes
  buildpacks/builder.go
Labels: kind/enhancement, lgtm, approved, size/XS

#1449 fix: on cluster build
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: lgtm, approved, size/XS
