Repository knative/func, pull requests merged in 2022-01, with the labels that each got.

#734 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#730 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/XS

#733 Adding support to ssh-agent on Windows using named pipes
  go.mod
  go.sum
  ssh/ssh_agent_conf.go
  ssh/ssh_agent_conf_windows.go
  ssh/ssh_dialer.go
  vendor/gopkg.in/natefinch/npipe.v2/.gitignore
  vendor/gopkg.in/natefinch/npipe.v2/LICENSE.txt
  vendor/gopkg.in/natefinch/npipe.v2/README.md
  vendor/gopkg.in/natefinch/npipe.v2/doc.go
  vendor/gopkg.in/natefinch/npipe.v2/npipe_windows.go
  vendor/gopkg.in/natefinch/npipe.v2/znpipe_windows_386.go
  vendor/gopkg.in/natefinch/npipe.v2/znpipe_windows_amd64.go
  vendor/modules.txt
Labels: kind/enhancement, lgtm, approved, size/XXL

#692 Adding ko to produce image with func command
  .ko.yaml
Labels: kind/enhancement, lgtm, approved, cla: yes, size/XS

#736 feat: add possibility to disable pushing of image in `deploy` command
  client.go
  cmd/build.go
  cmd/build_test.go
  cmd/deploy.go
Labels: kind/enhancement, lgtm, approved, size/L

#738 Revert "feat: add possibility to disable pushing of image in `deploy` command"
  client.go
  cmd/build.go
  cmd/build_test.go
  cmd/deploy.go
Labels: lgtm, approved, size/L

#739 feat: add possibility to disable pushing of image in `deploy` command
  client.go
  cmd/build.go
  cmd/build_test.go
  cmd/deploy.go
Labels: kind/enhancement, lgtm, approved, size/L

#741 src: simplify go templates
  pkged.go
  templates/go/cloudevents/handle.go
  templates/go/cloudevents/handle_test.go
  templates/go/http/handle.go
  templates/go/http/handle_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#747 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#729 chore: add knative infra release scripts
  hack/release.sh
  test/presubmit-tests.sh
Labels: lgtm, approved, size/M, kind/chore

#737 chore: release 0.21.0
  CHANGELOG.md
  version.txt
Labels: size/S, size/S, lgtm, approved

#740 feat: add definition for `func-deploy` Tekton Task
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: kind/enhancement, lgtm, approved, size/M

#756 src: use common functionality for docker cred retrieval
  cmd/deploy.go
  docker/pusher.go
  docker/pusher_test.go
  pipelines/init.go
  pipelines/registry_credentials.go
  pipelines/tekton/pipeplines_provider.go
Labels: lgtm, approved, size/L

#749 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#759 src: simplyfing Knative Deployer RoleBinding used by Pipeline
  docs/guides/on-cluster-build.md
  k8s/role_bidings.go
  pipelines/resources/knative-deployer-account.yaml
  pipelines/resources/knative-deployer-clusterrole.yaml
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/resources.go
Labels: lgtm, approved, size/M

#760 fix: use correct --build flag value for `func-deploy` Tekton Task
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: lgtm, approved, size/XS

#757 feat: add a label to every resouce created for a Function
  k8s/labels/labels.go
  k8s/persistent_volumes.go
  k8s/role_bidings.go
  k8s/secrets.go
  k8s/service_accounts.go
  knative/deployer.go
  knative/lister.go
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/resources.go
Labels: kind/enhancement, lgtm, approved, size/M

#761 Support git scp url format
  function_git.go
  function_git_unit_test.go
Labels: size/S, size/S, lgtm, approved

#758 ensure build flag binds for run command
  cmd/run.go
Labels: kind/bug, lgtm, approved, size/XS

#764 chore: bump lifecycle version to 0.13.2
  buildpacks/builder.go
Labels: lgtm, approved, size/XS

#766 fixup: document minimum podman version
  docs/guides/podman.md
Labels: lgtm, approved, size/XS

#742 src: remove need for hosts entry for local clusters
  hack/allocate.sh
  hack/delete.sh
  hack/registry.sh
Labels: kind/techdebt, size/S, size/S, lgtm, approved

#770 Enable custom CA for specified server names
  http/transport.go
  http/transport_test.go
  k8s/dialer.go
  k8s/dialer_test.go
Labels: lgtm, approved, size/L

#705 feat!: invoke
  client.go
  client_test.go
  cloudevents/emitter.go
  cloudevents/emitter_test.go
  cmd/build_test.go
  cmd/create.go
  cmd/create_test.go
  cmd/delete_test.go
  cmd/emit.go
  cmd/info.go
  cmd/invoke.go
  cmd/repository_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/run_test.go
  config_test.go
  docker/creds/credentials_test.go
  docker/runner.go
  docker/runner_test.go
  docs/guides/commands.md
  function.go
  function_test.go
  instances.go
  invoke.go
  job.go
  knative/describer.go
  mock/describer.go
  mock/emitter.go
  mock/runner.go
  pkged.go
  repositories_test.go
  repository.go
  repository_test.go
  schema/func_yaml-schema.json
  template.go
  templates.go
  templates/go/cloudevents/manifest.yaml
  templates/go/http/manifest.yaml
  templates/python/cloudevents/manifest.yaml
  templates/quarkus/cloudevents/manifest.yaml
  templates/typescript/cloudevents/manifest.yaml
  templates_test.go
  test/_e2e/cmd_emit_test.go
  test/_e2e/cmd_invoke_test.go
  test/_e2e/update_templates/node/cloudevents/index.js
  testdata/repositories/customLanguagePackRepo/templates/manifestedRuntime/manifestedTemplate/manifest.yaml
Labels: kind/enhancement, lgtm, approved, size/XXL

#772 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#777 test: fix URL
  http/transport_test.go
Labels: lgtm, approved, size/XS

#779 fix: local cluster name collision
  hack/allocate.sh
  hack/delete.sh
Labels: kind/bug, size/S, lgtm, approved

#763 feat: delete pipeline and resources with `func delete`
  client.go
  client_int_test.go
  client_test.go
  cmd/delete.go
  k8s/persistent_volumes.go
  k8s/role_bidings.go
  k8s/secrets.go
  k8s/service_accounts.go
  knative/remover.go
  mock/pipelines_provider.go
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/resources.go
Labels: kind/enhancement, lgtm, approved, size/L

#780 chore: skip integration tests in upstream release scripts for now
  test/presubmit-tests.sh
Labels: size/S, lgtm, approved, kind/chore

#783 Update OWNERS
  OWNERS
Labels: size/S, lgtm, approved

#781 doc: `git add` before `commit` and `push` for on cluster builds
  docs/guides/on-cluster-build.md
Labels: lgtm, approved, size/XS

#785 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#787 chore: skip integration tests for now (#780)
  test/presubmit-tests.sh
Labels: size/S, lgtm, approved

#786 fix: error type-check condition
  docker/creds/credentials.go
Labels: lgtm, approved, size/XS

#788 fix: authentication check failure for gcr.io
  docker/creds/credentials.go
  docker/creds/credentials_test.go
Labels: lgtm, approved, size/XS

#789 fix: use domain qualified registry for springboot
  pkged.go
  templates/springboot/manifest.yaml
Labels: lgtm, approved, size/XS

#792 fix: use paketo base image for springboot
  pkged.go
  templates/springboot/manifest.yaml
Labels: lgtm, approved, size/XS

#793 backport: bug fixes for 0.21
  docker/creds/credentials.go
  docker/creds/credentials_test.go
  pkged.go
  templates/springboot/manifest.yaml
  test/presubmit-tests.sh
Labels: size/S, lgtm, approved

#790 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#797 chore: update Makefile and hack/release.sh to accept TAG
  Makefile
  hack/release.sh
Labels: lgtm, approved, size/XS

#799 chore: change TAG to ETAG to avoid stepping on toes
  Makefile
  hack/release.sh
Labels: lgtm, approved, size/XS
