Repository knative/func, pull requests merged in 2022-02, with the labels that each got.

#803 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#802 feat: completion --build flag of deploy sub-cmd
  cmd/completion_util.go
  cmd/deploy.go
  function_buildtype.go
Labels: size/S, lgtm, approved

#805 src: fix `func.yaml` schema
  function.go
  schema/func_yaml-schema.json
Labels: kind/bug, size/S, lgtm, approved

#806 Update installing_cli.md
  docs/installing_cli.md
Labels: lgtm, approved, size/XS

#810 chore: update boson builder image references
  templates/python/manifest.yaml
  templates/quarkus/cloudevents/manifest.yaml
  templates/quarkus/manifest.yaml
Labels: size/S, lgtm, approved

#812 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#807 Cleanup commands
  cmd/build.go
  cmd/completion.go
  cmd/config.go
  cmd/config_envs.go
  cmd/config_volumes.go
  cmd/create.go
  cmd/delete.go
  cmd/deploy.go
  cmd/func/main.go
  cmd/info.go
  cmd/invoke.go
  cmd/list.go
  cmd/repository.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/version.go
  plugin/plugin.go
Labels: lgtm, approved, size/XL

#815 Setting the default for language selector
  cmd/create.go
Labels: kind/bug, lgtm, approved, size/XS

#818 src: error-less ctors
  client_int_test.go
  cmd/build.go
  cmd/completion_util.go
  cmd/delete.go
  cmd/deploy.go
  cmd/info.go
  cmd/invoke.go
  cmd/list.go
  docker/pusher.go
  docker/pusher_test.go
  knative/deployer.go
  knative/describer.go
  knative/lister.go
  knative/remover.go
  pipelines/tekton/pipeplines_provider.go
Labels: lgtm, approved, size/L

#823 fix: don't fail info/invoke if eventing missing
  knative/describer.go
Labels: kind/bug, size/S, lgtm, approved

#824 Single common `fn.Client` factory for all commands
  cmd/build.go
  cmd/build_test.go
  cmd/client.go
  cmd/create.go
  cmd/create_test.go
  cmd/delete.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/info.go
  cmd/invoke.go
  cmd/list.go
  cmd/root.go
Labels: lgtm, approved, size/XL

#821 fix: defaults for prompt from flags then options
  cmd/create.go
  cmd/invoke.go
  cmd/root.go
Labels: kind/bug, lgtm, approved, size/M

#813 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#826 chore: bump node builder to latest
  pkged.go
  templates/node/manifest.yaml
Labels: lgtm, approved, size/XS

#828 Update guide for podman
  docs/guides/podman.md
Labels: lgtm, approved, size/XS

#831 chore: accommodate knative's go linter
  cmd/root_test.go
Labels: lgtm, approved, size/XS, kind/cleanup

#837 Fix checkum for github.com/tektoncd/cli
  go.sum
Labels: lgtm, approved, size/XS

#836 Fix podman guide
  docs/guides/podman.md
Labels: lgtm, approved, size/XS, kind/documentation

#841 build pkged.go directly from make target
  Makefile
  hack/update-pkger.sh
Labels: kind/bug, lgtm, approved, size/M

#845 Update python builder version
  pkged.go
  templates/python/cloudevents/manifest.yaml
Labels: lgtm, approved, size/XS

#846 chore: update manifest.yamls
  pkged.go
  templates/node/cloudevents/manifest.yaml
  templates/python/cloudevents/manifest.yaml
  templates/rust/cloudevents/manifest.yaml
  templates/springboot/cloudevents/manifest.yaml
  templates/typescript/cloudevents/manifest.yaml
Labels: kind/bug, lgtm, approved, size/M

#843 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/XS

#825 Custom improvements for OpenShift
  cmd/build.go
  cmd/client.go
  cmd/deploy.go
  cmd/root.go
  http/transport.go
  openshift/openshift.go
  openshift/openshift_test.go
Labels: lgtm, approved, size/L

#862 fix: minor typos in docs
  docs/guides/commands.md
  docs/guides/golang.md
  docs/guides/language-packs.md
  docs/guides/nodejs.md
  docs/guides/on-cluster-build.md
  docs/guides/python.md
  docs/guides/quarkus.md
  docs/guides/typescript.md
  templates/node/http/index.js
  templates/typescript/http/src/index.ts
Labels: lgtm, approved, size/M

#863 test: url for invoke test
  test/_e2e/cmd_invoke_test.go
Labels: size/S, lgtm, approved

#860 Windows unit test fixes
  Makefile
  docker/creds/credentials.go
  docker/creds/credentials_test.go
  docker/docker_client_test.go
  repositories.go
  repositories_test.go
  repository.go
  templates_test.go
  testing/testing.go
Labels: lgtm, approved, size/M

#844 added git related flags for remote builds
  client.go
  cmd/deploy.go
  cmd/deploy_test.go
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, size/L

#870 Mark OpenShift test as an integration test
  openshift/openshift.go
  openshift/openshift_test.go
Labels: size/S, lgtm, approved
