Repository knative/func, pull requests merged in 2022-06, with the labels that each got.

#1017 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1026 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1034 chore(release): 0.24.0
  CHANGELOG.md
  version.txt
Labels: lgtm, approved, size/M

#1035 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1028 feat: pack builder images individually configurable
  buildpacks/builder.go
  buildpacks/builder_test.go
  client_int_test.go
  cmd/build.go
  cmd/client.go
  pipelines/tekton/resources.go
Labels: kind/enhancement, lgtm, approved, size/L

#1032 fix: increase timeout when testing int cluster availability
  hack/test.sh
Labels: kind/bug, size/S, lgtm, approved

#1033 feat: builder images map migration
  client.go
  client_test.go
  cmd/build.go
  cmd/completion_util.go
  cmd/root.go
  function.go
  function_migrations.go
  function_migrations_unit_test.go
  schema/func_yaml-schema.json
  template.go
  testdata/migrations/v0.23.0-customized/func.yaml
  testdata/migrations/v0.23.0/func.yaml
Labels: kind/enhancement, lgtm, approved, size/L

#1040 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1043 chore: fix timeout in test
  hack/test.sh
Labels: lgtm, approved, size/XS, kind/chore

#1042 feat: use JSON object as default message for the invoke sub-command
  invoke.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1030 Better error message for podman auto service
  docker/docker_client.go
  docker/docker_client_linux_test.go
Labels: lgtm, approved, size/M

#1046 chore: print correct logs for failed PipelineRun
  pipelines/tekton/pipeplines_provider.go
Labels: lgtm, approved, size/XS

#1041 fix: map invoke format flag
  cmd/invoke.go
Labels: kind/bug, lgtm, approved, size/XS

#1048 remove third-party echo test from CI
  .github/workflows/test-integration.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1051 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1052 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1056 Fix premature Close() of docker client
  s2i/builder.go
Labels: size/S, lgtm, approved

#1031 feat: on run, build only when filesystem changed
  client.go
  client_test.go
  cmd/deploy.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/run_test.go
  function.go
  job.go
Labels: kind/enhancement, lgtm, approved, size/L

#1063 fix: s2i build as-dockerfile mode
  s2i/builder.go
  s2i/builder_test.go
  s2i/docker_client_wrapper.go
  s2i/testData/builder.tar
Labels: kind/bug, lgtm, approved, size/XL

#1065 feat: add all build flags to deploy
  client.go
  cmd/deploy.go
  test/e2e_lifecycle_tests.sh
Labels: kind/enhancement, lgtm, approved, size/M

#1066 fix: premature Close() of docker client
  .codecov.yaml
  .gitattributes
  buildpacks/builder.go
  docker/close_guarding_client.go
  docker/docker_client.go
  docker/zz_close_guarding_client_generated.go
  go.mod
  s2i/builder.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1069 doc: fix some func.yaml fields
  docs/reference/func_yaml.md
Labels: lgtm, approved, size/M, kind/documentation

#1070 fix: workaround for missing func.yaml on tekton step result
  pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
Labels: kind/bug, lgtm, approved, size/M

#1068 fix: minor improvements for s2i build
  s2i/builder.go
Labels: size/S, lgtm, approved

#1071 fix: do not prompt user if --build diabled
  cmd/deploy.go
Labels: lgtm, approved, size/XS

#1072 feat: add echo for springboot http template
  templates/springboot/http/README.md
  templates/springboot/http/src/main/java/functions/CloudFunctionApplication.java
  templates/springboot/http/src/test/java/functions/EchoCaseFunctionTest.java
  test/_e2e/trigger_http_test.go
  zz_filesystem_generated.go
Labels: lgtm, approved, size/M

#1073 doc: add closing mark
  docs/reference/commands.md
Labels: lgtm, approved, size/XS, kind/documentation

#1082 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1078 feat: introduce echo return for Python http template
  templates/python/http/func.py
  templates/python/http/test_func.py
  test/_e2e/trigger_http_test.go
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/M

#1081 Explicit define builder for Remote and Config e2e tests
  test/_e2e/cmd_build_test.go
  test/_e2e/cmd_config_envs_test.go
  test/_e2e/cmd_config_labels_test.go
  test/_e2e/cmd_config_volumes_test.go
  test/_e2e/config.go
  test/_e2e/e2e_remote_repository_test.go
  test/_e2e/func_test_proj.go
Labels: size/S, lgtm, approved, kind/cleanup

#1088 feat: check valid runtimes for on cluster build
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/validate.go
  pipelines/tekton/validate_test.go
Labels: lgtm, approved, size/L

#1092 Preserve func.yaml for Quarkus BP build
  pipelines/tekton/validate.go
  pipelines/tekton/validate_test.go
  templates/quarkus/cloudevents/README.md
  templates/quarkus/http/README.md
  templates/quarkus/manifest.yaml
  zz_filesystem_generated.go
Labels: size/S, lgtm, approved
