Repository knative/func, pull requests merged in 2022-08, with the labels that each got.

#1144 fix: use space prefix for deploy output text
  client.go
  test/_e2e/cmd_deploy_test.go
Labels: size/S, lgtm, approved

#1153 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/M, skip-review

#1154 doc: fix doc reference on nodejs template
  templates/node/cloudevents/index.js
  templates/node/http/index.js
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1150 fixup: change period 15min -> 4hrs
  .github/workflows/update-quarkus-platform.yaml
Labels: lgtm, approved, size/XS

#1155 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1156 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1134 feat: templates list command
  cmd/languages.go
  cmd/root.go
  cmd/templates.go
  cmd/templates_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1160 Added binary builds for platforms ppc64le and s390x
  .github/workflows/ci.yaml
  Makefile
  hack/release.sh
Labels: kind/enhancement, size/S, lgtm, approved

#1162 remove duplicate cmd.AddCommand(NewLanguagesCmd) at root.go
  cmd/root.go
Labels: kind/bug, lgtm, approved, size/XS

#1161 fix link to reference/command.txt
  docs/function-developers/developers_guide.md
  docs/function-developers/golang.md
  docs/function-developers/nodejs.md
  docs/function-developers/python.md
  docs/function-developers/quarkus.md
  docs/function-developers/typescript.md
Labels: size/S, lgtm, approved, kind/documentation

#1163 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1168 fix: ensure registry in func.yaml is respected
  cmd/build.go
  cmd/build_test.go
Labels: kind/bug, lgtm, approved, size/M

#1165 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1171 quarkus test template change to remove package type property
  test/_e2e/update_templates/quarkus/http/src/main/resources/application.properties
Labels: lgtm, approved, size/XS, kind/cleanup

#1170 chore: Use JS for script instead of shell
  .github/workflows/update-quarkus-platform.yaml
  hack/update-quarkus-platform.js
  hack/update-quarkus-platform.sh
Labels: lgtm, approved, size/L

#1174 On cluster build: support Build Envs
  function_envs.go
  function_envs_unit_test.go
  pipelines/tekton/resources.go
  pipelines/tekton/tasks.go
Labels: kind/enhancement, lgtm, approved, size/L

#1178 chore: add some milliseconds in client tests
  client_test.go
Labels: lgtm, approved, size/XS, kind/chore

#1177 chore: adjust codecov configuration
  .codecov.yaml
Labels: size/S, lgtm, approved, kind/chore

#1179 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1183 chore: update springboot dependencies
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
  zz_filesystem_generated.go
Labels: kind/enhancement, size/S, lgtm, approved

#1184 chore: use dot as path default rather than absolute path
  cmd/build.go
  cmd/config.go
  cmd/delete.go
  cmd/deploy.go
  cmd/format.go
  cmd/info.go
  cmd/invoke.go
  cmd/root.go
  cmd/run.go
  docs/reference/commands.txt
Labels: lgtm, approved, size/L

#1180 builder short name constants etc throughout
  builders/builders.go
  builders/builders_test.go
  buildpacks/builder.go
  buildpacks/builder_test.go
  client_test.go
  cmd/build.go
  cmd/build_test.go
  cmd/completion_util.go
  cmd/deploy.go
  docs/reference/commands.txt
  function_builder.go
  function_builder_unit_test.go
  pipelines/tekton/resources.go
  s2i/builder.go
  s2i/builder_test.go
  test/_e2e/cmd_config_envs_test.go
  test/_e2e/cmd_config_labels_test.go
  test/_e2e/cmd_config_volumes_test.go
  test/_e2e/e2e_remote_repository_test.go
Labels: lgtm, approved, size/XL, kind/chore

#1191 feat: S2I strategy for on cluster build
  cmd/client.go
  docs/reference/on_cluster_build.md
  pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pipelines/tekton/resources.go
  pipelines/tekton/resources_test.go
  pipelines/tekton/tasks.go
  pipelines/tekton/validate.go
  pipelines/tekton/validate_test.go
  s2i/builder_test.go
Labels: kind/enhancement, lgtm, approved, size/XL

#1189 fix: performance of template loading
  repository.go
Labels: size/S, lgtm, approved

#1196 Fix a broken link in docs
  docs/function-developers/golang.md
  docs/function-developers/nodejs.md
  docs/function-developers/python.md
  docs/function-developers/quarkus.md
  docs/function-developers/typescript.md
Labels: size/S, lgtm, approved, kind/documentation

#1195 chore(release): 0.26.0
  CHANGELOG.md
  version.txt
Labels: lgtm, approved, size/M, kind/chore

#1198 fix: trailing white spaces in genrated docs
  docs/generator/main.go
  docs/reference/func_create.md
  docs/reference/func_templates.md
Labels: size/S, lgtm, approved

#1200 fix: on cluster builds when buildEnvs contains only one build environment
  pipelines/tekton/resources.go
Labels: kind/bug, lgtm, approved, size/XS

#1201 chore: update rust dependencies
  templates/rust/cloudevents/Cargo.lock
  templates/rust/cloudevents/Cargo.toml
  templates/rust/http/Cargo.lock
  templates/rust/http/Cargo.toml
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/L

#1202 fix: flags more consistent between build/deploy
  cmd/deploy.go
Labels: kind/bug, lgtm, approved, size/XS

#1203 doc: update generated docs for 'deploy'
  docs/reference/func_deploy.md
Labels: lgtm, approved, size/XS, kind/documentation

#1207 use the correct sample repository link in command usage
  cmd/languages.go
  cmd/templates.go
  docs/reference/func_languages.md
  docs/reference/func_templates.md
Labels: kind/bug, lgtm, approved, size/XS

#1209 chore: update .gitignore (#215)
  .gitignore
Labels: size/S, lgtm, approved

#1204 fix: check for `--image` flag in build command
  cmd/build.go
  cmd/build_test.go
Labels: kind/bug, lgtm, approved, size/M
