Repository knative/func, pull requests merged in 2023-07, with the labels that each got.

#1847 [release-1.10] chore: update Quarkus platform version to 3.2.0.Final (#1844)
  generate/zz_filesystem_generated.go
  templates/quarkus/cloudevents/pom.xml
  templates/quarkus/cloudevents/src/test/java/functions/NativeFunctionIT.java
  templates/quarkus/http/pom.xml
  templates/quarkus/http/src/test/java/functions/NativeFunctionIT.java
Labels: size/S, lgtm, approved

#1850 [release-1.10]: src: interstitial commit version (#1817)
  Makefile
  cmd/func/main.go
  cmd/root.go
  cmd/root_test.go
Labels: lgtm, approved, size/M

#1854 doc: list demos in the Readme
  README.md
Labels: lgtm, approved, size/XS

#1855 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, size/XS, skip-review

#1843 feat: use Tekton Resolvers for a standard on cluster build
  docs/building-functions/on_cluster_build.md
  go.mod
  go.sum
  hack/tekton.sh
  pkg/builders/builders.go
  pkg/k8s/manifestival.go
  pkg/pipelines/tekton/pipelines_pac_provider.go
  pkg/pipelines/tekton/pipelines_pac_provider_test.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/resources.go
  pkg/pipelines/tekton/resources_test.go
  pkg/pipelines/tekton/tasks.go
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/templates_pack.go
  pkg/pipelines/tekton/templates_s2i.go
  pkg/pipelines/tekton/templates_test.go
  third_party/VENDOR-LICENSE/github.com/manifestival/client-go-client/LICENSE
  third_party/VENDOR-LICENSE/github.com/manifestival/manifestival/LICENSE
  third_party/VENDOR-LICENSE/sigs.k8s.io/controller-runtime/pkg/client/apiutil/LICENSE
  vendor/github.com/manifestival/client-go-client/.gitignore
  vendor/github.com/manifestival/client-go-client/LICENSE
  vendor/github.com/manifestival/client-go-client/README.md
  vendor/github.com/manifestival/client-go-client/client.go
  vendor/github.com/manifestival/client-go-client/pkg/dynamic/interface.go
  vendor/github.com/manifestival/client-go-client/pkg/dynamic/rest_mapper_resource_interface.go
  vendor/github.com/manifestival/client-go-client/pkg/dynamic/unsafe_resource_interface.go
  vendor/github.com/manifestival/manifestival/.gitignore
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/LICENSE
  vendor/github.com/manifestival/manifestival/README.md
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/fake/client.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/internal/overlay/overlay.go
  vendor/github.com/manifestival/manifestival/internal/patch/patch.go
  vendor/github.com/manifestival/manifestival/internal/sources/path.go
  vendor/github.com/manifestival/manifestival/internal/sources/yaml.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/source.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
Labels: lgtm, approved, size/XXL

#1860 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1837 feat: default ADDRESS env var on deploy
  pkg/knative/deployer.go
Labels: kind/enhancement, lgtm, approved, size/M

#1862 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1836 src: update func-runtime-go and dapr
  generate/zz_filesystem_generated.go
  hack/binaries.sh
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/go.sum
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/go.sum
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
Labels: lgtm, approved, size/M, kind/cleanup

#1873 chore: bump faas-js-runtime and cloudevents for node & TS
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  generate/zz_filesystem_generated.go
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
Labels: lgtm, approved, size/XXL, kind/chore

#1874 fix: host builder retry error
  pkg/oci/builder.go
  pkg/oci/containerize.go
  pkg/scaffolding/scaffold.go
Labels: kind/bug, size/S, lgtm, approved

#1884 fix: verbose default not applied
  cmd/root.go
Labels: kind/bug, lgtm, approved, size/XS

#1885 fix: resolve tkn task spec locally
  go.mod
  pkg/pipelines/tekton/templates.go
Labels: lgtm, approved, size/M

#1857 src: Use jobs not plain pods for auxiliary tasks
  pkg/k8s/dialer.go
  pkg/k8s/persistent_volumes.go
  pkg/k8s/security_context.go
Labels: lgtm, approved, size/L

#1886 fix: deploy warning about insecure defaults (#1851)
  pkg/knative/deployer.go
Labels: size/S, lgtm, approved, needs-ok-to-test

#1882 feat: support external deps for host runs
  cmd/run.go
  pkg/functions/runner.go
Labels: size/S, lgtm, approved

#1879 src: update func go runtime dep
  Makefile
  generate/zz_filesystem_generated.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/go.sum
  templates/go/scaffolding/instanced-cloudevents/main.go
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/instanced-http/main.go
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/go.sum
  templates/go/scaffolding/static-cloudevents/main.go
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
  templates/go/scaffolding/static-http/main.go
Labels: lgtm, approved, size/M, kind/cleanup

#1889 Fix pod security context
  cmd/client.go
  pkg/config/config.go
  pkg/http/openshift.go
  pkg/http/openshift_test.go
  pkg/k8s/dialer.go
  pkg/k8s/openshift.go
  pkg/k8s/persistent_volumes.go
  pkg/k8s/security_context.go
  pkg/openshift/metadata.go
  test/common/config.go
Labels: lgtm, approved, size/L

#1892 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1891 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#1890 Fix failing concurrent test on Windows
  pkg/oci/builder.go
  pkg/oci/builder_test.go
Labels: size/S, lgtm, approved

#1445 allowing on cluster build for go runtime
  docs/building-functions/on_cluster_build.md
  pkg/pipelines/tekton/pipelines_pac_provider.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/validate.go
  pkg/pipelines/tekton/validate_test.go
Labels: lgtm, approved, size/M, kind/cleanup
