Repository knative/func, pull requests merged in 2023-01, with the labels that each got.

#1471 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1482 fix: `deploy` with autoscaling options specified
  client_int_test.go
  knative/deployer.go
Labels: kind/bug, lgtm, approved, size/M

#1490 chore: update BP lifecycle image to 0.15.3
  buildpacks/builder.go
Labels: lgtm, approved, size/XS

#1486 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1494 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1495 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1468 deps(node,typescript): update dependencies
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
  zz_filesystem_generated.go
Labels: lgtm, approved, size/L, kind/chore

#1496 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1485 chore: refactor commands help to use templates
  cmd/build.go
  cmd/config.go
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_volumes.go
  cmd/create.go
  cmd/delete.go
  cmd/deploy.go
  cmd/describe.go
  cmd/invoke.go
  cmd/languages.go
  cmd/list.go
  cmd/repository.go
  cmd/root.go
  cmd/run.go
  cmd/templates.go
  cmd/templates/template_engine.go
  cmd/templates/templates.go
  cmd/version.go
  docs/generator/main.go
  docs/reference/func_build.md
  docs/reference/func_create.md
  docs/reference/func_delete.md
  docs/reference/func_describe.md
Labels: lgtm, approved, size/L, kind/chore

#1497 docs: update language pack docs for builderImages
  docs/language-packs/language-pack-contract.md
Labels: size/S, lgtm, approved, kind/documentation

#1500 fix: create command help text
  cmd/create.go
Labels: kind/bug, lgtm, approved, size/M

#1502 Update Spring Boot to 2.7.7
  docs/function-templates/springboot.md
  templates/springboot/cloudevents/README.md
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/README.md
  templates/springboot/http/pom.xml
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/L, kind/documentation

#1510 fix: improve error message for missing registry name
  client.go
Labels: kind/enhancement, lgtm, approved, size/XS

#1511 fix: e2e springboot error
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
  zz_filesystem_generated.go
Labels: kind/bug, size/S, lgtm, approved

#1507 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_defaults.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1512 fix: envvar parsing for pack tekton task
  pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
Labels: kind/bug, lgtm, approved, size/XS

#1514 fix: on cluster build - fix url in the output msg
  pipelines/tekton/pipeplines_provider.go
Labels: lgtm, approved, size/XS

#1516 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1519 fix: allow trailing path flag
  cmd/root.go
  cmd/root_test.go
Labels: kind/bug, size/S, lgtm, approved

#1517 rebuild docs
  docs/reference/func_build.md
  docs/reference/func_create.md
Labels: lgtm, approved, size/XS, kind/cleanup

#1520 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1524 e2e tests log stdout and stderr
  test/common/cmd.go
  test/common/gitserver.go
  test/e2e/cmd_invoke_test.go
  test/oncluster/scenario_basic_test.go
  test/oncluster/scenario_context-dir_test.go
  test/oncluster/scenario_from-cli_test.go
  test/oncluster/scenario_revision_test.go
Labels: kind/enhancement, lgtm, approved, size/M

#1523 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1527 chore(ci): update java version
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS
