Repository knative/func, pull requests merged in 2023-09, with the labels that each got.

#1950 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1959 chore: dump cluster logs in tests
  .github/workflows/test-e2e-oncluster-runtime.yaml
Labels: size/S, lgtm, approved

#1967 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1971 Use our own s2i image
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
Labels: lgtm, approved, size/XS

#1968 chore: better JSON Schema
  pkg/functions/function.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/XS

#1972 Make func image multiarch
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#1974 fix: use current func image in tests
  .github/workflows/ci.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-integration.yaml
  hack/allocate.sh
  hack/create-testing-func-image.sh
Labels: size/S, lgtm, approved

#1976 chore: use local registry in test
  .github/workflows/ci.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-integration.yaml
  hack/allocate.sh
  hack/create-testing-func-image.sh
  hack/patch-s2i-task.sh
  hack/setup-testing-images.sh
  pkg/k8s/dialer.go
Labels: lgtm, approved, size/M

#1963 test: consider FUNC_BUILDER env var for e2e oncluter tests
  .github/workflows/test-e2e-oncluster-runtime.yaml
  test/oncluster/scenario_runtime_test.go
Labels: size/S, lgtm, approved, kind/cleanup

#1977 adding test for run without container
  test/e2e/scenario_no_container_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#1975 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1987 chore: update maven wrapper in Quarkus template
  generate/zz_filesystem_generated.go
  templates/quarkus/cloudevents/.mvn/wrapper/MavenWrapperDownloader.java
  templates/quarkus/cloudevents/.mvn/wrapper/maven-wrapper.properties
  templates/quarkus/http/.mvn/wrapper/MavenWrapperDownloader.java
  templates/quarkus/http/.mvn/wrapper/maven-wrapper.properties
Labels: lgtm, approved, size/L

#1988 chore: use ./mvnw not mvn in tests
  Makefile
Labels: lgtm, approved, size/XS

#1992 chore: parallelize cluster allocate script
  hack/allocate.sh
Labels: size/S, lgtm, approved
