Repository knative/func, pull requests merged in 2023-04, with the labels that each got.

#1664 fix: Rust template project listen on 0.0.0.0
  generate/zz_filesystem_generated.go
  templates/rust/cloudevents/src/main.rs
  templates/rust/http/src/main.rs
Labels: lgtm, approved, size/XS

#1665 [Release 1.9] fix: actix listent on 0.0.0.0 (#1664)
  templates/rust/cloudevents/src/main.rs
  templates/rust/http/src/main.rs
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XS

#1657 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1598 feat: add pvc-size flag to deploy command (#851)
  cmd/deploy.go
  docs/reference/func_deploy.md
  pkg/functions/function.go
  pkg/pipelines/tekton/defaults.go
  pkg/pipelines/tekton/pipelines_pac_provider.go
  pkg/pipelines/tekton/pipeplines_provider.go
  pkg/pipelines/tekton/pipeplines_provider_test.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/L

#1669 doc: refer specific verision of Tekton not latest
  docs/building-functions/on_cluster_build.md
  hack/tekton.sh
Labels: size/S, lgtm, approved

#1667 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1670 fix: template flag completion
  cmd/completion_util.go
Labels: size/S, lgtm, approved

#1673 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
Labels: size/L, skip-review

#1674 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1672 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1677 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1679 fix: increase connection timeouts
  pkg/functions/invoke.go
  pkg/http/transport.go
Labels: lgtm, approved, size/XS

#1678 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#1681 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1684 test: extend filesystem tests
  pkg/filesystem/filesystem_test.go
  pkg/filesystem/testdata/fs.zip
  pkg/filesystem/testdata/repo.git/HEAD
  pkg/filesystem/testdata/repo.git/config
  pkg/filesystem/testdata/repo.git/description
  pkg/filesystem/testdata/repo.git/hooks/applypatch-msg.sample
  pkg/filesystem/testdata/repo.git/hooks/commit-msg.sample
  pkg/filesystem/testdata/repo.git/hooks/fsmonitor-watchman.sample
  pkg/filesystem/testdata/repo.git/hooks/post-update.sample
  pkg/filesystem/testdata/repo.git/hooks/pre-applypatch.sample
  pkg/filesystem/testdata/repo.git/hooks/pre-commit.sample
  pkg/filesystem/testdata/repo.git/hooks/pre-merge-commit.sample
  pkg/filesystem/testdata/repo.git/hooks/pre-push.sample
  pkg/filesystem/testdata/repo.git/hooks/pre-rebase.sample
  pkg/filesystem/testdata/repo.git/hooks/pre-receive.sample
  pkg/filesystem/testdata/repo.git/hooks/prepare-commit-msg.sample
  pkg/filesystem/testdata/repo.git/hooks/push-to-checkout.sample
  pkg/filesystem/testdata/repo.git/hooks/update.sample
  pkg/filesystem/testdata/repo.git/info/exclude
  pkg/filesystem/testdata/repo.git/objects/73/2af9ed648c3488e3b314ab1b3f6ee65cac5161
  pkg/filesystem/testdata/repo.git/objects/7e/6db979cdd45dff20bdde1bd3233a99acd9110c
  pkg/filesystem/testdata/repo.git/objects/8b/3ca73a54c5388fb90004d927bdabfd498b1a89
  pkg/filesystem/testdata/repo.git/objects/98/0a0d5f19a64b4b30a87d4206aade58726b60e3
  pkg/filesystem/testdata/repo.git/objects/a5/162f80d4a6782b7cb2a0a197f834e683cb9eb1
  pkg/filesystem/testdata/repo.git/refs/heads/master
  pkg/filesystem/testdata/root/a/hello.lnk
  pkg/filesystem/testdata/root/a/hello.txt
Labels: lgtm, approved, size/XXL

#1654 docs: add preliminary document for function lifecycles
  docs/function-templates/lifecycle.md
Labels: lgtm, approved, size/M, kind/documentation

#1682 feat: custom health checks for node and typescript
  docs/reference/func_config.md
  generate/zz_filesystem_generated.go
  templates/node/cloudevents/README.md
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/README.md
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/README.md
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/README.md
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
  templates/typescript/http/src/index.ts
Labels: kind/enhancement, lgtm, approved, size/XXL

#1688 feat: track go template sumfiles
  .gitignore
Labels: lgtm, approved, size/XS, kind/cleanup

#1692 fix: remove preparsing flag error messages
  cmd/root.go
Labels: kind/bug, lgtm, approved, size/XS

#1694 src: rename Instance to InstanceRefs
  pkg/functions/client.go
  pkg/functions/instances.go
  pkg/functions/instances_test.go
Labels: size/S, lgtm, approved, kind/cleanup

#1691 fix: building resets image digest
  cmd/deploy.go
Labels: kind/bug, lgtm, approved, size/XS

#1698 src: move template struct definition
  pkg/functions/repository.go
  pkg/functions/template.go
Labels: lgtm, approved, size/M, kind/cleanup

#1700 src: cleanup templates.Get
  pkg/functions/templates.go
Labels: lgtm, approved, size/M, kind/cleanup

#1704 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#1705 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#1685 feat: specify create time for image built with buildpacks
  cmd/build.go
  cmd/deploy.go
  pkg/builders/buildpacks/builder.go
Labels: kind/enhancement, lgtm, approved, size/M

#1701 src: Envs type
  cmd/deploy_test.go
  pkg/functions/function.go
  pkg/functions/function_envs.go
  pkg/functions/repository_test.go
  pkg/functions/templates_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#1714 fix: Quarkus template Integration Tests
  generate/zz_filesystem_generated.go
  templates/quarkus/cloudevents/src/test/java/functions/NativeFunctionIT.java
  templates/quarkus/http/src/test/java/functions/NativeFunctionIT.java
Labels: lgtm, approved, size/XS

#1713 fix: PaC not working with dot git suffixed URLs
  pkg/git/git.go
  pkg/git/git_test.go
Labels: kind/bug, lgtm, approved, size/XS
