Repository knative/func, pull requests merged in 2023-12, with the labels that each got.

#2100 chore: update Go lint
  Makefile
Labels: lgtm, approved, size/XS

#2098 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2101 fix: update Quarkus template readme
  generate/zz_filesystem_generated.go
  templates/quarkus/cloudevents/README.md
  templates/quarkus/http/README.md
Labels: lgtm, approved, size/XS

#2105 fix: replace git-urls with patched fork
  go.mod
  go.sum
  pkg/functions/function_git.go
  third_party/VENDOR-LICENSE/github.com/chainguard-dev/git-urls/LICENSE
Labels: lgtm, approved, size/XS

#2106 chore: include Quarkus BP in our builders
  go.mod
  go.sum
  hack/update-builder.go
  third_party/VENDOR-LICENSE/github.com/Masterminds/semver/v3/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/buildpacks/libcnb/LICENSE
  third_party/VENDOR-LICENSE/github.com/buildpacks/libcnb/NOTICE
  third_party/VENDOR-LICENSE/github.com/mitchellh/hashstructure/v2/LICENSE
  third_party/VENDOR-LICENSE/github.com/onsi/gomega/types/LICENSE
  third_party/VENDOR-LICENSE/github.com/paketo-buildpacks/libpak/LICENSE
  third_party/VENDOR-LICENSE/github.com/paketo-buildpacks/libpak/NOTICE
Labels: lgtm, approved, size/XL

#2103 feat: func-go v0.19.0
  generate/zz_filesystem_generated.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/go.sum
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/go.sum
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
Labels: lgtm, approved, size/M
