Repository knative/func, pull requests merged in 2023-03, with the labels that each got.

#1564 cli help text updates and flags cleanup
  cmd/build.go
  cmd/completion.go
  cmd/config.go
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_volumes.go
  cmd/create.go
  cmd/delete.go
  cmd/deploy.go
  cmd/describe.go
  cmd/invoke.go
  cmd/languages.go
  cmd/list.go
  cmd/repository.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/templates.go
  cmd/templates/template_engine_test.go
  cmd/templates/templates.go
  cmd/version.go
  docs/reference/func.md
  docs/reference/func_build.md
  docs/reference/func_completion.md
  docs/reference/func_config.md
  docs/reference/func_config_envs.md
  docs/reference/func_config_envs_add.md
  docs/reference/func_config_envs_remove.md
  docs/reference/func_config_labels.md
  docs/reference/func_config_labels_add.md
  docs/reference/func_config_labels_remove.md
  docs/reference/func_config_volumes.md
  docs/reference/func_config_volumes_add.md
  docs/reference/func_config_volumes_remove.md
  docs/reference/func_create.md
  docs/reference/func_delete.md
  docs/reference/func_deploy.md
  docs/reference/func_describe.md
  docs/reference/func_invoke.md
  docs/reference/func_languages.md
  docs/reference/func_list.md
  docs/reference/func_repository.md
  docs/reference/func_repository_add.md
  docs/reference/func_repository_list.md
  docs/reference/func_repository_remove.md
  docs/reference/func_repository_rename.md
  docs/reference/func_run.md
  docs/reference/func_templates.md
  docs/reference/func_version.md
Labels: lgtm, approved, size/XL, kind/cleanup

#1592 chore: move prompts to a separate package
  cmd/client.go
  cmd/deploy.go
  cmd/prompt/prompt.go
  cmd/prompt/prompt_test.go
Labels: lgtm, approved, size/L

#1597 docs: add note about not supported on cluster build runtimes.
  docs/building-functions/on_cluster_build.md
Labels: lgtm, approved, size/XS

#1602 bug: Correctly format Node.js code
  generate/zz_filesystem_generated.go
  templates/node/http/index.js
Labels: kind/bug, lgtm, approved, size/XS

#1591 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1606 chore: better output for PaC
  pkg/pipelines/tekton/pipelines_pac_provider.go
Labels: lgtm, approved, size/XS

#1607 Change 'create' help text to indicate mandatory language option
  cmd/create.go
  docs/reference/func_create.md
Labels: size/S, lgtm, approved, kind/documentation

#1603 chore: coverage for e2e tests
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .gitignore
  Makefile
  test/e2e_extended_tests.sh
  test/e2e_lifecycle_tests.sh
  test/e2e_oncluster_tests.sh
Labels: lgtm, approved, size/M

#1608 fix: build stamp computation
  pkg/functions/client.go
Labels: kind/bug, size/S, lgtm, approved

#1611 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#1612 fix: node s2i build when node_modules present
  pkg/builders/s2i/builder.go
  pkg/builders/s2i/builder_test.go
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pkg/pipelines/tekton/pipeplines_provider.go
Labels: kind/bug, lgtm, approved, size/M

#1613 docs: update broken links in docs to command.txt and command.md
  docs/function-templates/golang.md
  docs/function-templates/nodejs.md
  docs/function-templates/python.md
  docs/function-templates/quarkus.md
  docs/function-templates/typescript.md
  docs/language-packs/language-pack-contract.md
  docs/reference/func_yaml.md
Labels: size/S, lgtm, approved

#1616 chore: more tests on push to main
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/M

#1604 feat: support flags for `func config git set` command
  cmd/config_git_set.go
  cmd/deploy.go
Labels: kind/enhancement, lgtm, approved, size/M

#1618 fix: failing CI
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#1614 Include --builder option on func run command
  cmd/run.go
  cmd/run_test.go
  docs/reference/func_run.md
Labels: lgtm, approved, size/M, kind/api-change

#1621 chore: properly implement `--config*` flags for `func config git set`
  cmd/config_git_set.go
Labels: kind/enhancement, size/S, lgtm, approved

#1629 fix: TCP+TLS docker daemon connection
  pkg/docker/docker_client.go
Labels: lgtm, approved, size/M

#1615 e2e tests restructuring / refactoring
  .github/workflows/test-e2e-runtime.yaml
  Makefile
  test/common/cmd.go
  test/common/config.go
  test/common/gitserver.go
  test/common/iteractivecmd.go
  test/common/knative.go
  test/common/knfunc.go
  test/common/outcleaner.go
  test/common/readycheck.go
  test/e2e/cmd_build_test.go
  test/e2e/cmd_create_test.go
  test/e2e/cmd_delete_test.go
  test/e2e/cmd_deploy_test.go
  test/e2e/cmd_info_test.go
  test/e2e/cmd_invoke_test.go
  test/e2e/cmd_list_test.go
  test/e2e/e2e_functions_test.go
  test/e2e/e2e_remote_repository_test.go
  test/e2e/func_test_proj.go
  test/e2e/main_test.go
  test/e2e/scenario_config-envs_test.go
  test/e2e/scenario_config-labels_test.go
  test/e2e/scenario_config-volumes_test.go
  test/e2e/scenario_extended_flow_test.go
  test/e2e/scenario_remote-repository_test.go
  test/e2e/scenario_runtime-cloudevents_test.go
  test/e2e/scenario_runtime-http_test.go
  test/e2e/shell_cmd_runner.go
  test/e2e/trigger_events_test.go
  test/e2e/trigger_http_test.go
  test/e2e/update_templates/go/http/handle.go
  test/e2e/update_templates/node/cloudevents/index.js
  test/e2e/update_templates/node/http/index.js
  test/e2e/update_templates/python/http/func.py
  test/e2e/update_templates/quarkus/http/src/main/java/functions/Function.java
  test/e2e/update_templates/springboot/http/src/main/java/functions/CloudFunctionApplication.java
  test/e2e/update_templates/typescript/http/src/index.ts
  test/e2e/update_test.go
  test/e2e_extended_tests.sh
  test/e2e_lifecycle_tests.sh
  test/oncluster/scenario_basic_test.go
  test/oncluster/scenario_context-dir_test.go
  test/oncluster/scenario_from-cli-local_test.go
  test/oncluster/scenario_from-cli_test.go
  test/oncluster/scenario_revision_test.go
  test/oncluster/scenario_runtime_test.go
  test/testhttp/testhttp.go
Labels: lgtm, approved, size/XXL, kind/cleanup

#1631 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1634 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1633 Descriptions in JSON Schema
  go.mod
  go.sum
  schema/func_yaml-schema.json
  schema/generator/main.go
  vendor/github.com/alecthomas/jsonschema/.golangci.yml
  vendor/github.com/alecthomas/jsonschema/.travis.yml
  vendor/github.com/alecthomas/jsonschema/README.md
  vendor/github.com/alecthomas/jsonschema/comment_extractor.go
  vendor/github.com/alecthomas/jsonschema/reflect.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#1641 fix: s2i python build on Windows
  pkg/builders/s2i/builder.go
Labels: kind/bug, lgtm, approved, size/XS

#1644 Pick s2i build fix
  s2i/builder.go
Labels: lgtm, approved, size/XS

#1636 feat: PAC - dynamically generate Pipeline target branch
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/templates_pack.go
  pkg/pipelines/tekton/templates_s2i.go
Labels: kind/enhancement, size/S, lgtm, approved

#1638 feat: PAC - add possibility to specify a Git provider
  cmd/config_git_set.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/pipelines/metadata.go
  pkg/pipelines/tekton/pipelines_pac_provider.go
  pkg/pipelines/tekton/resources_pac.go
Labels: kind/enhancement, lgtm, approved, size/L

#1645 fix: pre-compile mock binaries instead of 'go run' in tests
  pkg/testing/testing.go
Labels: size/S, lgtm, approved

#1648 style: fix lint error
  pkg/docker/creds/credentials.go
Labels: lgtm, approved, size/XS

#1630 feat: Minimal initial func.yaml
  pkg/functions/function.go
  pkg/functions/function_envs.go
  pkg/functions/function_volumes.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/M

#1653 chore: update lifecycle image to v0.16.1
  pkg/builders/buildpacks/builder.go
Labels: lgtm, approved, size/XS

#1652 chore: fixup release.sh script
  hack/release.sh
Labels: lgtm, approved, size/XS, kind/chore

#1656 chore: adjust shell script quotes
  hack/release.sh
Labels: lgtm, approved, size/XS, kind/chore

#1658 Update springboot templates to Spring Boot 3.0.5
  generate/zz_filesystem_generated.go
  templates/springboot/cloudevents/.mvn/wrapper/maven-wrapper.properties
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/.mvn/wrapper/maven-wrapper.properties
  templates/springboot/http/pom.xml
Labels: kind/enhancement, lgtm, approved, size/M

#1649 test: adding e2e github oncluster test scenario
  test/oncluster/scenario_github_test.go
  test/oncluster/testdata/simplefunc/.gitignore
  test/oncluster/testdata/simplefunc/func.yaml
  test/oncluster/testdata/simplefunc/index.js
  test/oncluster/testdata/simplefunc/package-lock.json
  test/oncluster/testdata/simplefunc/package.json
Labels: lgtm, approved, size/XXL, kind/cleanup

#1640 Replace path with function struct in client api
  cmd/build.go
  cmd/build_test.go
  cmd/client_test.go
  cmd/create.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/describe.go
  cmd/describe_test.go
  cmd/invoke_test.go
  cmd/run.go
  pkg/functions/client.go
  pkg/functions/client_int_test.go
  pkg/functions/client_test.go
  pkg/functions/function.go
  pkg/functions/function_test.go
  pkg/functions/instances_test.go
  pkg/functions/templates_test.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#1662 test: cleanup on e2e github test
  test/common/config.go
  test/oncluster/scenario_github_test.go
Labels: size/S, lgtm, approved, kind/cleanup

#1661 Update Rust templates dependencies and UTs for Actix 4.x
  generate/zz_filesystem_generated.go
  templates/rust/cloudevents/.gitignore
  templates/rust/cloudevents/Cargo.lock
  templates/rust/cloudevents/Cargo.toml
  templates/rust/cloudevents/src/config.rs
  templates/rust/cloudevents/src/main.rs
  templates/rust/http/.gitignore
  templates/rust/http/Cargo.lock
  templates/rust/http/Cargo.toml
  templates/rust/http/src/config.rs
  templates/rust/http/src/handler.rs
  templates/rust/http/src/main.rs
Labels: kind/enhancement, lgtm, approved, size/XXL

#1663 [Release 1.9] cherry pick template updates for Rust and SpringBoot
  templates/rust/cloudevents/.gitignore
  templates/rust/cloudevents/Cargo.lock
  templates/rust/cloudevents/Cargo.toml
  templates/rust/cloudevents/src/config.rs
  templates/rust/cloudevents/src/main.rs
  templates/rust/http/.gitignore
  templates/rust/http/Cargo.lock
  templates/rust/http/Cargo.toml
  templates/rust/http/src/config.rs
  templates/rust/http/src/handler.rs
  templates/rust/http/src/main.rs
  templates/springboot/cloudevents/.mvn/wrapper/maven-wrapper.properties
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/.mvn/wrapper/maven-wrapper.properties
  templates/springboot/http/pom.xml
  zz_filesystem_generated.go
Labels: lgtm, approved, size/XXL
