Repository knative/func, pull requests merged in 2023-06, with the labels that each got.

#1775 feat: add common command aliases
  cmd/delete.go
  cmd/list.go
Labels: lgtm, approved, size/XS

#1747 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1771 fix: PVCSize resets to default with futureproofing
  cmd/deploy.go
  docs/reference/func_deploy.md
  pkg/functions/function.go
  pkg/pipelines/tekton/pipeplines_provider.go
  pkg/pipelines/tekton/pipeplines_provider_test.go
Labels: kind/bug, lgtm, approved, size/M

#1777 src: invoke response cleanup
  cmd/invoke.go
Labels: size/S, lgtm, approved, kind/cleanup

#1774 feat: source-defined buildpacks
  generate/zz_filesystem_generated.go
  pkg/builders/buildpacks/builder.go
  pkg/builders/buildpacks/builder_test.go
  templates/go/manifest.yaml
Labels: lgtm, approved, size/M, kind/cleanup

#1776 src: remove datestamp from binary
  Makefile
  cmd/environment.go
  cmd/func/main.go
  cmd/root.go
  cmd/root_test.go
  cmd/version.go
  docs/reference/func_version.md
Labels: size/S, lgtm, approved

#1773 src: add missing 'omitempty' annotations
  pkg/functions/function.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/XS, kind/cleanup

#1772 src: fix filename misspelling
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/pipelines_provider_test.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1781 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1785 chore: clean up PaC GitLab test
  .github/workflows/test-integration.yaml
  hack/install-gitlab.sh
  hack/install-pac.sh
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/M

#1784 Fix appending SHA256 hash to image reference in ImageWithDigest
  pkg/functions/function.go
  pkg/functions/function_unit_test.go
Labels: kind/bug, size/S, lgtm, approved

#1783 src: errors cleanup
  cmd/build.go
  cmd/config.go
  cmd/delete.go
  cmd/deploy.go
  cmd/describe.go
  cmd/invoke.go
  cmd/run.go
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/functions/errors.go
  pkg/functions/function.go
  pkg/functions/instances.go
  pkg/functions/instances_test.go
  pkg/functions/runner.go
  pkg/functions/runner_test.go
  pkg/functions/templates.go
Labels: lgtm, approved, size/L, kind/cleanup

#1750 feat: enable scaffolding for host builds
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/functions/job.go
  pkg/functions/repository.go
  pkg/functions/signatures.go
  pkg/functions/testdata/testClientRunReadiness/f.go
  pkg/functions/testdata/testClientRunReadiness/go.mod
  pkg/oci/builder.go
  pkg/oci/builder_test.go
  pkg/oci/containerize_go.go
  pkg/oci/errors.go
  pkg/scaffolding/detectors.go
  pkg/scaffolding/detectors_test.go
  pkg/scaffolding/errors.go
  pkg/scaffolding/scaffold.go
  pkg/scaffolding/scaffold_test.go
  pkg/scaffolding/signatures.go
  pkg/scaffolding/signatures_test.go
  pkg/scaffolding/testdata/testnotfound/go/README.md
  pkg/scaffolding/testdata/testwrite/go/scaffolding/instanced-http/main.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#1787 chore: default s2i builder as vars
  pkg/builders/s2i/builder.go
Labels: size/S, lgtm, approved

#1791 cleanup: run test operations in dedicated ns
  pkg/pipelines/tekton/gitlab_test.go
Labels: size/S, lgtm, approved

#1789 test: integration test for tekton on cluster build
  .github/workflows/test-integration.yaml
  hack/allocate.sh
  hack/patch-s2i-task.sh
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pkg/pipelines/tekton/pipelines_integration_test.go
Labels: lgtm, approved, size/L

#1802 chore: update to Go 1.20
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/pkg/cached/cache.go
  vendor/k8s.io/kube-openapi/pkg/handler3/handler.go
  vendor/k8s.io/kube-openapi/pkg/internal/flags.go
  vendor/k8s.io/kube-openapi/pkg/internal/handler/handler_cache.go
  vendor/k8s.io/kube-openapi/pkg/internal/serialization.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/arshal.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/arshal_any.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/arshal_default.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/arshal_inlined.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/arshal_methods.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/arshal_time.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/decode.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/encode.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/pools.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/state.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/token.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/value.go
  vendor/k8s.io/kube-openapi/pkg/spec3/encoding.go
  vendor/k8s.io/kube-openapi/pkg/spec3/example.go
  vendor/k8s.io/kube-openapi/pkg/spec3/external_documentation.go
  vendor/k8s.io/kube-openapi/pkg/spec3/fuzz.go
  vendor/k8s.io/kube-openapi/pkg/spec3/header.go
  vendor/k8s.io/kube-openapi/pkg/spec3/media_type.go
  vendor/k8s.io/kube-openapi/pkg/spec3/operation.go
  vendor/k8s.io/kube-openapi/pkg/spec3/parameter.go
  vendor/k8s.io/kube-openapi/pkg/spec3/path.go
  vendor/k8s.io/kube-openapi/pkg/spec3/request_body.go
  vendor/k8s.io/kube-openapi/pkg/spec3/response.go
  vendor/k8s.io/kube-openapi/pkg/spec3/server.go
  vendor/k8s.io/kube-openapi/pkg/spec3/spec.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/header.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/info.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/items.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/operation.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/parameter.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/path_item.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/paths.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/ref.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/response.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/responses.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/schema.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/security_scheme.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/swagger.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/tag.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1803 Check error before defer body close, include timeout in error message
  pkg/functions/runner.go
Labels: lgtm, approved, size/XS

#1798 Cleanup Rust http example
  generate/zz_filesystem_generated.go
  templates/rust/http/Cargo.lock
  templates/rust/http/Cargo.toml
  templates/rust/http/src/config.rs
  templates/rust/http/src/handler.rs
  templates/rust/http/src/main.rs
Labels: lgtm, approved, size/L, kind/cleanup

#1804 src: cleanup the run timeout loop and check
  pkg/functions/errors.go
  pkg/functions/runner.go
Labels: lgtm, approved, size/M

#1797 added shorthand -R for --remote flag
  cmd/deploy.go
  docs/reference/func_deploy.md
Labels: lgtm, approved, size/XS

#1799 Cleanup Rust cloudevents example
  generate/zz_filesystem_generated.go
  templates/rust/cloudevents/Cargo.lock
  templates/rust/cloudevents/Cargo.toml
  templates/rust/cloudevents/src/config.rs
  templates/rust/cloudevents/src/handler.rs
  templates/rust/cloudevents/src/main.rs
Labels: lgtm, approved, size/XL, kind/cleanup

#1780 feat: platform build options
  cmd/build.go
  cmd/deploy.go
  cmd/run.go
  pkg/builders/buildpacks/builder.go
  pkg/builders/buildpacks/builder_test.go
  pkg/builders/s2i/builder.go
  pkg/builders/s2i/builder_test.go
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/mock/builder.go
  pkg/oci/builder.go
  pkg/oci/builder_test.go
  pkg/oci/containerize.go
  pkg/oci/containerize_go.go
Labels: kind/enhancement, lgtm, approved, size/L

#1809 src: use ghcr.io for dapr components in GH Action
  hack/allocate.sh
Labels: lgtm, approved, size/M

#1810 src: more verbose output
  .github/workflows/test-integration.yaml
  hack/binaries.sh
Labels: size/S, lgtm, approved

#1796 adding default builders
  cmd/environment.go
  docs/reference/func_config_git_set.md
  docs/reference/func_environment.md
  pkg/builders/buildpacks/builder.go
Labels: lgtm, approved, size/L

#1807 Update springboot template pom.xml dependencies
  generate/zz_filesystem_generated.go
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
Labels: size/S, lgtm, approved, kind/cleanup

#1814 Added Rust templates linting
  .github/workflows/ci.yaml
  Makefile
Labels: kind/enhancement, lgtm, approved, size/XS

#1800 fix: bad connection handling for in cluster dialer
  pkg/k8s/dialer.go
  pkg/k8s/dialer_test.go
Labels: kind/bug, lgtm, approved, size/L, ok-to-test

#1811 Add support for `serviceAccountName` on deploy
  docs/reference/func_yaml.md
  pkg/functions/function.go
  pkg/knative/deployer.go
  schema/func_yaml-schema.json
Labels: size/S, lgtm, approved

#1817 src: improved version output
  Makefile
  cmd/func/main.go
  cmd/root.go
  cmd/root_test.go
Labels: lgtm, approved, size/M

#1790 feat: support dependencies in host-built functions
  pkg/oci/containerize_go.go
Labels: kind/enhancement, size/S, lgtm, approved

#1812 adding service account support
  cmd/deploy.go
  docs/reference/func_deploy.md
  pkg/k8s/serviceaccount.go
  pkg/knative/deployer.go
Labels: lgtm, approved, size/L

#1821 src: refactor builder concurrency test
  pkg/oci/builder.go
  pkg/oci/builder_test.go
  pkg/oci/containerize.go
  pkg/oci/containerize_go.go
Labels: lgtm, approved, size/L, kind/cleanup

#1819 chore: test cluster versions update
  hack/allocate.sh
  hack/binaries.sh
Labels: lgtm, approved, size/M, kind/cleanup

#1820 src: speed up tests by building with a test platform
  pkg/functions/client_test.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1825 fix: choosePort for host-runner
  pkg/functions/runner.go
Labels: size/S, lgtm, approved

#1823 feat: scaffolding ca certs
  .gitignore
  Makefile
  generate/templates/main.go
  generate/zz_filesystem_generated.go
  pkg/filesystem/filesystem.go
  pkg/filesystem/filesystem_test.go
  pkg/functions/repository.go
  pkg/oci/builder_test.go
  pkg/oci/containerize.go
  pkg/scaffolding/scaffold.go
  pkg/scaffolding/scaffold_test.go
  pkg/scaffolding/testdata/go/scaffolding/instanced-http/main.go
  pkg/scaffolding/testdata/testwrite/certs/README.md
  pkg/scaffolding/testdata/testwrite/certs/ca-certificates.crt
  templates/README.md
  templates/certs/README.md
  templates/certs/ca-certificates.crt
Labels: lgtm, approved, size/XXL

#1808 chore: use a custom presubmit_tests.sh script
  test/presubmit-tests.sh
Labels: lgtm, approved, size/M, kind/chore

#1832 chore: quiet template tests for quarkus, springboot & rust
  Makefile
Labels: size/S, lgtm, approved, kind/chore

#1833 chore: add presubmit-unit-tests Makefile target
  Makefile
  test/presubmit-tests.sh
Labels: lgtm, approved, size/M, kind/chore

#1834 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1815 adding support for .funcignore file
  pkg/builders/buildpacks/builder.go
  pkg/builders/buildpacks/builder_test.go
  pkg/builders/s2i/builder.go
  pkg/builders/s2i/builder_test.go
  pkg/functions/client.go
Labels: lgtm, approved, size/L, ok-to-test

#1828 src: make test and check go
  Makefile
  generate/zz_filesystem_generated.go
  templates/go/scaffolding/static-cloudevents/main.go
  templates/go/scaffolding/static-http/main.go
Labels: kind/enhancement, lgtm, approved, size/M

#1835 src: rebuild templates on make update-runtimes
  Makefile
Labels: lgtm, approved, size/XS, kind/cleanup
