Repository knative/func, pull requests merged in 2023-08, with the labels that each got.

#1895 chore: cron task for paketo's jammy builder
  .github/workflows/update-builder.yaml
  hack/update-builder.go
Labels: lgtm, approved, size/L

#1898 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1896 fix: spring boot dependency updater
  .github/workflows/update-springboot-platform.yaml
  hack/update-springboot-platform.js
Labels: lgtm, approved, size/M

#1902 chore: update scaffolding sandbox => extensions
  generate/zz_filesystem_generated.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/go.sum
  templates/go/scaffolding/instanced-cloudevents/main.go
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/instanced-http/main.go
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/go.sum
  templates/go/scaffolding/static-cloudevents/main.go
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
  templates/go/scaffolding/static-http/main.go
Labels: lgtm, approved, size/M

#1903 fix: typo
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#1906 chore: update Func Go buildpack reference
  hack/update-builder.go
Labels: lgtm, approved, size/XS

#1905 rename knative-sandbox
  Makefile
  cmd/repository.go
  docs/language-packs/language-pack-contract.md
  docs/language-packs/templates.md
  docs/reference/func_repository.md
Labels: lgtm, approved, size/M, kind/chore

#1912 chore: multiple variants of builder
  hack/update-builder.go
Labels: size/S, lgtm, approved

#1910 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1915 fix: report correct error when task doesn't exist
  pkg/pipelines/tekton/templates.go
Labels: lgtm, approved, size/XS

#1916 chore: released binaries refer correct tekton task yamls
  hack/release.sh
Labels: lgtm, approved, size/XS

#1920 chore: mark test as integration test
  pkg/pipelines/tekton/templates_integration_test.go
  pkg/pipelines/tekton/templates_test.go
Labels: lgtm, approved, size/M

#1918 chore: refer correct tekton task yamls in tests
  .github/workflows/test-unit.yaml
  Makefile
  test/presubmit-tests.sh
Labels: size/S, lgtm, approved

#1917 test: update github ref used on e2e oncluster tests
  test/oncluster/scenario_github_test.go
Labels: lgtm, approved, size/XS

#1911 Use custom jammy paketo builder
  .github/workflows/test-e2e-runtime.yaml
  generate/zz_filesystem_generated.go
  hack/test-integration-podman.sh
  pkg/builders/buildpacks/builder.go
  pkg/k8s/security_context.go
  pkg/pipelines/resources/tekton/task/func-buildpacks/0.2/func-buildpacks.yaml
  pkg/pipelines/tekton/gitlab_test.go
  pkg/pipelines/tekton/pipelines_integration_test.go
  pkg/pipelines/tekton/pipelines_pac_provider.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/validate.go
  pkg/pipelines/tekton/validate_test.go
  templates/rust/manifest.yaml
  test/e2e/scenario_runtime-http_test.go
  test/oncluster/scenario_runtime_test.go
Labels: lgtm, approved, size/L

#1921 feat: run host-built containers as non-root
  pkg/oci/containerize.go
Labels: kind/enhancement, lgtm, approved, size/XS

#1926 changelog manual renaming
  CHANGELOG.md
Labels: lgtm, approved, size/XL

#1923 doc: Go and Rust on cluster build is supported
  docs/CONTRIBUTING.md
  docs/building-functions/on_cluster_build.md
Labels: lgtm, approved, size/XS

#1925 feat: tekton task urls in the `environment` sub-command output
  cmd/environment.go
  pkg/pipelines/tekton/templates.go
Labels: lgtm, approved, size/M

#1924 chore: update release generation
  Makefile
  hack/release.sh
Labels: size/S, lgtm, approved

#1929 fix: docker registry/repository parsing
  cmd/deploy_test.go
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/functions/function.go
  pkg/functions/function_unit_test.go
Labels: kind/bug, lgtm, approved, size/L

#1922 Remove progress package (spinner)
  cmd/client.go
  cmd/deploy_test.go
  pkg/docker/pusher.go
  pkg/functions/client.go
  pkg/mock/pipelines_provider.go
  pkg/pipelines/tekton/pipelines_integration_test.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/progress/progress.go
Labels: lgtm, approved, size/XL, kind/removal

#1930 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1936 typos
  cmd/build.go
  cmd/deploy.go
  docs/reference/func_build.md
  docs/reference/func_deploy.md
Labels: lgtm, approved, size/XS

#1935 Improving func environment command
  cmd/environment.go
  docs/reference/func_environment.md
Labels: lgtm, approved, size/M, ok-to-test

#1934 chore: added standard labels for our builders
  hack/update-builder.go
Labels: lgtm, approved, size/M

#1937 chore: faster `make build`
  Makefile
Labels: size/S, lgtm, approved

#1944 chore: update CA certs
  generate/zz_filesystem_generated.go
  templates/certs/ca-certificates.crt
Labels: lgtm, approved, size/L

#1945 fix: err check at correct place
  test/testhttp/testhttp.go
Labels: lgtm, approved, size/XS

#1960 chore: update buildah image ref
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
Labels: lgtm, approved, size/XS

#1957 chore: Update client-go dependency to aligned version
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/L, kind/cleanup
