Repository knative/func, pull requests merged in 2023-02, with the labels that each got.

#1529 feat: apply and update client methods
  client.go
  client_int_test.go
  client_test.go
  cmd/build_test.go
  cmd/create.go
  cmd/delete_test.go
  cmd/deploy_test.go
  cmd/describe_test.go
  cmd/invoke_test.go
  function_test.go
  instances_test.go
  templates_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1530 client methods return current function route
  client.go
  client_int_test.go
  client_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1518 feat: preliminary dapr runtime support
  client.go
  client_int_test.go
  hack/allocate.sh
  hack/binaries.sh
  knative/deployer.go
  knative/labels.go
Labels: kind/enhancement, lgtm, approved, size/L

#1434 feat: deploy command global config with function context
  client.go
  client_int_test.go
  client_test.go
  cmd/build.go
  cmd/build_test.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/describe_test.go
  cmd/list.go
  cmd/list_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/testdata/TestX_ConfigApplied/func/config.yaml
  cmd/testdata/TestX_ConfigPrecedence/func/config.yaml
  config/config.go
  docs/reference/func_build.md
  docs/reference/func_delete.md
  docs/reference/func_deploy.md
  docs/reference/func_describe.md
  function.go
  mock/deployer.go
  testing/testing.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#1532 Cleanup: remove ioutil for new go version
  test/e2e/main_test.go
Labels: lgtm, approved, size/XS, kind/cleanup

#1533 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/M, skip-review

#1539 fix: func deploy with explicity `--build=false` bypass isBuilt check
  client.go
  cmd/deploy.go
Labels: kind/bug, size/S, lgtm, approved

#1540 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#1542 fix: oncluster builds registry mismatch error
  pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
  pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pipelines/tekton/pipeplines_provider.go
  pipelines/tekton/resources.go
  pipelines/tekton/tasks.go
Labels: size/S, lgtm, approved

#1548 Use current (as in PR) func image in integration tests
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  hack/create-testing-func-image.sh
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: lgtm, approved, size/M

#1558 feat: adds refspec support for `func repo add`
  cmd/repository.go
  cmd/repository_test.go
  docs/reference/func_repository.md
  pkg/functions/repositories_test.go
  pkg/functions/repository.go
Labels: kind/enhancement, lgtm, approved, size/L

#1555 feat(templates): remove liveness and readiness from defaults
  generate/zz_filesystem_generated.go
  pkg/functions/repository.go
  templates/manifest.yaml
Labels: kind/enhancement, size/S, lgtm, approved

#1437 chore: build and deploy test suite cleanup
  cmd/build_test.go
  cmd/deploy_test.go
Labels: lgtm, approved, size/XXL, kind/cleanup

#1560 chore: `testData` -> `testdata`
  pkg/builders/s2i/builder_test.go
  pkg/builders/s2i/testdata/builder.tar
  pkg/docker/pusher_test.go
  pkg/docker/testdata/image.tar
  pkg/k8s/persistent_volumes_test.go
  pkg/k8s/testdata/content.tar
  pkg/pipelines/tekton/pipeplines_provider_test.go
  pkg/pipelines/tekton/testdata/fn-src/.gitignore
  pkg/pipelines/tekton/testdata/fn-src/hello.txt
  pkg/pipelines/tekton/testdata/fn-src/hello.txt.lnk
Labels: size/S, lgtm, approved

#1557 chore(release): add tekton artifacts to release
  hack/release.sh
Labels: lgtm, approved, size/XS, kind/chore

#1556 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1559 feat: global config accessors
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1562 feat: enabled s2i for python
  generate/zz_filesystem_generated.go
  pkg/builders/s2i/builder.go
  pkg/builders/s2i/builder_test.go
  templates/python/cloudevents/app.sh
  templates/python/http/app.sh
  test/oncluster/scenario_runtime_test.go
Labels: size/S, lgtm, approved

#1563 fix: ban podman 4.3 for pack build
  pkg/builders/buildpacks/builder.go
Labels: size/S, lgtm, approved

#1565 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/client/pkg/serving/service.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1569 fix initialization of service.Spec.Template.ObjectMeta.Annotations
  pkg/knative/deployer.go
Labels: lgtm, approved, size/XS

#1570 chore: update faas-js-runtime to 0.10.0
  .gitattributes
  generate/zz_filesystem_generated.go
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
Labels: lgtm, approved, size/XXL, kind/chore

#1576 removes dangling testData
  pkg/builders/s2i/testData/builder.tar
  pkg/docker/testData/image.tar
  pkg/k8s/testData/content.tar
  pkg/pipelines/tekton/testData/fn-src/.gitignore
  pkg/pipelines/tekton/testData/fn-src/hello.txt
  pkg/pipelines/tekton/testData/fn-src/hello.txt.lnk
Labels: kind/bug, lgtm, approved, size/XS

#1575 fix: missing map initializations
  pkg/functions/function.go
Labels: kind/bug, lgtm, approved, size/XS

#1574 fix: deploy annotations & labels correctly
  Makefile
  pkg/functions/client_int_test.go
  pkg/knative/deployer.go
Labels: lgtm, approved, size/L

#1579 [release-1.9] feat: enabled s2i for python (#1562)
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  hack/create-testing-func-image.sh
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
  s2i/builder.go
  s2i/builder_test.go
  templates/python/cloudevents/app.sh
  templates/python/http/app.sh
  test/oncluster/scenario_runtime_test.go
  zz_filesystem_generated.go
Labels: kind/enhancement, lgtm, approved, size/M

#1577 fix: repo add no longer skips root
  pkg/filesystem/filesystem.go
  pkg/functions/repository.go
Labels: kind/bug, size/S, lgtm, approved

#1578 feat: common command aliases
  cmd/config_envs.go
  cmd/config_labels.go
  cmd/config_volumes.go
  cmd/repository.go
Labels: kind/enhancement, size/S, lgtm, approved

#1580 chore: update references to zz_filesystem_generated.go
  Makefile
  generate/templates/main.go
  hack/update-quarkus-platform.js
  hack/verify-codegen.sh
Labels: lgtm, approved, size/M, kind/chore

#1584 cleanup: FS test
  pkg/filesystem/filesystem_test.go
Labels: lgtm, approved, size/L

#1590 chore: verify-codegen.sh
  hack/verify-codegen.sh
Labels: lgtm, approved, size/XS
