Repository knative/func, pull requests merged in 2023-11, with the labels that each got.

#2064 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2063 Differentiate between podman and docker for local registry connection
  hack/allocate.sh
Labels: size/S, lgtm, approved

#2066 Using `$CONTAINER_ENGINE` variable instead of hard-coded `docker`
  hack/allocate.sh
Labels: lgtm, approved, size/XS

#2001 Adding support for `func subscribe` for creating mutiple triggers, based on event filters
  Makefile
  cmd/root.go
  cmd/subscribe.go
  cmd/subscribe_test.go
  docs/reference/func.md
  docs/reference/func_subscribe.md
  pkg/functions/client_int_test.go
  pkg/functions/function.go
  pkg/knative/deployer.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/L

#2068 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2071 fix: release uses correct version tags
  hack/release.sh
Labels: size/S, lgtm, approved

#2072 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2069 Fixed PersistentVolumeClaim spelling error
  cmd/config_volumes.go
  pkg/functions/function_migrations.go
  pkg/functions/function_volumes.go
  pkg/functions/function_volumes_unit_test.go
  pkg/knative/deployer.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/M, ok-to-test

#2073 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2079 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2083 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2084 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2078 test: adding e2e test for config volumes EmptyDir and PersistentVolumeClaim
  test/e2e/scenario_config-volumes_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#2087 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2089 Make SECURITY.md consistent
  SECURITY.md
Labels: lgtm, approved, size/XS

#2091 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2093 Added clotributor link to readme
  README.md
Labels: lgtm, approved, size/XS

#2095 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2090 Log if image is referenced by tag
  go.mod
  pkg/builders/s2i/builder.go
Labels: kind/enhancement, lgtm, approved, size/XS, ok-to-test
