Repository knative/func, pull requests merged in 2023-05, with the labels that each got.

#1708 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1693 feat: func run support all build options
  cmd/client.go
  cmd/deploy.go
  cmd/root.go
  cmd/run.go
  pkg/functions/client.go
  pkg/functions/function.go
  pkg/functions/job.go
  test/e2e/scenario_extended_flow_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#1715 chore: update docs from changes to deploy/run
  docs/reference/func_build.md
  docs/reference/func_deploy.md
  docs/reference/func_run.md
Labels: lgtm, approved, size/M

#1666 add pvc and emptyDir to function_volumes
  Makefile
  cmd/config_volumes.go
  pkg/functions/function.go
  pkg/functions/function_volumes.go
  pkg/functions/function_volumes_unit_test.go
  pkg/functions/invoke.go
  pkg/k8s/persistent_volumes.go
  pkg/k8s/persistent_volumes_test.go
  pkg/knative/deployer.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/L, kind/api-change

#1695 feat: write a build stamp log to .func
  cmd/build.go
  cmd/deploy.go
  cmd/run_test.go
  pkg/functions/client.go
  pkg/functions/function.go
Labels: kind/enhancement, lgtm, approved, size/L

#1721 chore: update maven wrapper in Quarkus template
  generate/zz_filesystem_generated.go
  templates/quarkus/cloudevents/mvnw
  templates/quarkus/cloudevents/mvnw.cmd
  templates/quarkus/http/mvnw
  templates/quarkus/http/mvnw.cmd
Labels: lgtm, approved, size/XL

#1723 chore: Quarkus auto-update action runs smoke test
  .github/workflows/update-quarkus-platform.yaml
  hack/update-quarkus-platform.js
Labels: size/S, lgtm, approved

#1697 feat: job scaffolding
  cmd/invoke_test.go
  cmd/run.go
  pkg/docker/runner.go
  pkg/docker/runner_int_test.go
  pkg/functions/client_int_test.go
  pkg/functions/client_test.go
  pkg/functions/job.go
  pkg/functions/job_test.go
  pkg/mock/runner.go
Labels: kind/enhancement, lgtm, approved, size/L

#1717 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1736 chore: remove Procfile from Rust templates
  generate/zz_filesystem_generated.go
  templates/rust/cloudevents/Procfile
  templates/rust/http/Procfile
Labels: lgtm, approved, size/XS

#1737 fix: use full builder for Rust
  pkg/builders/buildpacks/builder.go
Labels: lgtm, approved, size/XS

#1729 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1731 docs: regen for domain option
  docs/reference/func_deploy.md
Labels: size/S, lgtm, approved, kind/cleanup

#1738 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#1739 chore: improve error message when no func on path
  cmd/config.go
  cmd/delete.go
  cmd/describe.go
  cmd/invoke.go
Labels: lgtm, approved, size/XS

#1728 fix: .gitignore .func
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/functions/function.go
  pkg/functions/function_test.go
Labels: kind/bug, kind/enhancement, lgtm, approved, size/XL

#1740 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#1730 feat: host oci builder
  cmd/build.go
  pkg/functions/client.go
  pkg/functions/function.go
  pkg/oci/builder.go
  pkg/oci/builder_test.go
  pkg/oci/containerize.go
  pkg/oci/containerize_go.go
Labels: kind/enhancement, lgtm, approved, size/XL

#1742 chore: improve error msg when PAC is not installed
  pkg/pipelines/tekton/pipelines_pac_provider.go
Labels: size/S, lgtm, approved

#1745 chore: improve error messages for most commands
  cmd/build.go
  cmd/config.go
  cmd/delete.go
  cmd/deploy.go
  cmd/describe.go
  cmd/invoke.go
  cmd/run.go
  pkg/functions/function.go
Labels: lgtm, approved, size/M, kind/cleanup

#1746 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#1732 feat: go scaffolding
  generate/zz_filesystem_generated.go
  pkg/filesystem/filesystem_test.go
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/functions/repository.go
  templates/go/.instanced-cloudevent/README.md
  templates/go/.instanced-cloudevent/function.go
  templates/go/.instanced-cloudevent/function_test.go
  templates/go/.instanced-cloudevent/go.mod
  templates/go/.instanced-cloudevent/manifest.yaml
  templates/go/.instanced-http/README.md
  templates/go/.instanced-http/function.go
  templates/go/.instanced-http/function_test.go
  templates/go/.instanced-http/go.mod
  templates/go/scaffolding/README.md
  templates/go/scaffolding/instanced-cloudevent/f
  templates/go/scaffolding/instanced-cloudevent/go.mod
  templates/go/scaffolding/instanced-cloudevent/go.sum
  templates/go/scaffolding/instanced-cloudevent/main.go
  templates/go/scaffolding/instanced-http/f
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/instanced-http/main.go
  templates/go/scaffolding/static-cloudevent/f
  templates/go/scaffolding/static-cloudevent/go.mod
  templates/go/scaffolding/static-cloudevent/go.sum
  templates/go/scaffolding/static-cloudevent/main.go
  templates/go/scaffolding/static-http/f
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
  templates/go/scaffolding/static-http/main.go
Labels: kind/enhancement, lgtm, approved, size/XL

#1743 fix: don't require credentials when not configuring webhook
  cmd/config_git_set.go
Labels: kind/bug, size/S, lgtm, approved

#1754 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1752 Use Contour Ingress instead of Kourier
  hack/allocate.sh
Labels: lgtm, approved, size/M

#1735 Prepare pipelines as code template for midstream customization
  pkg/pipelines/tekton/templates.go
Labels: size/S, lgtm, approved

#1733 feat: host-based scaffolded function runner
  cmd/invoke_test.go
  pkg/docker/runner.go
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/functions/function_git_unit_test.go
  pkg/functions/function_migrations_unit_test.go
  pkg/functions/job.go
  pkg/functions/job_test.go
  pkg/functions/runner.go
  pkg/functions/runner_test.go
  pkg/functions/signatures_test.go
  pkg/functions/template.go
  pkg/mock/runner.go
Labels: kind/enhancement, lgtm, approved, size/L

#1756 Pass image with digest to the deploy task
  pkg/pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
  pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
  pkg/pipelines/tekton/resources.go
  pkg/pipelines/tekton/tasks.go
  pkg/pipelines/tekton/templates_pack.go
Labels: size/S, lgtm, approved

#1762 Automated platform update for springboot templates
  .github/workflows/update-springboot-platform.yaml
  generate/zz_filesystem_generated.go
  hack/update-springboot-platform.js
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
Labels: lgtm, approved, size/L

#1765 reduce default build platforms
  pkg/oci/builder.go
Labels: lgtm, approved, size/XS, kind/cleanup
