Repository knative/func, pull requests merged in 2023-10, with the labels that each got.

#1998 [release-1.11] backports for release-1.11.1
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  Makefile
  cmd/deploy_test.go
  cmd/environment.go
  docs/CONTRIBUTING.md
  docs/building-functions/on_cluster_build.md
  generate/zz_filesystem_generated.go
  hack/release.sh
  hack/test-integration-podman.sh
  pkg/builders/buildpacks/builder.go
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/functions/function.go
  pkg/functions/function_unit_test.go
  pkg/k8s/persistent_volumes.go
  pkg/k8s/security_context.go
  pkg/oci/builder.go
  pkg/oci/builder_test.go
  pkg/pipelines/resources/tekton/task/func-buildpacks/0.2/func-buildpacks.yaml
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pkg/pipelines/tekton/gitlab_test.go
  pkg/pipelines/tekton/pipelines_integration_test.go
  pkg/pipelines/tekton/pipelines_pac_provider.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/validate.go
  pkg/pipelines/tekton/validate_test.go
  templates/certs/ca-certificates.crt
  templates/quarkus/cloudevents/.mvn/wrapper/MavenWrapperDownloader.java
  templates/quarkus/cloudevents/.mvn/wrapper/maven-wrapper.properties
  templates/quarkus/cloudevents/pom.xml
  templates/quarkus/http/.mvn/wrapper/MavenWrapperDownloader.java
  templates/quarkus/http/.mvn/wrapper/maven-wrapper.properties
  templates/quarkus/http/pom.xml
  templates/rust/manifest.yaml
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
  test/e2e/scenario_runtime-http_test.go
  test/oncluster/scenario_github_test.go
  test/oncluster/scenario_runtime_test.go
  test/presubmit-tests.sh
Labels: lgtm, approved, size/XXL, ok-to-test

#2002 test: increase timeout to wait func to get ready on no-container test
  test/e2e/scenario_no_container_test.go
Labels: lgtm, approved, size/XS

#1995 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, skip-review

#2009 fixup: zz_filesystem_generated.go
  generate/zz_filesystem_generated.go
Labels: lgtm, approved, size/XS

#2008 Continue on error when one of runtimes fails
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-runtime.yaml
Labels: lgtm, approved, size/XS

#2015 fix s2i on cluster RT tests
  pkg/builders/s2i/builder.go
  test/oncluster/scenario_runtime_test.go
Labels: lgtm, approved, size/XS

#1964 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2032 test improvements remove deprecates avoid nils, bump go version 1.20.x
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  hack/allocate.sh
  pkg/functions/client_int_test.go
  test/common/readycheck.go
  test/e2e/scenario_extended_flow_test.go
  test/e2e/scenario_no_container_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#2014 chore: update maven profile buildEnv in springboot templates
  generate/zz_filesystem_generated.go
  templates/springboot/cloudevents/README.md
  templates/springboot/http/README.md
  templates/springboot/manifest.yaml
Labels: lgtm, approved, size/M

#2029 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#2031 chore: Add go setup as composite action
  .github/composite/go-setup/action.yaml
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/update-builder.yaml
Labels: lgtm, approved, size/L

#2034 test: better clean up after test
  pkg/pipelines/tekton/pipelines_integration_test.go
Labels: lgtm, approved, size/M

#2021 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2042 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2044 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2041 test: more robust test
  pkg/functions/client_int_test.go
Labels: lgtm, approved, size/M

#2012 test: optimise disk usage
  hack/allow-insecure.tar
  hack/setup-testing-images.sh
Labels: size/S, lgtm, approved

#2003 SSH tests
  go.mod
  go.sum
  pkg/ssh/server_test.go
  pkg/ssh/ssh_dialer_test.go
  pkg/ssh/ssh_posix_test.go
  pkg/ssh/ssh_windows_test.go
Labels: lgtm, approved, size/XXL

#2047 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#2048 fixup: generated file
  generate/zz_filesystem_generated.go
Labels: lgtm, approved, size/XS

#2046 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2052 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2051 fix: better cleaup for Java template tests
  Makefile
Labels: lgtm, approved, size/XS

#2055 Add limit to number of manifests
  pkg/docker/platform.go
Labels: kind/bug, lgtm, approved, size/XS, ok-to-test

#2050 test: verify embedded templates
  test/presubmit-tests.sh
Labels: lgtm, approved, size/XS

#2060 Adding simple Podman insecure registry support
  hack/registry.sh
Labels: size/S, lgtm, approved

#2061 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
Labels: lgtm, approved, size/M

#2062 fix: NPE
  pkg/knative/deployer.go
Labels: size/S, lgtm, approved
