Repository knative/func, pull requests merged in 2024-09, with the labels that each got.

#2471 On cluster s2i build for Go (alternative version)
  Dockerfile.utils
  cmd/func-util/main.go
  pkg/pipelines/tekton/tasks.go
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/templates_pack.go
  pkg/pipelines/tekton/templates_s2i.go
Labels: lgtm, approved, size/L

#2473 Add s2i to the func-utils image
  Dockerfile.utils
  cmd/func-util/main.go
  go.mod
  go.sum
  pkg/pipelines/tekton/tasks.go
Labels: lgtm, approved, size/M

#2476 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2477 migrate client-pkg to client/pkg
  cmd/deploy.go
  cmd/root.go
  cmd/root_test.go
  cmd/templates/command_groups_test.go
  cmd/templates/template_engine_test.go
  go.mod
  go.sum
  pkg/knative/client.go
  pkg/knative/deployer.go
  pkg/knative/describer.go
  pkg/knative/lister.go
  plugin/plugin.go
Labels: lgtm, approved, size/M

#2480 [release-1.15] Release 1.15.1
  Dockerfile.utils
  cmd/build.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/func-util/main.go
  cmd/run.go
  cmd/run_test.go
  generate/zz_filesystem_generated.go
  go.mod
  go.sum
  hack/release.sh
  pkg/docker/runner_int_test.go
  pkg/functions/client.go
  pkg/functions/client_int_test.go
  pkg/oci/pusher_test.go
  pkg/pipelines/tekton/tasks.go
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/templates_pack.go
  pkg/pipelines/tekton/templates_s2i.go
  templates/quarkus/cloudevents/pom.xml
  templates/quarkus/http/pom.xml
  templates/rust/cloudevents/Cargo.lock
  templates/rust/http/Cargo.lock
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
  test/e2e/scenario_runtime-http_test.go
Labels: lgtm, approved, size/XXL

#2478 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2484 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2361 fix: HOME with different permissions
  cmd/root.go
  pkg/config/config.go
  pkg/docker/creds/credentials_test.go
  pkg/functions/repositories.go
Labels: kind/enhancement, lgtm, approved, size/L

#2489 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2491 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2495 Revert bad changes
  Makefile
Labels: size/S, lgtm, approved

#2496 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2499 test: preventing dubios ownership repository error on git unit tests
  pkg/testing/testing.go
Labels: lgtm, approved, size/XS

#2500 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2504 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2506 Improve socat connection success detection using KMP
  pkg/k8s/dialer.go
  pkg/k8s/dialer_unit_test.go
Labels: lgtm, approved, size/M

#2511 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2479 Go socat
  Dockerfile.utils
  cmd/func-util/main.go
  cmd/func-util/socat.go
  cmd/func-util/socat_test.go
Labels: lgtm, approved, size/L

#2510 fix: make image digest check more permissive
  cmd/deploy.go
  cmd/deploy_test.go
Labels: kind/bug, lgtm, approved, size/L

#2514 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2512 Use latest buildpack builder images
  pkg/builders/buildpacks/builder.go
Labels: lgtm, approved, size/XS

#2513 Remove unnecessary clause from Dockerfile
  Dockerfile.utils
Labels: lgtm, approved, size/XS

#2518 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2519 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2523 fix: allow sub-pkgs in Go functions
  generate/zz_filesystem_generated.go
  pkg/builders/s2i/assemblers.go
  pkg/functions/runner.go
  pkg/oci/containerize_go.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/main.go
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/main.go
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/main.go
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/main.go
Labels: lgtm, approved, size/M

#2524 Remove unnecessary 'go get' commands
  pkg/builders/s2i/assemblers.go
  pkg/functions/runner.go
  pkg/oci/containerize_go.go
Labels: size/S, lgtm, approved
