Repository knative/func, pull requests merged in 2024-12, with the labels that each got.

#2605 Update pack dep
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2606 Update golangci-lint
  Makefile
  cmd/func-util/main.go
  cmd/root.go
  pkg/knative/deployer.go
Labels: lgtm, approved, size/XS

#2604 Update pack/s2i/docker deps
  .github/composite/go-setup/action.yaml
  Dockerfile.utils
  go.mod
  go.sum
  pkg/docker/runner_int_test.go
  pkg/docker/zz_close_guarding_client_generated.go
Labels: lgtm, approved, size/L, do-not-merge/hold

#2596 add repository to the credentials prompt
  cmd/prompt/prompt.go
  pkg/docker/creds/credentials.go
  pkg/docker/creds/credentials_test.go
Labels: size/S, lgtm, approved

#2607 Fixed some deprecation warnings
  go.mod
  go.sum
  pkg/docker/platform.go
  pkg/docker/pusher_test.go
  pkg/docker/zz_close_guarding_client_generated.go
Labels: lgtm, approved, size/M

#2608 Fix some linter errors in integration tests
  pkg/docker/runner_int_test.go
  pkg/functions/client_int_test.go
  pkg/k8s/dialer_test.go
  pkg/k8s/logs_test.go
  pkg/k8s/persistent_volumes_test.go
  pkg/knative/integration_test.go
  pkg/pipelines/tekton/gitlab_test.go
  pkg/pipelines/tekton/pipelines_integration_test.go
Labels: lgtm, approved, size/M

#2612 use knative go setup action
  .github/composite/go-setup/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/update-builder.yaml
  .github/workflows/update-quarkus-platform.yaml
  .github/workflows/update-springboot-platform.yaml
Labels: lgtm, approved, size/M, kind/cleanup

#2614 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2615 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2613 bump: setup-node action version in workflows
  .github/workflows/update-ca-bundle.yaml
  .github/workflows/update-quarkus-platform.yaml
  .github/workflows/update-springboot-platform.yaml
Labels: lgtm, approved, size/XS

#2619 fix: add case for DNS resolve fail in TestDialUnreachable
  pkg/k8s/dialer_test.go
Labels: lgtm, approved, size/XS

#2617 Provide tiny buildpack builder image for ARM64
  hack/update-builder.go
Labels: lgtm, approved, size/L

#2622 Fix authorization for buildpack builder periodic task
  hack/update-builder.go
Labels: lgtm, approved, size/M

#2624 Use library GH keychain instead of our own
  hack/update-builder.go
Labels: size/S, lgtm, approved

#2620 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2629 Fix buildpack builder script
  go.mod
  hack/update-builder.go
Labels: lgtm, approved, size/M

#2630 Fix deadlock
  hack/update-builder.go
Labels: lgtm, approved, size/M

#2626 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2631 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
