Repository knative/func, pull requests merged in 2024-06, with the labels that each got.

#2236 Run func without HOME defined/ unaccessible .config dir
  cmd/build.go
  cmd/deploy.go
  cmd/deploy_test.go
  pkg/builders/buildpacks/builder.go
  pkg/docker/creds/credentials.go
  pkg/docker/creds/credentials_test.go
  pkg/functions/client_int_test.go
Labels: kind/bug, kind/enhancement, lgtm, approved, size/L

#2338 chore: ubi9 => ubi8
  pkg/builders/s2i/builder.go
Labels: lgtm, approved, size/XS

#2337 Update pack dependency
  go.mod
  go.sum
  hack/update-builder.go
Labels: lgtm, approved, size/L, ok-to-test

#2334 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2340 chore: update tekton,PaC
  go.mod
  go.sum
  hack/install-pac.sh
  hack/install-tekton.sh
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/XXL

#2335 Honor --registry-insecure flag in deploy command
  cmd/deploy.go
Labels: kind/bug, lgtm, approved, size/XS, ok-to-test

#2342 fix: error when setting gitlab settings in test
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/M

#2343 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2352 chore: use codegen script for docs
  docs/reference/func_config_git_remove.md
  docs/reference/func_delete.md
  docs/reference/func_deploy.md
  docs/reference/func_describe.md
  docs/reference/func_list.md
  hack/update-codegen.sh
  hack/verify-codegen.sh
Labels: size/S, lgtm, approved

#2341 fix: PaC build
  pkg/pipelines/tekton/pac/pac.go
  pkg/pipelines/tekton/pipelines_pac_provider.go
Labels: lgtm, approved, size/M

#2348 Clarify --registry-insecure flag description
  cmd/build.go
  cmd/deploy.go
Labels: lgtm, approved, size/XS, kind/documentation, needs-ok-to-test

#2355 Optimized disk usage in GH Action for integration tests
  .github/workflows/test-integration.yaml
  docs/reference/func_build.md
  docs/reference/func_deploy.md
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/M

#2350 fix: mount of Docker API socket from Docker Desktop
  pkg/docker/docker_client.go
  pkg/docker/docker_client_test.go
Labels: size/S, lgtm, approved

#2346 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2356 test: increased wait period
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/XS

#2345 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#2349 test: better res cleanup
  pkg/functions/client_int_test.go
Labels: size/S, lgtm, approved

#2360 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2362 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2363 test: revert error suppression
  test/e2e/scenario_runtime-cloudevents_test.go
  test/e2e/scenario_runtime-http_test.go
  test/oncluster/scenario_runtime_test.go
Labels: lgtm, approved, size/M

#2366 fix: codegen does not use current ns
  hack/update-codegen.sh
Labels: lgtm, approved, size/XS

#2369 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2368 corrected doc
  docs/reference/func_yaml.md
Labels: size/S, lgtm, approved, kind/documentation, needs-ok-to-test

#2370 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2374 chore: update deps
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2376 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2379 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2378 chore: removed deprecated types
  hack/update-builder.go
  pkg/docker/pusher.go
  pkg/docker/pusher_test.go
  pkg/docker/zz_close_guarding_client_generated.go
Labels: lgtm, approved, size/M

#2386 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2372 corrected error msg
  pkg/knative/deployer.go
Labels: kind/bug, lgtm, approved, size/XS, ok-to-test

#2387 Fix codegen
  hack/update-codegen.sh
Labels: lgtm, approved, size/XS

#2383 chore: updated tekton api verison
  pkg/pipelines/resources/tekton/task/func-buildpacks/0.2/func-buildpacks.yaml
  pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pkg/pipelines/tekton/client.go
  pkg/pipelines/tekton/pipelines_provider.go
Labels: size/S, lgtm, approved

#2391 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2392 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2394 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2395 chore: check FS gen in hack/update-codegen.sh
  hack/update-codegen.sh
  hack/verify-codegen.sh
Labels: size/S, lgtm, approved

#2397 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2396 feat: embed tkn tasks in func binary
  cmd/environment.go
  cmd/root.go
  cmd/tkn_tasks.go
  docs/generator/main.go
  pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
  pkg/pipelines/tekton/tasks.go
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/templates_pack.go
Labels: lgtm, approved, size/L

#2403 chore: updated Go linter
  Makefile
Labels: lgtm, approved, size/XS

#2402 chore: removed unused constants
  pkg/pipelines/tekton/templates.go
Labels: size/S, lgtm, approved
