Repository knative/func, pull requests merged in 2024-02, with the labels that each got.

#2144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2143 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2146 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2147 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2148 chore: update pack to v0.33.0
  go.mod
  go.sum
  hack/update-builder.go
  pkg/docker/docker_client.go
  third_party/VENDOR-LICENSE/github.com/containerd/log/LICENSE
  third_party/VENDOR-LICENSE/github.com/distribution/reference/LICENSE
  third_party/VENDOR-LICENSE/github.com/docker/go-metrics/LICENSE
  third_party/VENDOR-LICENSE/github.com/docker/go-metrics/NOTICE
  third_party/VENDOR-LICENSE/github.com/gorilla/mux/LICENSE
Labels: lgtm, approved, size/XL

#2153 chore: updated BP builder updater
  hack/update-builder.go
Labels: lgtm, approved, size/M

#2149 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2157 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2158 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2159 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2161 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#2162 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2164 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2163 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#2168 typo in run cmd
  cmd/run.go
Labels: lgtm, approved, size/XS, ok-to-test

#2169 Updates to MD file
  docs/reference/func_run.md
Labels: lgtm, approved, size/XS

#2170 Bump to func-go v0.20.0
  generate/zz_filesystem_generated.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/go.sum
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/go.sum
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
Labels: lgtm, approved, size/M

#2156 feat: host builder nonregular file support
  pkg/oci/builder_test.go
  pkg/oci/containerize.go
  pkg/oci/containerize_test.go
  pkg/oci/testdata/test-links/...validName.lnk
  pkg/oci/testdata/test-links/...validName.txt
  pkg/oci/testdata/test-links/a.lnk
  pkg/oci/testdata/test-links/a.txt
  pkg/oci/testdata/test-links/absoluteLink
  pkg/oci/testdata/test-links/absoluteLinkWindows
  pkg/oci/testdata/test-links/b/c/linkToParent
  pkg/oci/testdata/test-links/b/linkOutsideRootsParent
  pkg/oci/testdata/test-links/b/linkToCurrentDir
  pkg/oci/testdata/test-links/b/linkToRoot
  pkg/oci/testdata/test-links/b/linkToRootsParent
  pkg/oci/testdata/test-links/linkToRoot
Labels: lgtm, approved, size/L

#2175 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#2186 unreliable gitlab test skip
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/XS

#1962 Cleanup orphaned func, new image-name calculation
  cmd/build.go
  cmd/client.go
  cmd/client_test.go
  cmd/create.go
  cmd/delete.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  pkg/builders/buildpacks/builder.go
  pkg/builders/s2i/builder.go
  pkg/config/config.go
  pkg/docker/pusher.go
  pkg/docker/pusher_test.go
  pkg/docker/runner.go
  pkg/docker/runner_int_test.go
  pkg/functions/client.go
  pkg/functions/client_int_test.go
  pkg/functions/client_test.go
  pkg/functions/errors.go
  pkg/functions/function.go
  pkg/functions/function_unit_test.go
  pkg/k8s/client.go
  pkg/k8s/openshift.go
  pkg/k8s/persistent_volumes.go
  pkg/knative/deployer.go
  pkg/knative/deployer_test.go
  pkg/knative/describer.go
  pkg/knative/integration_test.go
  pkg/knative/lister.go
  pkg/knative/remover.go
  pkg/mock/deployer.go
  pkg/mock/pipelines_provider.go
  pkg/mock/remover.go
  pkg/oci/pusher.go
  pkg/pipelines/tekton/client.go
  pkg/pipelines/tekton/pac/client.go
  pkg/pipelines/tekton/pipelines_integration_test.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/pipelines_provider_test.go
  pkg/pipelines/tekton/templates.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/XXL, kind/cleanup

#2160 chore: update docker to v25
  go.mod
  go.sum
  pkg/builders/s2i/builder.go
  pkg/builders/s2i/builder_test.go
  pkg/docker/runner.go
  pkg/docker/zz_close_guarding_client_generated.go
  third_party/VENDOR-LICENSE/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/containerd/typeurl/v2/LICENSE
  third_party/VENDOR-LICENSE/github.com/felixge/httpsnoop/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/go-logr/stdr/LICENSE
  third_party/VENDOR-LICENSE/github.com/moby/sys/user/LICENSE
  third_party/VENDOR-LICENSE/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/LICENSE
  third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/LICENSE
  third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/metric/LICENSE
  third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/trace/LICENSE
Labels: lgtm, approved, size/XXL

#2188 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/k8s/persistent_volumes.go
  test/e2e/scenario_config-volumes_test.go
  third_party/VENDOR-LICENSE/github.com/gorilla/websocket/LICENSE
  third_party/VENDOR-LICENSE/github.com/mxk/go-flowrate/flowrate/LICENSE
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
Labels: lgtm, approved, size/L

#2189 chore: Update setup E2E to match latest Knative release
  hack/allocate.sh
  hack/binaries.sh
Labels: size/S, lgtm, approved, kind/chore, kind/cleanup

#2194 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved
