Repository knative/func, pull requests merged in 2024-03, with the labels that each got.

#2195 feat: host builder metadata envs
  pkg/oci/builder_test.go
  pkg/oci/containerize.go
Labels: kind/enhancement, lgtm, approved, size/L

#2198 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2199 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#2200 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2197 chore: Refactor cluster allocation script to use latest Knative bits
  hack/allocate.sh
Labels: lgtm, approved, size/M

#2205 src: remove redundant workflows
  .github/workflows/build.yaml
  .github/workflows/check.yaml
Labels: lgtm, approved, size/M, kind/cleanup

#2207 fix: Fix missing bash function in allocate.sh script
  hack/allocate.sh
Labels: size/S, lgtm, approved

#2208 chore: bump CE dep
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2210 chore: func-go v0.20.1
  generate/zz_filesystem_generated.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/go.sum
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/go.sum
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
Labels: lgtm, approved, size/M, kind/chore

#2201 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2214 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2219 chore: update CA bundle
  generate/zz_filesystem_generated.go
  templates/certs/ca-certificates.crt
Labels: lgtm, approved, size/M

#2215 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2216 test: update gitserver test image
  test/gitserver.sh
Labels: lgtm, approved, size/XS, kind/cleanup

#2212 Drop replace directive
  go.mod
  go.sum
  pkg/docker/creds/credentials.go
  pkg/docker/creds/credentials_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.github/workflows/go-retryablehttp.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client_test.go
  third_party/go.mod
Labels: lgtm, approved, size/L

#2222 [release-1.13 ]Bump to latest of GO SDK for CE
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2223 [release-1.12] Bump to latest of GO SDK for CE
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2224 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2227 func-go v1.21.3 - idiomatic handler signatures
  .github/composite/go-setup/action.yaml
  generate/zz_filesystem_generated.go
  hack/allocate.sh
  pkg/functions/testdata/testClientRunReadiness/f.go
  pkg/functions/testdata/testClientRunTimeout/f.go
  templates/go/.instanced-cloudevents/go.mod
  templates/go/.instanced-http/function.go
  templates/go/.instanced-http/go.mod
  templates/go/cloudevents/go.mod
  templates/go/http/go.mod
  templates/go/http/handle.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/go.sum
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/go.sum
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/go.sum
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/go.sum
Labels: lgtm, approved, size/L

#2230 update templates to work with func-go
  generate/zz_filesystem_generated.go
  templates/go/.instanced-http/function_test.go
  templates/go/http/handle.go
  templates/go/http/handle_test.go
  templates/go/scaffolding/static-http/main.go
Labels: size/S, lgtm, approved

#2225 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2231 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2234 Introduce a --registry-insecure flag
  cmd/build.go
  cmd/deploy.go
  cmd/root.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/oci/pusher.go
  pkg/oci/pusher_test.go
Labels: lgtm, approved, size/M

#2229 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2240 src: remove unused args
  cmd/config_git.go
  cmd/config_git_remove.go
  cmd/config_git_set.go
  cmd/config_labels.go
  cmd/deploy_test.go
  cmd/invoke.go
  cmd/languages.go
  cmd/repository.go
  cmd/run.go
  cmd/subscribe.go
  cmd/templates.go
  cmd/version.go
Labels: lgtm, approved, size/M, kind/cleanup

#2239 src: remove unrechable condition
  pkg/functions/client.go
Labels: lgtm, approved, size/XS, kind/cleanup

#2232 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2242 Basic auth
  cmd/build.go
  cmd/build_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  go.mod
  go.sum
  pkg/functions/client.go
  pkg/functions/client_test.go
  pkg/mock/pusher.go
  pkg/oci/mock/registry.go
  pkg/oci/pusher.go
  pkg/oci/pusher_test.go
  third_party/VENDOR-LICENSE/cloud.google.com/go/compute/metadata/LICENSE
Labels: lgtm, approved, size/XL

#2246 Standalone deploy binary/image
  .github/workflows/ci.yaml
  .github/workflows/test-podman.yaml
  Dockerfile.utils
  cmd/func-deployer/main.go
  hack/setup-testing-images.sh
  pkg/k8s/dialer.go
  pkg/k8s/persistent_volumes.go
  pkg/k8s/persistent_volumes_test.go
  pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: lgtm, approved, size/L

#2249 Usage of only proper handler API, no longer need for redundant Context
  docs/function-templates/golang.md
Labels: lgtm, approved, size/XS

#2254 Fixing Rust version to 1.76.0
  generate/zz_filesystem_generated.go
  hack/update-builder.go
  templates/rust/manifest.yaml
Labels: lgtm, approved, size/XS

#2250 Setup test images before integration test run
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#2245 make was not called #2234
  docs/reference/func_build.md
  docs/reference/func_deploy.md
Labels: lgtm, approved, size/XS

#2253 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2256 func invoke handles json properly
  pkg/functions/invoke.go
Labels: kind/bug, size/S, lgtm, approved

#2258 Fix utils image build
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS
