Repository knative/func, pull requests merged in 2024-10, with the labels that each got.

#2527 Remove unnecessary annotations from Pipeline-as-Code template
  pkg/pipelines/tekton/templates_s2i.go
Labels: lgtm, approved, size/XS, kind/cleanup

#2530 Set default value for REGISTRY param on func-s2i task
  pkg/pipelines/tekton/tasks.go
Labels: lgtm, approved, size/XS, kind/cleanup

#2526 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2534 Updated JS/TS template dependencies
  generate/zz_filesystem_generated.go
  templates/node/cloudevents/package-lock.json
  templates/node/cloudevents/package.json
  templates/node/http/package-lock.json
  templates/node/http/package.json
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/package-lock.json
Labels: lgtm, approved, size/XXL

#2533 test: making e2e config tests builder agnostic
  test/e2e/scenario_config-envs_test.go
  test/e2e/scenario_config-labels_test.go
  test/e2e/scenario_config-volumes_test.go
  test/e2e/scenario_remote-repository_test.go
Labels: size/S, lgtm, approved, kind/cleanup

#2536 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2537 Remove dependecy for boson-project git repository on e2e tests
  test/e2e/scenario_config-envs_test.go
  test/e2e/scenario_config-volumes_test.go
  test/e2e/scenario_remote-repository_test.go
  test/oncluster/scenario_remote-repository_test.go
  test/templates/go/testenvs/go.mod
  test/templates/go/testenvs/handle.go
  test/templates/go/testvolumes/go.mod
  test/templates/go/testvolumes/handle.go
Labels: lgtm, approved, size/L, kind/cleanup

#2535 Fix symlink path separators
  pkg/builders/s2i/builder.go
  pkg/pipelines/tekton/pipelines_provider.go
Labels: lgtm, approved, size/XS

#2540 Enforce branch on test remote repository
  .github/workflows/test-unit.yaml
  test/oncluster/scenario_remote-repository_test.go
Labels: size/S, lgtm, approved, kind/cleanup

#2538 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#2539 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2543 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2541 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2544 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2549 Update Knative deps to release 1.16
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2551 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2553 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2554 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2555 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved
