Repository knative/func, pull requests merged in 2024-07, with the labels that each got.

#2406 update typescript template dependencies
  generate/zz_filesystem_generated.go
  templates/typescript/cloudevents/package-lock.json
  templates/typescript/cloudevents/package.json
  templates/typescript/http/package-lock.json
  templates/typescript/http/package.json
Labels: kind/enhancement, lgtm, approved, size/XXL, ok-to-test

#2400 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2408 chore: do not publish removed tkn tasks
  hack/release.sh
Labels: lgtm, approved, size/XS

#2412 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2410 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M, ok-to-test

#2413 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2414 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS, ok-to-test

#2415 chore: update CA bundle
  generate/zz_filesystem_generated.go
  hack/test.sh
  templates/certs/ca-certificates.crt
  templates/python/cloudevents/test_func.py
  templates/python/http/func.py
  templates/python/http/test_func.py
  templates/quarkus/cloudevents/README.md
  templates/quarkus/http/README.md
  templates/springboot/cloudevents/pom.xml
  templates/springboot/cloudevents/src/test/java/echo/SpringCloudEventsApplicationTests.java
  templates/springboot/http/pom.xml
  templates/springboot/http/src/main/resources/application.properties
Labels: lgtm, approved, size/M

#2420 Fix linter issues
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .golangci.yaml
  CHANGELOG.md
  cmd/environment.go
  cmd/templates.go
  cmd/version.go
  docs/CONTRIBUTING.md
  docs/function-templates/golang.md
  docs/function-templates/nodejs.md
  docs/function-templates/python.md
  docs/function-templates/quarkus.md
  docs/function-templates/typescript.md
  docs/reference/func_yaml.md
  hack/allocate.sh
  hack/registry.sh
  hack/test.sh
  pkg/functions/client.go
  pkg/functions/client_int_test.go
  pkg/functions/client_test.go
  pkg/functions/templates_test.go
  pkg/functions/testdata/repositories/customLanguagePackRepo/templates/customRuntime/customTemplate/custom.impl
  pkg/functions/testdata/repositories/customLanguagePackRepo/templates/manifestedRuntime/customTemplate/custom.impl
  pkg/functions/testdata/repositories/customLanguagePackRepo/templates/manifestedRuntime/manifestedTemplate/custom.impl
  pkg/functions/testdata/repositories/customTemplateRepo/README.md
  pkg/functions/testdata/repositories/customTemplateRepo/customRuntime/customTemplate/custom.impl
  pkg/functions/testdata/repositories/customTemplateRepo/node/json/index.js
  pkg/functions/testdata/repositories/customTemplateRepo/node/json/json.js
  pkg/knative/deployer.go
  pkg/utils/names.go
  schema/func_yaml-schema.json
  schema/generator/main.go
  test/patch_network.sh
Labels: lgtm, approved, size/L

#2417 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2423 chore: linter should ignore test data symlinks
  .gitattributes
Labels: lgtm, approved, size/XS

#2421 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2422 Cron GH Action to update CA bundle
  .github/workflows/update-ca-bundle.yaml
  hack/update-ca-bundle.js
Labels: lgtm, approved, size/L

#2425 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2390 fix: Allow undigested images to be deployed directly
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/run.go
Labels: lgtm, approved, size/L

#2426 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2429 Fix PaC detection for Red Hat's Sandbox cluster
  pkg/pipelines/tekton/pac/pac.go
Labels: lgtm, approved, size/XS

#2433 fix: springboot updater missing EOL
  hack/update-springboot-platform.js
Labels: lgtm, approved, size/XS

#2434 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2435 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2440 Fix failure in GHA caused by missing cargo bin
  .github/workflows/test-unit.yaml
Labels: lgtm, approved, size/XS

#2441 Include go.sum in the Go CloudEvent template
  .gitignore
  Makefile
  generate/zz_filesystem_generated.go
  templates/go/cloudevents/go.mod
  templates/go/cloudevents/go.sum
Labels: lgtm, approved, size/M

#2437 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2442 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2401 Adding GO s2i to e2e test suite
  test/e2e/scenario_runtime-http_test.go
Labels: lgtm, approved, size/XS

#2446 Remove superfluous equals sign from envvar
  generate/zz_filesystem_generated.go
  hack/release.sh
  templates/rust/cloudevents/Cargo.lock
  templates/rust/http/Cargo.lock
Labels: lgtm, approved, size/XXL

#2450 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
