Repository knative/func, pull requests merged in 2024-11, with the labels that each got.

#2559 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2564 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2573 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2568 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2576 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2577 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2587 Fix missing workspaces decl in the scaffold task
  pkg/pipelines/tekton/tasks.go
Labels: kind/bug, lgtm, approved, size/XS

#2599 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, skip-review

#2601 bump builder image
  Dockerfile.utils
Labels: lgtm, approved, size/XS

#2602 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved
