Repository knative/func, pull requests merged in 2024-01, with the labels that each got.

#2109 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#2110 test: adding e2e test for func subscribe command
  hack/binaries.sh
  test/e2e/scenario_subscribe_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#2111 adding `--path` option to `subscribe` command
  cmd/subscribe.go
Labels: kind/enhancement, lgtm, approved, size/XS

#2112 fix: GitLab test
  hack/install-gitlab.sh
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/XS

#2113 doc: update func subscribe doc
  docs/reference/func_subscribe.md
Labels: lgtm, approved, size/XS

#2115 Smooth syntax and pass only in the filters not the entire config
  cmd/subscribe.go
Labels: lgtm, approved, size/XS

#2114 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2116 Dont duplicate subscriptions
  cmd/subscribe.go
  cmd/subscribe_test.go
Labels: lgtm, approved, size/L

#2117 chore: use Quarkus BP instead of explicit envvars
  generate/zz_filesystem_generated.go
  templates/quarkus/cloudevents/README.md
  templates/quarkus/http/README.md
  templates/quarkus/manifest.yaml
Labels: size/S, lgtm, approved

#2119 Invoke instanced CE function's handle withNew()
  generate/zz_filesystem_generated.go
  templates/certs/ca-certificates.crt
  templates/go/.instanced-cloudevents/function_test.go
Labels: lgtm, approved, size/L

#2118 Testing two sources(brokers) and third invocation for an override on the first
  cmd/subscribe_test.go
Labels: lgtm, approved, size/M

#2123 fix: use correct Go version in GH action
  .github/workflows/update-quarkus-platform.yaml
  .github/workflows/update-springboot-platform.yaml
Labels: lgtm, approved, size/XS

#2121 Adding local field to function for handling transient spec (Local.Remote)
  cmd/deploy.go
  cmd/deploy_test.go
  pkg/functions/function.go
  pkg/functions/function_test.go
  pkg/pipelines/tekton/gitlab_test.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/L

#2125 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2126 Springboot bumps
  .github/workflows/ci.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/update-quarkus-platform.yaml
  .github/workflows/update-springboot-platform.yaml
  generate/zz_filesystem_generated.go
  pkg/builders/s2i/builder.go
  templates/springboot/cloudevents/pom.xml
  templates/springboot/http/pom.xml
  templates/springboot/manifest.yaml
Labels: lgtm, approved, size/M

#2129 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2130 Bump for GO-GIT 5.11
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/dario.cat/mergo/LICENSE
  third_party/VENDOR-LICENSE/github.com/cyphar/filepath-securejoin/LICENSE
  third_party/VENDOR-LICENSE/github.com/skeema/knownhosts/NOTICE
Labels: lgtm, approved, size/L

#2132 fix: springboot version auto-updater
  hack/update-springboot-platform.js
Labels: size/S, lgtm, approved

#2135 Remove toolchain directive
  go.mod
Labels: lgtm, approved, size/XS

#2133 [release-1.12] Bump for GO-GIT 5.11
  Makefile
  go.mod
  go.sum
  hack/install-gitlab.sh
  pkg/pipelines/tekton/gitlab_test.go
  third_party/VENDOR-LICENSE/dario.cat/mergo/LICENSE
  third_party/VENDOR-LICENSE/github.com/cyphar/filepath-securejoin/LICENSE
  third_party/VENDOR-LICENSE/github.com/skeema/knownhosts/NOTICE
Labels: lgtm, approved, size/L

#2136 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/antlr/antlr4/runtime/Go/antlr/v4/LICENSE
  third_party/VENDOR-LICENSE/github.com/google/gnostic-models/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  third_party/VENDOR-LICENSE/golang.org/x/exp/LICENSE
Labels: lgtm, approved, size/XL
