Repository knative/func, pull requests merged in 2024-04, with the labels that each got.

#2260 Update Rust BP
  hack/update-builder.go
Labels: lgtm, approved, size/XS

#2247 src: improved setup scripts
  .github/workflows/ci.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .gitignore
  hack/allocate.sh
  hack/binaries.sh
  hack/common.sh
  hack/delete.sh
  hack/install-binaries.sh
  hack/install-git-server.sh
  hack/install-gitlab.sh
  hack/install-pac.sh
  hack/install-tekton.sh
  hack/patch-hosts.sh
  hack/registry.sh
  hack/tekton.sh
  hack/test.sh
  pkg/functions/client_int_test.go
  test/README.md
Labels: lgtm, approved, size/XL, kind/cleanup

#2261 Update deps
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2265 Update Knative deps to latest
  go.mod
  go.sum
  pkg/knative/deployer.go
  plugin/plugin.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/go.mod
  third_party/VENDOR-LICENSE/github.com/pelletier/go-toml/v2/LICENSE
  third_party/VENDOR-LICENSE/github.com/spf13/viper/LICENSE
Labels: lgtm, approved, size/L

#2264 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2270 Clean up e2e oncluster test
  test/common/gitserver.go
  test/oncluster/scenario_basic_test.go
  test/oncluster/scenario_context-dir_test.go
  test/oncluster/scenario_from-cli_test.go
  test/oncluster/scenario_revision_test.go
  test/oncluster/scenario_runtime_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#2262 chore: func-utils image has appropriate labels
  .github/workflows/ci.yaml
  Dockerfile.utils
Labels: size/S, lgtm, approved

#2266 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2271 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2274 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2277 chore: make tkn taks urls setable via linker flags
  pkg/pipelines/tekton/templates.go
Labels: size/S, lgtm, approved

#2273 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2217 chore: update node to v20
  pkg/builders/s2i/builder.go
  test/e2e/scenario_runtime-cloudevents_test.go
  test/e2e/scenario_runtime-http_test.go
  test/oncluster/scenario_runtime_test.go
Labels: lgtm, approved, size/M

#2279 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved
