Repository knative/func, pull requests merged in 2024-08, with the labels that each got.

#2449 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2454 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2455 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2457 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2458 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2461 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2463 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2468 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2470 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2445 allow digested images to be 'run'
  cmd/build.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/run.go
  cmd/run_test.go
  pkg/docker/runner_int_test.go
  pkg/functions/client.go
  pkg/functions/client_int_test.go
  pkg/oci/pusher_test.go
Labels: kind/enhancement, lgtm, approved, size/XL

#2475 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS
