Repository knative/func, pull requests merged in 2024-05, with the labels that each got.

#2281 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#2285 fix: Disable flaky unit test Test_deployerNamespace
  pkg/knative/deployer_test.go
Labels: lgtm, approved, size/XS

#2288 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2286 fix: Fix Test_deployerNamespace with empty kubeconfig
  pkg/knative/deployer.go
  pkg/knative/deployer_test.go
  pkg/knative/testdata/test_empty
Labels: size/S, lgtm, approved

#2290 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2291 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2294 Remove axios dependency
  .github/composite/go-setup/action.yaml
  .github/workflows/update-quarkus-platform.yaml
  .github/workflows/update-springboot-platform.yaml
  hack/update-quarkus-platform.js
  hack/update-springboot-platform.js
Labels: size/S, lgtm, approved

#2296 chore: update paketo dep
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2297 fix: call appropriate script in CI GH action
  .github/workflows/ci.yaml
Labels: size/S, lgtm, approved

#2298 chore: update GH actions
  .github/workflows/ci.yaml
  .github/workflows/schema.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-embedded-fs.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/update-builder.yaml
  .github/workflows/update-quarkus-platform.yaml
  .github/workflows/update-springboot-platform.yaml
Labels: lgtm, approved, size/M

#2295 fix: pin octokit npm module version to 3
  .github/workflows/update-quarkus-platform.yaml
  .github/workflows/update-springboot-platform.yaml
Labels: lgtm, approved, size/XS

#2292 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2305 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2301 chore: upload coverage of unittests together
  .github/workflows/test-unit.yaml
Labels: size/S, lgtm, approved

#2308 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2310 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#2187 fix: test and namespace isolation
  cmd/build_test.go
  cmd/client.go
  cmd/client_test.go
  cmd/completion_util.go
  cmd/config_git_remove.go
  cmd/config_git_set.go
  cmd/create_test.go
  cmd/delete.go
  cmd/delete_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/describe.go
  cmd/describe_test.go
  cmd/environment.go
  cmd/invoke.go
  cmd/invoke_test.go
  cmd/languages_test.go
  cmd/list.go
  cmd/list_test.go
  cmd/repository_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/run_test.go
  cmd/subscribe_test.go
  cmd/templates_test.go
  cmd/testdata/TestDeploy_NamespaceDefaults/TestDeploy_NamespaceRedeployWarning/kubeconfig
  cmd/testdata/Test_defaultNamespace/func/config.yaml
  cmd/testdata/Test_defaultNamespace/kubeconfig
  hack/install-gitlab.sh
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/functions/client.go
  pkg/functions/client_int_test.go
  pkg/functions/client_test.go
  pkg/functions/function.go
  pkg/functions/instances.go
  pkg/functions/instances_test.go
  pkg/knative/deployer.go
  pkg/knative/deployer_test.go
  pkg/knative/describer.go
  pkg/knative/integration_test.go
  pkg/knative/lister.go
  pkg/mock/deployer.go
  pkg/mock/describer.go
  pkg/mock/lister.go
  pkg/mock/pipelines_provider.go
  pkg/pipelines/tekton/client.go
  pkg/pipelines/tekton/gitlab_test.go
  pkg/pipelines/tekton/pipelines_integration_test.go
  pkg/pipelines/tekton/pipelines_pac_provider.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/resources.go
  pkg/pipelines/tekton/validate.go
  pkg/testing/testing.go
  test/oncluster/scenario_github_test.go
  test/oncluster/tekton.go
Labels: kind/bug, lgtm, approved, size/XXL, kind/cleanup

#2203 feat: s2i builder go support
  .gitignore
  pkg/builders/s2i/assemblers.go
  pkg/builders/s2i/builder.go
  pkg/builders/s2i/builder_test.go
  pkg/oci/pusher_test.go
  pkg/pipelines/tekton/validate_test.go
Labels: kind/enhancement, lgtm, approved, size/L

#2311 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2314 Fix PaC build
  pkg/pipelines/tekton/gitlab_test.go
  pkg/pipelines/tekton/pac/client.go
  pkg/pipelines/tekton/templates.go
Labels: size/S, lgtm, approved

#2317 fix: pipeline run yaml format for newer PaC
  pkg/pipelines/tekton/templates.go
Labels: lgtm, approved, size/XS

#2315 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2321 chore: cluster log
  .github/workflows/test-integration.yaml
Labels: size/S, lgtm, approved

#2320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2323 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2324 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2284 Use image index not just image
  pkg/docker/pusher.go
  pkg/docker/pusher_test.go
Labels: lgtm, approved, size/L

#2328 chore: update images ubi8 => ubi9
  pkg/builders/s2i/builder.go
Labels: lgtm, approved, size/XS

#2327 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2333 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
