Repository knative/func, pull requests merged in 2025-10, with the labels that each got.

#3064 Update gitlab library
  go.mod
  go.sum
  pkg/git/gitlab/gitlab.go
  pkg/pipelines/tekton/gitlab_int_test.go
Labels: lgtm, approved, size/M

#3062 fix the platform restriction error providing more educational guidance
  cmd/build.go
  cmd/deploy.go
  pkg/functions/errors.go
Labels: kind/enhancement, lgtm, approved, size/M, needs-ok-to-test

#3070 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, skip-review

#3071 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/M, skip-review
