Repository knative/func, pull requests merged in 2025-01, with the labels that each got.

#2632 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2634 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2635 Set annotations on builder images
  hack/update-builder.go
Labels: lgtm, approved, size/XS

#2636 Enable Go ARM64 buildpack
  hack/update-builder.go
Labels: lgtm, approved, size/L

#2639 Update deps
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2641 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2643 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2645 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2646 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2647 Remove gauron image references in code
  cmd/deploy_test.go
  pkg/docker/runner_int_test.go
Labels: lgtm, approved, size/M

#2649 Bump s2i dep
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2652 Update deps to match latest Knative versions
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL

#2656 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2657 use knative go setup in ci
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS, kind/cleanup

#2658 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2654 Remove dependency on docker hub
  .github/workflows/ci.yaml
  .gitignore
  Dockerfile.utils
  hack/fetch-util-img-prerequisites.sh
  hack/setup-testing-images.sh
Labels: lgtm, approved, size/M

#2660 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2661 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2662 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2653 Remove usage of ttl.sh
  .github/workflows/test-e2e-oncluster.yaml
  pkg/docker/pusher.go
  pkg/pipelines/tekton/gitlab_test.go
Labels: lgtm, approved, size/XS

#2650 test for func run with digested image override
  cmd/run_test.go
Labels: lgtm, approved, size/M

#2664 fix: capitalise kind broker and bump versions in script
  hack/allocate.sh
  hack/install-binaries.sh
Labels: size/S, lgtm, approved

#2667 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2672 Go tar
  Dockerfile.utils
  cmd/func-util/main.go
  go.mod
  pkg/k8s/dialer.go
  pkg/k8s/testdata/content.tar
  pkg/tar/tar.go
  pkg/tar/tar_basic_test.go
  pkg/tar/tar_errors_test.go
Labels: lgtm, approved, size/XL

#2673 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2675 Set platform of builder image
  Dockerfile.utils
Labels: lgtm, approved, size/XS

#2679 Fix multiarch image build
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#2663 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2680 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2681 Create test symlinks dynamically
  pkg/oci/containerize_test.go
  pkg/oci/testdata/test-links/absoluteLink
  pkg/oci/testdata/test-links/absoluteLinkWindows
Labels: size/S, lgtm, approved

#2670 fix: struct naming in instanced go http templates synced
  generate/zz_filesystem_generated.go
  templates/go/.instanced-http/function.go
Labels: lgtm, approved, size/XS
