Repository knative/func, pull requests merged in 2025-04, with the labels that each got.

#2753 Allow host mounts for build phahse
  pkg/builders/builders_int_test.go
  pkg/builders/buildpacks/builder.go
  pkg/functions/function.go
  schema/func_yaml-schema.json
Labels: lgtm, approved, size/M, ok-to-test

#2764 Use s2i in standard mode, not "as-dockerfile"
  pkg/builders/s2i/builder.go
  pkg/builders/s2i/builder_test.go
Labels: lgtm, approved, size/XL

#2765 Improvements for Go s2i assembler
  pkg/builders/s2i/assemblers.go
Labels: kind/bug, lgtm, approved, size/XS

#2766 S2I (source-to-image) host binds
  pkg/builders/builders_int_test.go
  pkg/builders/s2i/builder.go
Labels: lgtm, approved, size/L

#2768 Make build binds more similar to runtime binds
  pkg/functions/function.go
  schema/func_yaml-schema.json
Labels: size/S, lgtm, approved

#2771 Add guideline for private Go module usage
  generate/zz_filesystem_generated.go
  templates/go/cloudevents/README.md
  templates/go/http/README.md
Labels: lgtm, approved, size/M

#2769 Fix: Go scaffolding uses correct module name
  pkg/scaffolding/scaffold.go
  pkg/scaffolding/scaffold_test.go
  pkg/scaffolding/testdata/testwrite/go/scaffolding/instanced-http/go.mod
Labels: lgtm, approved, size/M

#2770 Fix Python S2I On-Cluster build
  cmd/func-util/main.go
Labels: size/S, lgtm, approved

#2774 Fixes buildpack builders
  .github/workflows/update-builder.yaml
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/XS

#2777 Fix buildpacks builder update task
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/XS

#2775 Mirror buildpack run images in ghcr.io/knative
  .github/workflows/update-builder.yaml
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/M

#2778 Update rust buildpack
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/XS

#2781 Migrate golangci-lint config to v2
  .golangci.yaml
Labels: lgtm, approved, size/M

#2783 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2780 Make base jammy stack multi-arch
  .github/workflows/update-builder.yaml
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/L

#2784 Bump golangci-lint version
  Makefile
Labels: lgtm, approved, size/XS

#2785 Refactor if-elif-else => switch
  cmd/build.go
  cmd/config.go
  pkg/docker/docker_client_ssh_test.go
  pkg/functions/client.go
  pkg/functions/invoke.go
  pkg/pipelines/tekton/templates.go
  pkg/pipelines/tekton/validate.go
  pkg/tar/tar.go
Labels: lgtm, approved, size/L

#2788 Update e2e ci workflow to test against arm for go and quarkus
  .github/workflows/test-e2e-runtime.yaml
Labels: size/S, lgtm, approved, kind/cleanup

#2787 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2789 Enable arm64 python buildpack
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/L

#2790 Do not run builder build unnecessary
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/M

#2793 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2794 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2796 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2797 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2798 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2807 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2809 fix e2e errorf formatting for 1.24
  test/e2e/main_test.go
Labels: lgtm, approved, size/XS

#2810 fix: e2e scenarion config test errorf format for go 1.24
  test/e2e/scenario_config-envs_test.go
Labels: lgtm, approved, size/XS

#2800 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2817 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2820 upgrade podman-next packages to fedora 41 for nightly podman test
  .github/workflows/test-podman-next.yaml
Labels: lgtm, approved, size/XS

#2819 Fix: do not override uid/git in buildpack builder
  pkg/builders/builders_int_test.go
  pkg/builders/buildpacks/builder.go
Labels: lgtm, approved, size/XS

#2818 Make docker.io/heroku/ builders trusted
  pkg/builders/buildpacks/builder.go
Labels: lgtm, approved, size/XS
