Repository knative/func, pull requests merged in 2025-06, with the labels that each got.

#2836 feat: adds command for mcp server
  cmd/mcp.go
  cmd/root.go
  docs/reference/func.md
  docs/reference/func_mcp.md
  go.mod
  go.sum
  pkg/mcp/mcp.go
Labels: lgtm, approved, size/L, needs-ok-to-test

#2856 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2889 mcp: extends flags support for existing tools
  pkg/mcp/mcp.go
Labels: lgtm, approved, size/L, ok-to-test

#2876 feat: support FUNC_GIT env in Host builder
  pkg/oci/builder.go
Labels: kind/enhancement, size/S, lgtm, approved

#2878 chore: add missing .PHONY statements to Makefile
  Makefile
Labels: lgtm, approved, size/M

#2881 fix: remove redundant initialized check
  cmd/build.go
Labels: lgtm, approved, size/XS, kind/cleanup

#2879 feat: add noninteractive path to func config envs remove
  cmd/config_envs.go
  docs/reference/func_config_envs_remove.md
Labels: kind/enhancement, lgtm, approved, size/M

#2867 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2896 ci: install Tekton and PAC in cluster by default
  .github/workflows/ci.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-integration.yaml
  docs/building-functions/on_cluster_build.md
  hack/allocate.sh
  hack/cmd/update-knative-components/main.go
  hack/cmd/update-knative-components/main_test.go
  hack/component-versions.json
  hack/component-versions.sh
  hack/install-pac.sh
  hack/install-tekton.sh
  test/README.md
Labels: lgtm, approved, size/L, kind/cleanup

#2880 feat: add LISTEN_ADDRESS to Python default runner
  pkg/functions/runner.go
Labels: kind/enhancement, lgtm, approved, size/XS

#2885 feat: improved error on remote deploy without local source
  cmd/deploy.go
Labels: kind/enhancement, size/S, lgtm, approved

#2897 feat: macos support for dev cluster scripts
  hack/allocate.sh
  hack/common.sh
  hack/install-binaries.sh
  hack/registry.sh
Labels: kind/enhancement, lgtm, approved, size/L
