Repository knative/func, pull requests merged in 2025-03, with the labels that each got.

#2727 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2730 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2734 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2733 Refactor data member of the InvokeMessage to be []byte
  cmd/invoke.go
  pkg/functions/client_test.go
  pkg/functions/invoke.go
Labels: kind/enhancement, lgtm, approved, size/M, ok-to-test

#2737 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2695 Remove direct dep on golang.org/x/exp
  go.mod
  pkg/builders/s2i/builder.go
Labels: lgtm, approved, size/XS

#2740 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2739 Add a retry functionality to workflows
  .github/workflows/ci.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-podman.yaml
Labels: lgtm, approved, size/L

#2741 golangci bump in Makefile
  Makefile
Labels: lgtm, approved, size/XS

#2742 Fix https port 433 => 443
  hack/allocate.sh
Labels: lgtm, approved, size/XS

#2747 Add git BP to our Go detection group
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/XS

#2748 Add testcase for Go private repositories
  pkg/builders/builders_int_test.go
  pkg/builders/testdata/go-fn-with-private-deps/.funcignore
  pkg/builders/testdata/go-fn-with-private-deps/.gitignore
  pkg/builders/testdata/go-fn-with-private-deps/README.md
  pkg/builders/testdata/go-fn-with-private-deps/func.yaml
  pkg/builders/testdata/go-fn-with-private-deps/go.mod
  pkg/builders/testdata/go-fn-with-private-deps/go.sum
  pkg/builders/testdata/go-fn-with-private-deps/handle.go
  pkg/builders/testdata/go-fn-with-private-deps/handle_test.go
Labels: lgtm, approved, size/L

#2749 fix: create custom http transport for each run for Auth tests
  pkg/docker/creds/credentials_test.go
Labels: lgtm, approved, size/L

#2743 Adding workflow to test against podman nightly build
  .github/workflows/test-podman-next.yaml
Labels: lgtm, approved, size/M, kind/cleanup

#2751 Test adjustments
  pkg/builders/builders_int_test.go
  pkg/builders/testdata/go-fn-with-private-deps/go.mod
  pkg/builders/testdata/go-fn-with-private-deps/go.sum
Labels: size/S, lgtm, approved

#2755 Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: lgtm, approved, size/XS, kind/documentation, needs-ok-to-test

#2746 Removes redundant default labels and annotations
  pkg/functions/function.go
  pkg/functions/function_unit_test.go
  pkg/k8s/labels/labels.go
  pkg/knative/deployer.go
  pkg/knative/lister.go
Labels: kind/enhancement, lgtm, approved, size/M, needs-ok-to-test

#2763 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
