Repository knative/func, pull requests merged in 2025-05, with the labels that each got.

#2821 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2825 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS, ok-to-test

#2826 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2773 Cleanup: Codecov update, unify flags and ignore unwanted files
  .codecov.yaml
  .github/workflows/ci.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-unit.yaml
  pkg/docker/appease_coverage_gods_test.go
Labels: lgtm, approved, size/M

#2843 Fix: build correct func-util binary for give arch
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#2838 Fix quarkus buildpack image reference
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/XS

#2839 Add tasks related images to func environment
  cmd/environment.go
Labels: kind/enhancement, lgtm, approved, size/XS

#2842 Issue #2835 - Fix Tekton task "func-buildpacks" prepare/results steps use non-multi-arch bash:5.1.4 image, causing exec format errors on ARM64
  pkg/pipelines/tekton/tasks.go
Labels: kind/bug, lgtm, approved, size/XS, ok-to-test
