Repository knative/func, pull requests merged in 2025-02, with the labels that each got.

#2682 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2683 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2684 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2686 Optimise func-utils image
  .github/workflows/ci.yaml
  Dockerfile.utils
  Makefile
  cmd/func-util/main.go
  cmd/func-util/s2i_generate.go
  func-util-symlinks.tgz
  hack/fetch-util-img-prerequisites.sh
  hack/setup-testing-images.sh
  pkg/k8s/dialer.go
  pkg/k8s/persistent_volumes.go
  pkg/pipelines/tekton/tasks.go
Labels: lgtm, approved, size/L

#2692 Use podman from default Ubuntu registry in workflows
  .github/workflows/test-podman.yaml
Labels: size/S, lgtm, approved

#2694 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#2697 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2677 Have static knative component versions in hack/, update in automatic PR
  .github/workflows/update-builder.yaml
  .github/workflows/update-knative-hack.yaml
  Makefile
  go.mod
  go.sum
  hack/allocate.sh
  hack/cmd/update-builder/main.go
  hack/cmd/update-knative-components/main.go
  hack/cmd/update-knative-components/main_test.go
  hack/component-versions.json
  hack/component-versions.sh
  pkg/git/github/github.go
Labels: lgtm, approved, size/XL

#2698 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2699 fix: Wrong name in update-knative-components workflow
  .github/workflows/update-knative-hack.yaml
Labels: lgtm, approved, size/XS

#2702 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2703 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2693 feat: remote storage class
  cmd/deploy.go
  docs/reference/func_deploy.md
  pkg/functions/function.go
  pkg/k8s/persistent_volumes.go
  pkg/k8s/persistent_volumes_test.go
  pkg/pipelines/tekton/pipelines_provider.go
  pkg/pipelines/tekton/pipelines_provider_test.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/M

#2706 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2705 bump: update codecov to v5 in workflows
  .github/workflows/ci.yaml
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/update-knative-hack.yaml
Labels: size/S, lgtm, approved

#2707 fix: update comment of knative-component auto PR
  hack/cmd/update-knative-components/main.go
Labels: lgtm, approved, size/XS

#2709 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2711 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2714 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2722 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2696 Update pack dep
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2723 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/XS

#2715 Bug: Fixes Incorrect Implementation of --file Option
  cmd/invoke.go
Labels: kind/bug, lgtm, approved, size/XS, ok-to-test

#2726 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2728 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved
