Repository knative/func, pull requests merged in 2025-08, with the labels that each got.

#2954 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2961 Fix for arm64 buildpacks
  hack/cmd/update-builder/main.go
Labels: lgtm, approved, size/M

#2965 fix: Python host builder base image version
  pkg/oci/python_builder.go
Labels: kind/bug, size/S, lgtm, approved

#2963 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2951 mcp: adds remote template support
  pkg/mcp/help.go
  pkg/mcp/mcp.go
Labels: lgtm, approved, size/L, ok-to-test

#2959 cleanup: Simplify hack/ components
  .github/workflows/update-builder.yaml
  .github/workflows/update-knative-hack.yaml
  Makefile
  hack/cmd/components/main.go
  hack/cmd/components/main_test.go
  hack/cmd/update-knative-components/main.go
  hack/cmd/update-knative-components/main_test.go
  hack/component-versions.json
  hack/component-versions.sh
  hack/update-deps.sh
Labels: lgtm, approved, size/XL

#2967 fix: func templates reference in mcp
  pkg/mcp/mcp.go
Labels: lgtm, approved, size/XS

#2969 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, skip-review

#2975 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, skip-review

#2981 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, skip-review

#2991 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, skip-review

#2998 fix-components
  hack/component-versions.json
Labels: lgtm, approved, size/XS

#3001 [release-1.19] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, skip-review
