Repository knative/func, pull requests merged in 2025-07, with the labels that each got.

#2898 feat: Python,Go func listen dual-stack
  pkg/builders/s2i/builder.go
  pkg/oci/go_builder.go
  pkg/oci/python_builder.go
Labels: kind/enhancement, lgtm, approved, size/XS

#2882 feat: add labels to func describe
  cmd/describe.go
  cmd/describe_test.go
  pkg/functions/client.go
  pkg/knative/describer.go
Labels: kind/enhancement, lgtm, approved, size/M

#2904 fix: return better error when using pack+python
  pkg/builders/buildpacks/builder.go
Labels: lgtm, approved, size/XS

#2909 Prevent 503 on e2e subscriber test
  test/e2e/scenario_subscribe_test.go
Labels: lgtm, approved, size/XS

#2894 chore: integration test isolation
  .gitignore
  pkg/functions/client_int_test.go
  pkg/functions/client_test.go
  pkg/functions/function_test.go
  pkg/functions/repositories_test.go
  pkg/functions/repository_test.go
  pkg/functions/templates_test.go
  pkg/functions/testdata/default_home/README.md
  pkg/oci/go_builder.go
Labels: lgtm, approved, size/L, kind/cleanup

#2907 fix: Python local buildpack build
  pkg/builders/buildpacks/builder.go
  pkg/builders/buildpacks/scaffolding_injector.go
Labels: kind/bug, lgtm, approved, size/L

#2915 chore: adds makefile target for embedded FS check
  .github/workflows/test-embedded-fs.yaml
  Makefile
Labels: size/S, lgtm, approved, kind/cleanup

#2911 chore: fix build and test tags
  pkg/docker/creds/credentials_test.go
  pkg/docker/pusher_test.go
  pkg/docker/runner_test.go
  pkg/functions/client_test.go
  pkg/functions/config_test.go
  pkg/functions/function_envs_unit_test.go
  pkg/functions/function_git_unit_test.go
  pkg/functions/function_labels_unit_test.go
  pkg/functions/function_migrations_unit_test.go
  pkg/functions/function_options_unit_test.go
  pkg/functions/function_test.go
  pkg/functions/function_unit_test.go
  pkg/functions/function_volumes_unit_test.go
  pkg/functions/instances_test.go
  pkg/functions/job_test.go
  pkg/functions/repositories_test.go
  pkg/functions/repository_test.go
  pkg/functions/runner_test.go
  pkg/functions/templates_test.go
  pkg/knative/deployer_test.go
  pkg/pipelines/tekton/validate_test.go
  pkg/scaffolding/detectors_test.go
  pkg/scaffolding/scaffold_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#2913 chore: reduce logging verbosity in mocks
  pkg/oci/mock/registry.go
Labels: lgtm, approved, size/XS, kind/cleanup

#2918 Use localtest.me instead of sslip.io
  .github/workflows/test-integration.yaml
  docs/CONTRIBUTING.md
  hack/allocate.sh
  hack/install-gitlab.sh
  hack/patch-hosts.sh
  hack/test.sh
  pkg/builders/builders_int_test.go
  pkg/builders/testdata/go-fn-with-private-deps/go.mod
  pkg/builders/testdata/go-fn-with-private-deps/go.sum
  pkg/builders/testdata/go-fn-with-private-deps/handle.go
  pkg/pipelines/tekton/pipelines_int_test.go
  test/e2e/scenario_subscribe_test.go
Labels: lgtm, approved, size/M

#2890 mcp: adds resources and prompts for func subcommands
  pkg/mcp/mcp.go
Labels: lgtm, approved, size/M, ok-to-test

#2924 fix: refer correct version of schema in func.yaml
  Makefile
  go.mod
  pkg/app/app.go
  pkg/functions/function.go
  pkg/version/version.go
Labels: kind/bug, lgtm, approved, size/M

#2926 test: simplify func-git service
  hack/install-git-server.sh
  test/common/gitserver.go
Labels: lgtm, approved, size/L

#2935 feat: base image flag for host builds
  cmd/build.go
  cmd/build_test.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/run.go
  cmd/run_test.go
  docs/reference/func_build.md
  docs/reference/func_deploy.md
  docs/reference/func_run.md
  pkg/functions/function.go
  pkg/oci/builder.go
  pkg/oci/builder_test.go
  pkg/oci/go_builder.go
  pkg/oci/python_builder.go
  schema/func_yaml-schema.json
Labels: kind/enhancement, lgtm, approved, size/L

#2942 feat: func invoke get requests
  cmd/invoke.go
  docs/reference/func_invoke.md
  pkg/functions/invoke.go
Labels: kind/enhancement, lgtm, approved, size/L

#2922 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2932 docs: python update
  docs/function-templates/python.md
  generate/zz_filesystem_generated.go
  templates/python/cloudevents/README.md
  templates/python/http/README.md
Labels: lgtm, approved, size/XL, kind/documentation

#2931 mcp: adds labels and envs config tools and resources
  pkg/mcp/help.go
  pkg/mcp/mcp.go
  pkg/mcp/tools.go
Labels: lgtm, approved, size/L, needs-ok-to-test

#2920 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2946 fix pod security context fs permissions
  pkg/k8s/security_context.go
Labels: lgtm, approved, size/XS

#2950 fix: linter reporting xml unsupported type
  pkg/functions/client.go
Labels: lgtm, approved, size/XS

#2953 fix: update console output to show both host and port
  cmd/run.go
  test/e2e/scenario_extended_flow_test.go
  test/e2e/scenario_no_container_test.go
Labels: lgtm, approved, size/M, ok-to-test
