Repository knative/func, pull requests merged in 2025-09, with the labels that each got.

#2979 oci: refactors the auth for pusher
  cmd/build.go
  cmd/client.go
  cmd/prompt/prompt.go
  cmd/prompt/prompt_test.go
  pkg/creds/credentials.go
  pkg/creds/credentials_test.go
  pkg/docker/pusher.go
  pkg/docker/pusher_test.go
  pkg/k8s/keychains.go
  pkg/k8s/openshift.go
  pkg/oci/pusher.go
  pkg/pipelines/tekton/gitlab_int_test.go
  pkg/pipelines/tekton/pipelines_int_test.go
  pkg/pipelines/tekton/pipelines_provider.go
Labels: lgtm, approved, size/L, ok-to-test

#3019 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, skip-review

#3025 Improve error message when `func subscribe` is run outside function directory
  cmd/subscribe.go
Labels: kind/enhancement, lgtm, approved, size/XS, needs-ok-to-test, ok-to-test

#3018 Improve error message when `func invoke` is run outside function directory
  cmd/invoke.go
Labels: kind/enhancement, lgtm, approved, size/XS, ok-to-test

#3028 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  hack/component-versions.json
  hack/component-versions.sh
Labels: size/M, skip-review

#3035 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, approved, skip-review

#3040 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, skip-review

#3044 fix: update deprecated function by linter
  cmd/root.go
Labels: lgtm, approved, size/XS

#3016 Improve error message when `--language` flag is missing in `func create`
  cmd/create.go
Labels: kind/enhancement, lgtm, approved, size/XS, ok-to-test

#3020 Adds docs for mcp integration
  docs/mcp-integration/integration.md
Labels: lgtm, approved, size/L, ok-to-test
